import type { Entry } from './summary'
import type { Bilingual, WorkedExample } from './summary-examples'
import type { DerivationStep, SummaryLesson } from './summary-lessons'
import type { VisualTheorem } from './summary-theorems'

export type AlgebraSlideKind = 'setMembership' | 'setBuilder' | 'abstractSets' | 'setEquality' | 'equivalence' | 'firstIso' | 'correspondence' | 'secondIso' | 'thirdIso' | 'symmetricFunctions' | 'cycleConjugation' | 'parityProof' | 'subringTest' | 'booleanRing' | 'ringTheorems' | 'formalPolynomials'
const b = (id: string, en: string): Bilingual => ({ id, en })
const s = (id: string, en: string, textId: string, textEn: string, tex: string): DerivationStep => ({ title: b(id, en), text: b(textId, textEn), tex })
type Definition = { name: Bilingual; text: Bilingual; tex: string; picture: Bilingual }
type Topic = { entry: Entry; lesson: SummaryLesson; definition: Definition; example: WorkedExample }
type Input = { visual: AlgebraSlideKind; title: Bilingual; question: Bilingual; meaning: Bilingual; tex: string; picture: Bilingual; steps: DerivationStep[]; conditions: Bilingual[]; failure: Bilingual; examplePrompt: Bilingual; exampleSteps: DerivationStep[]; check: { question: Bilingual; answer: Bilingual } }
function topic(i: Input): Topic {
  const last = i.exampleSteps[i.exampleSteps.length - 1]
  return {
    entry: { title: i.title, intuition: i.meaning, formulas: [i.tex], insight: i.steps[i.steps.length - 1].text, pitfall: i.failure },
    definition: { name: i.title, text: i.meaning, tex: i.tex, picture: i.picture },
    lesson: { visual: i.visual, question: i.question, steps: i.steps, conditions: i.conditions, failure: i.failure, exampleSteps: i.exampleSteps, check: i.check },
    example: { prompt: i.examplePrompt, work: last.tex, reading: last.text },
  }
}

/** Lessons follow the supplied UI Algebra slides. Textbook topics are retained alongside them. */
export const ALGEBRA_SLIDE_TOPICS: Record<AlgebraSlideKind, Topic> = {
  setMembership: topic({
    visual: 'setMembership', title: b('Anggota, subset, dan himpunan kuasa (Bab 1)', 'Members, subsets, and power sets (Chapter 1)'),
    question: b('Apa bedanya 1, {1}, dan {{1}}?', 'How do 1, {1}, and {{1}} differ?'),
    meaning: b('Simbol ∈ memeriksa satu objek sebagai anggota. Simbol ⊆ memeriksa semua anggota suatu himpunan. Himpunan kuasa P(S) berisi semua subset S; setiap anggotanya adalah himpunan.', 'The symbol ∈ checks one object as a member. The symbol ⊆ checks every member of a set. The power set P(S) contains all subsets of S; each of its members is a set.'),
    tex: String.raw`a\in S,\quad A\subseteq S\iff(\forall a\in A,\ a\in S),\quad\mathcal P(S)=\{A:A\subseteq S\}`,
    picture: b('Kotak besar berisi empat himpunan. Bedakan angka 1, kotak {1}, dan koleksi yang hanya berisi kotak {1}.', 'The large box contains four sets. Distinguish the number 1, the box {1}, and a collection containing only the box {1}.'),
    steps: [
      s('Tentukan jenis objek', 'Identify the object', 'Untuk S={1,2}, angka 1 adalah anggota; {1} adalah subset karena satu-satunya anggotanya, 1, ada di S.', 'For S={1,2}, the number 1 is a member; {1} is a subset because its only member, 1, belongs to S.', String.raw`1\in S,\qquad\{1\}\subseteq S`),
      s('Daftar semua subset', 'List all subsets', 'Setiap anggota S dapat dipilih atau tidak dipilih. Dua anggota memberi empat pilihan: kosong, hanya 1, hanya 2, atau keduanya.', 'Each member can be included or excluded. Two members give four choices: neither, only 1, only 2, or both.', String.raw`\mathcal P(\{1,2\})=\{\varnothing,\{1\},\{2\},\{1,2\}\},\quad |\mathcal P(S)|=2^{|S|}`),
      s('Periksa satu lapis kurung', 'Check one layer of braces', '{1} adalah satu anggota P(S). Namun {1}⊆P(S) salah karena menuntut angka 1 menjadi anggota P(S). {{1}}⊆P(S) benar: anggotanya adalah {1}.', '{1} is one member of P(S). But {1}⊆P(S) is false because it requires the number 1 to belong to P(S). {{1}}⊆P(S) is true: its member is {1}.', String.raw`\{1\}\in\mathcal P(S),\quad 1\notin\mathcal P(S),\quad\{\{1\}\}\subseteq\mathcal P(S)`),
    ],
    conditions: [b('Slide memakai ⊂ untuk subset yang boleh sama. Di sini ⊆ berarti subset, sedangkan ⊊ berarti subset sejati.', 'The slides use ⊂ for a subset that may be equal. Here ⊆ means subset and ⊊ means proper subset.')],
    failure: b('∅∈P(S) dan ∅⊆P(S) sama-sama benar, tetapi alasannya berbeda: yang pertama karena ∅⊆S; yang kedua karena tidak ada anggota ∅ yang melanggar inklusi.', '∅∈P(S) and ∅⊆P(S) are both true, for different reasons: the first because ∅⊆S; the second because no member of ∅ can violate inclusion.'),
    examplePrompt: b('Untuk S={a,b}, bedakan {a}∈P(S) dan {a}⊆P(S).', 'For S={a,b}, distinguish {a}∈P(S) and {a}⊆P(S).'),
    exampleSteps: [s('Buka kurung', 'Open the braces', '{a} adalah himpunan yang anggotanya a. P(S) mempunyai anggota ∅, {a}, {b}, dan {a,b}.', '{a} is a set whose member is a. P(S) has members ∅, {a}, {b}, and {a,b}.', String.raw`\mathcal P(S)=\{\varnothing,\{a\},\{b\},\{a,b\}\}`), s('Uji masing-masing', 'Test each statement', 'Jika a dan b adalah objek dasar yang berbeda, {a}∈P(S) benar, tetapi {a}⊆P(S) salah: a bukan salah satu himpunan di daftar.', 'For distinct basic objects a and b, {a}∈P(S) is true but {a}⊆P(S) is false: a is not one of the listed sets.', String.raw`\{a\}\in\mathcal P(S),\qquad\{\{a\}\}\subseteq\mathcal P(S)`)],
    check: { question: b('Jika |X|=3, berapa anggota {Y:Y⊆X}?', 'If |X|=3, how many members does {Y:Y⊆X} have?'), answer: b('8. Itu P(X), bukan X; setiap dari tiga anggota mempunyai dua pilihan.', '8. It is P(X), not X; each of the three members has two choices.') },
  }),
  setBuilder: topic({
    visual: 'setBuilder', title: b('Notasi pembentuk himpunan: syarat atau hasil (Bab 1)', 'Set builders: a condition or an output (Chapter 1)'),
    question: b('Mengapa {n∈Z:n² genap} berbeda dari {n²:n∈Z}?', 'Why does {n∈Z:n² is even} differ from {n²:n∈Z}?'),
    meaning: b('Bentuk {x∈U:P(x)} menyaring objek x berdasarkan suatu sifat. Bentuk {f(x):x∈U} menghasilkan nilai f(x). Yang pertama memberi syarat pada anggota; yang kedua memberi saksi untuk menghasilkan anggota.', 'The form {x∈U:P(x)} filters objects x by a property. The form {f(x):x∈U} produces values f(x). The first gives a condition on a member; the second gives a witness producing it.'),
    tex: String.raw`a\in\{x\in U:P(x)\}\iff a\in U\land P(a),\qquad a\in\{f(x):x\in U\}\iff\exists x\in U,\ a=f(x)`,
    picture: b('Dua baris menunjukkan bilangan genap I dan kuadrat sempurna J. Geser bilangan yang diuji: 2 hanya di I, 9 hanya di J, dan 4 di keduanya.', 'Two rows show even integers I and perfect squares J. Move the tested number: 2 lies only in I, 9 only in J, and 4 in both.'),
    steps: [
      s('Baca predikat', 'Read the predicate', 'Jika a∈I={n∈Z:n² genap}, hanya diketahui a∈Z dan a² genap. Tidak boleh langsung menulis a=b².', 'If a∈I={n∈Z:n² is even}, you only know a∈Z and a² is even. You cannot immediately write a=b².', String.raw`a\in I\iff a\in\mathbb Z\ \text{and}\ 2\mid a^2`),
      s('Baca nilai yang dihasilkan', 'Read the produced value', 'Jika a∈J={n²:n∈Z}, ada bilangan bulat m dengan a=m². Huruf m adalah saksi dan tidak harus sama dengan a.', 'If a∈J={n²:n∈Z}, some integer m satisfies a=m². The letter m is a witness and need not equal a.', String.raw`a\in J\iff\exists m\in\mathbb Z:\ a=m^2`),
      s('Cari contoh pembeda', 'Find distinguishing examples', '2² genap tetapi 2 bukan kuadrat bulat. Sebaliknya 9=3² tetapi 9² ganjil. Maka I≠J meskipun mempunyai anggota bersama.', '2² is even but 2 is not an integer square. Conversely 9=3² but 9² is odd. Thus I≠J despite shared members.', String.raw`2\in I\setminus J,\quad9\in J\setminus I,\quad4\in I\cap J`),
    ], conditions: [b('Domain U harus diperhatikan. Kuadrat bulat tidak negatif; tetapi bilangan yang kuadratnya genap dapat negatif.', 'Respect the domain U. Integer squares are nonnegative, but an integer with an even square may be negative.')],
    failure: b('P(a) adalah pernyataan, bukan rumus untuk a. Jangan mengubah “a² genap” menjadi “a=a²”.', 'P(a) is a statement, not a formula for a. Do not turn “a² is even” into “a=a²”.'),
    examplePrompt: b('Apakah 5 dan 8 ada dalam M={n²+1:n∈Z}?', 'Do 5 and 8 belong to M={n²+1:n∈Z}?'),
    exampleSteps: [s('Buat persamaan saksi', 'Set up the witness equation', 'Untuk 5, cari n dengan n²+1=5. Untuk 8, cari n²=7.', 'For 5 seek n with n²+1=5. For 8 seek n²=7.', String.raw`5=n^2+1\iff n^2=4,\quad8=n^2+1\iff n^2=7`), s('Putuskan di domain Z', 'Decide within Z', 'n=2 atau −2 menghasilkan 5. Tidak ada bilangan bulat yang kuadratnya 7; jadi 8 tidak termasuk.', 'n=2 or −2 produces 5. No integer has square 7, so 8 is excluded.', String.raw`5\in M,\qquad8\notin M`)],
    check: { question: b('Apakah −4∈I? Apakah −4∈J?', 'Is −4 in I? Is −4 in J?'), answer: b('−4∈I karena (−4)²=16 genap. −4∉J karena semua kuadrat bulat tidak negatif.', '−4∈I because (−4)²=16 is even. −4∉J because all integer squares are nonnegative.') },
  }),
  abstractSets: topic({
    visual: 'abstractSets', title: b('Himpunan berisi matriks, fungsi, atau objek abstrak (Bab 1)', 'Sets of matrices, functions, or abstract objects (Chapter 1)'),
    question: b('Apa yang benar-benar diketahui saat mengambil a∈H?', 'What do we actually know when taking a∈H?'),
    meaning: b('Objek anggota tidak harus bilangan. Jika H={x∈X:P(x)}, keanggotaan berarti jenis objeknya sesuai X dan sifat P benar. Ambil unsur sembarang tanpa menebak bentuk yang tidak diberikan.', 'Members need not be numbers. For H={x∈X:P(x)}, membership means the object belongs to X and satisfies P. Take an arbitrary member without inventing an unsupported form.'),
    tex: String.raw`H=\{A\in M_2(\mathbb R):\det A=0\}`,
    picture: b('Dua matriks dan satu angka diuji. Matriks singular lolos; identitas gagal sifatnya; angka 5 gagal jenis objeknya.', 'Two matrices and a number are tested. A singular matrix passes; the identity fails the property; the number 5 fails the object type.'),
    steps: [s('Periksa semesta', 'Check the universe', 'X=M₂(R) berisi matriks 2×2 real. Angka 5 bukan anggota X; pengujian berhenti sebelum determinan.', 'X=M₂(R) consists of real 2×2 matrices. The number 5 is not in X; testing stops before the determinant.', String.raw`5\notin M_2(\mathbb R)`), s('Periksa sifat', 'Check the property', 'A=[[1,2],[2,4]] adalah matriks yang sesuai dan det A=4−4=0. Identitas I₂ sesuai jenisnya, tetapi det I₂=1.', 'A=[[1,2],[2,4]] has the right type and det A=4−4=0. The identity I₂ has the right type but determinant 1.', String.raw`\det\begin{pmatrix}1&2\\2&4\end{pmatrix}=0,\qquad\det I_2=1`), s('Tulis kesimpulan yang tepat', 'Write the correct conclusion', 'A∈H; I₂∉H; 5∉H. Untuk himpunan bijeksi T={f:S→S bijektif}, g∈T berarti g adalah fungsi bijektif, bukan angka g(s).', 'A∈H; I₂∉H; 5∉H. For T={f:S→S bijective}, g∈T means g is a bijective function, not the number g(s).', String.raw`A\in H,\quad I_2\notin H,\quad g\in T\implies g:S\to S\ \text{bijective}`)],
    conditions: [b('Pisahkan objek dari nilainya: fungsi f berbeda dari f(x), dan matriks A berbeda dari det A.', 'Separate an object from its value: f differs from f(x), and A differs from det A.')],
    failure: b('Dari a∈H hanya diperoleh a∈X dan P(a). Sifat P bukan “bentuk” a.', 'From a∈H you obtain only a∈X and P(a). A property P is not a “form” of a.'),
    examplePrompt: b('Untuk H={A∈M₂(R):det A=0}, apakah B=[[1,0],[0,0]] anggota?', 'For H={A∈M₂(R):det A=0}, does B=[[1,0],[0,0]] belong?'),
    exampleSteps: [s('Jenis dan sifat', 'Type and property', 'B adalah matriks 2×2 real; determinannya 1·0−0·0=0.', 'B is a real 2×2 matrix; its determinant is 1·0−0·0=0.', String.raw`B\in M_2(\mathbb R),\quad\det B=0`), s('Keanggotaan', 'Membership', 'Kedua syarat terpenuhi, sehingga B∈H. Ini belum membuktikan H suatu grup atau subgrup; aksioma harus diuji tersendiri.', 'Both conditions hold, hence B∈H. This does not prove H is a group or subgroup; the axioms require separate checks.', String.raw`B\in H`)],
    check: { question: b('Apakah matriks singular dalam H dapat menjadi grup terhadap perkalian matriks?', 'Can the singular matrices in H form a group under matrix multiplication?'), answer: b('Tidak. Matriks singular tidak mempunyai invers matriks; bahkan identitas I₂ tidak ada di H.', 'No. Singular matrices have no matrix inverses; even I₂ is absent from H.') },
  }),
  setEquality: topic({
    visual: 'setEquality', title: b('Kesamaan himpunan dan hukum De Morgan (Bab 1)', 'Set equality and De Morgan laws (Chapter 1)'),
    question: b('Bagaimana membuktikan A=B tanpa menebak anggotanya?', 'How do we prove A=B without guessing its members?'),
    meaning: b('Buktikan dua inklusi dengan mengambil unsur sembarang. Gabungan memakai “atau”, irisan memakai “dan”, dan komplemen memakai “tidak”. Hukum De Morgan mengikuti aturan negasi ini.', 'Prove two inclusions using an arbitrary element. Union uses “or”, intersection uses “and”, and complement uses “not”. De Morgan laws follow these negation rules.'),
    tex: String.raw`A=B\iff A\subseteq B\land B\subseteq A,\quad(A\cup B)^c=A^c\cap B^c,\quad(A\cap B)^c=A^c\cup B^c`,
    picture: b('Dua baris menguji unsur semesta yang sama. Titik 5 dan 6 berada di luar A∪B dan sekaligus di dalam Aᶜ∩Bᶜ.', 'Two rows test the same universe. Points 5 and 6 lie outside A∪B and also inside Aᶜ∩Bᶜ.'),
    steps: [s('Mulai dari ruas kiri', 'Start on the left', 'Ambil x∈(A∪B)ᶜ. Artinya x ada dalam U dan tidak ada di A maupun B.', 'Take x∈(A∪B)ᶜ. Then x is in U and in neither A nor B.', String.raw`x\notin A\cup B\iff x\notin A\land x\notin B`), s('Masuk ke ruas kanan', 'Reach the right', 'Karena x∉A dan x∉B, x∈Aᶜ dan x∈Bᶜ. Jadi x∈Aᶜ∩Bᶜ; inklusi pertama terbukti.', 'Since x∉A and x∉B, x belongs to both complements, hence to their intersection. This proves the first inclusion.', String.raw`(A\cup B)^c\subseteq A^c\cap B^c`), s('Balikkan arah', 'Reverse the direction', 'Mulai dengan x∈Aᶜ∩Bᶜ dan balikkan setiap alasan: x∉A dan x∉B, maka x∉A∪B. Dua inklusi memberi kesamaan.', 'Start with x∈Aᶜ∩Bᶜ and reverse the reasoning: x lies in neither A nor B, so not in their union. Two inclusions give equality.', String.raw`A^c\cap B^c\subseteq(A\cup B)^c`)],
    conditions: [b('Semua komplemen harus relatif terhadap semesta U yang sama.', 'All complements must use the same universe U.')],
    failure: b('Beberapa contoh yang cocok tidak membuktikan kesamaan. Satu contoh pembeda cukup untuk membuktikan ketidaksamaan.', 'Several matching examples do not prove equality. One distinguishing example suffices to disprove it.'),
    examplePrompt: b('Buktikan {n∈Z:n² genap}=2Z.', 'Prove {n∈Z:n² is even}=2Z.'),
    exampleSteps: [s('Inklusi pertama', 'First inclusion', 'Jika n² genap, n tidak mungkin ganjil: n=2k+1 memberi n²=2(2k²+2k)+1 ganjil. Jadi n=2k untuk suatu k.', 'If n² is even, n cannot be odd: n=2k+1 gives the odd square 2(2k²+2k)+1. Thus n=2k for some k.', String.raw`n^2\ \text{even}\implies n\in2\mathbb Z`), s('Inklusi sebaliknya', 'Reverse inclusion', 'Jika n=2k, maka n²=4k² genap. Kini kedua inklusi terbukti; k diperkenalkan setelah ada alasan bahwa n genap.', 'If n=2k, then n²=4k² is even. Both inclusions hold; introduce k only after establishing that n is even.', String.raw`n\in2\mathbb Z\implies n^2\ \text{even},\quad I=2\mathbb Z`)],
    check: { question: b('Lengkapi negasi “x∈A dan x∈B”.', 'Negate “x∈A and x∈B”.'), answer: b('x∉A atau x∉B. Karena itu (A∩B)ᶜ=Aᶜ∪Bᶜ.', 'x∉A or x∉B. Therefore (A∩B)ᶜ=Aᶜ∪Bᶜ.') },
  }),
  equivalence: topic({
    visual: 'equivalence', title: b('Relasi ekuivalen, kelas, dan partisi (2.4)', 'Equivalence relations, classes, and partitions (2.4)'),
    question: b('Mengapa kelas ekuivalen tidak saling tumpang tindih?', 'Why do equivalence classes never partially overlap?'),
    meaning: b('Relasi ekuivalen bersifat refleksif, simetris, dan transitif. Kelas [a] mengumpulkan semua objek yang ekuivalen dengan a. Kelas-kelas tersebut mempartisi semesta: setiap objek masuk tepat satu kelas.', 'An equivalence relation is reflexive, symmetric, and transitive. The class [a] collects objects equivalent to a. Its classes partition the universe: each object lies in exactly one class.'),
    tex: String.raw`[a]=\{x:x\sim a\},\quad[a]\cap[b]\ne\varnothing\implies[a]=[b]`,
    picture: b('Bilangan dikelompokkan menurut sisa modulo 3. Kotak berisi kelas, bukan hanya wakil 0, 1, dan 2.', 'Integers are grouped by remainder modulo 3. The boxes contain classes, not just representatives 0, 1, and 2.'),
    steps: [s('Uji tiga syarat', 'Test three conditions', 'Untuk a∼b iff 3 membagi a−b: a−a=0, b−a=−(a−b), dan a−c=(a−b)+(b−c). Ketiganya menjaga kelipatan 3.', 'For a∼b iff 3 divides a−b: a−a=0, b−a=−(a−b), and a−c=(a−b)+(b−c). All preserve multiples of 3.', String.raw`a\sim a,\quad a\sim b\Rightarrow b\sim a,\quad a\sim b\land b\sim c\Rightarrow a\sim c`), s('Bangun kelas', 'Build the classes', 'Bilangan dengan sisa sama berada dalam kelas yang sama. Contoh [1]=1+3Z memuat ...,−2,1,4,7,...; angka 1 hanyalah wakil.', 'Integers with the same remainder share a class. For example [1]=1+3Z contains ...,−2,1,4,7,...; 1 is only a representative.', String.raw`\mathbb Z=[0]\sqcup[1]\sqcup[2]\quad(\text{mod }3)`), s('Buktikan kelas sama atau lepas', 'Prove equality or disjointness', 'Jika x ada di [a] dan [b], simetri dan transitivitas memberi a∼b. Untuk y∈[a], y∼a∼b, jadi y∈[b]; arah sebaliknya serupa.', 'If x lies in both classes, symmetry and transitivity give a∼b. For y∈[a], y∼a∼b, hence y∈[b]; reverse the argument for the other inclusion.', String.raw`[a]=[b]\quad\text{or}\quad[a]\cap[b]=\varnothing`)],
    conditions: [b('Ketiga sifat wajib diuji. Koset kanan Ha memakai a∼b iff ab⁻¹∈H; koset kiri mempunyai rumus berbeda.', 'Check all three properties. Right cosets Ha use a∼b iff ab⁻¹∈H; left cosets use a different formula.')],
    failure: b('Relasi “a<b” bukan ekuivalen: tidak refleksif dan tidak simetris. Kelas hanya mempartisi himpunan jika relasinya ekuivalen.', 'The relation a<b is not an equivalence: it is neither reflexive nor symmetric. Classes form a partition only for an equivalence relation.'),
    examplePrompt: b('Tentukan [4] dan [−2] modulo 3.', 'Find [4] and [−2] modulo 3.'),
    exampleSteps: [s('Bandingkan selisih', 'Compare the difference', '4−(−2)=6 habis dibagi 3, sehingga 4∼−2.', '4−(−2)=6 is divisible by 3, so 4∼−2.', String.raw`4-(-2)=6\in3\mathbb Z`), s('Identifikasi kelas', 'Identify the class', 'Keduanya mempunyai sisa 1. Karena itu [4]=[−2]=[1], bukan dua kelas berbeda.', 'Both have remainder 1, hence [4]=[−2]=[1], not two different classes.', String.raw`[4]=[-2]=1+3\mathbb Z`)],
    check: { question: b('Di C, apakah z∼w iff |z|=|w| ekuivalen? Bagaimana kelasnya?', 'On C, is z∼w iff |z|=|w| an equivalence? What are its classes?'), answer: b('Ya, kesamaan modulus memenuhi ketiga sifat. Untuk radius r>0 kelasnya lingkaran |z|=r; kelas nol hanya {0}.', 'Yes: modulus equality satisfies all three conditions. For r>0 a class is the circle |z|=r; the zero class is {0}.') },
  }),
  firstIso: topic({
    visual: 'firstIso', title: b('Teorema Homomorfisme I: bukti dan pemakaian (2.7)', 'First homomorphism theorem: proof and use (2.7)'),
    question: b('Bagaimana membuktikan G/ker φ≅φ(G)?', 'How do we prove G/ker φ≅φ(G)?'),
    meaning: b('Kernel berisi unsur yang menjadi identitas. Dua unsur punya image sama tepat ketika berada dalam koset kernel yang sama. Jadi satu koset dapat diganti dengan satu nilai image tanpa kehilangan struktur grup.', 'The kernel contains elements sent to the identity. Two elements share an image exactly when they share a kernel coset. Thus each coset can be replaced by its image value while preserving the group structure.'),
    tex: String.raw`K=\ker\varphi,\qquad\mu:G/K\to\varphi(G),\quad Ka\mapsto\varphi(a),\qquad G/K\cong\varphi(G)`,
    picture: b('Z₁₂ dipetakan ke Z₃. Empat anggota dalam tiap baris mempunyai image sama; setiap baris menjadi satu anggota grup kuosien.', 'Z₁₂ maps to Z₃. The four members in each row share an image; each row becomes one quotient element.'),
    steps: [s('Terdefinisi dengan baik', 'Well defined', 'Jika Ka=Kb, maka ab⁻¹∈K, sehingga φ(a)φ(b)⁻¹=e′. Jadi φ(a)=φ(b): memilih wakil koset lain tidak mengubah µ.', 'If Ka=Kb then ab⁻¹∈K, so φ(a)φ(b)⁻¹=e′. Hence φ(a)=φ(b): choosing another representative leaves µ unchanged.', String.raw`Ka=Kb\implies\varphi(a)=\varphi(b)`), s('Homomorfisme', 'Homomorphism', 'Operasi koset dan sifat φ memberi µ((Ka)(Kb))=µ(Kab)=φ(ab)=φ(a)φ(b).', 'Coset multiplication and the property of φ give µ((Ka)(Kb))=µ(Kab)=φ(ab)=φ(a)φ(b).', String.raw`\mu((Ka)(Kb))=\mu(Ka)\mu(Kb)`), s('Injektif', 'Injective', 'Jika µ(Ka)=µ(Kb), maka φ(ab⁻¹)=e′, jadi ab⁻¹∈K dan Ka=Kb.', 'If µ(Ka)=µ(Kb), then φ(ab⁻¹)=e′, hence ab⁻¹∈K and Ka=Kb.', String.raw`\mu(Ka)=\mu(Kb)\implies Ka=Kb`), s('Surjektif ke image', 'Onto the image', 'Setiap y∈φ(G) berbentuk φ(a), sehingga y=µ(Ka). Ke seluruh target G′, langkah ini memerlukan φ onto.', 'Every y∈φ(G) has form φ(a), hence equals µ(Ka). Reaching the entire target G′ requires φ to be onto.', String.raw`G/\ker\varphi\cong\varphi(G),\quad\varphi\ \text{onto }G'\Rightarrow G/\ker\varphi\cong G'`)],
    conditions: [b('φ harus homomorfisme; K normal otomatis karena merupakan kernel. Bandingkan struktur lewat peta bijektif, bukan hanya ukuran.', 'φ must be a homomorphism; K is automatically normal as a kernel. Compare structure using a bijective map, not just cardinality.')],
    failure: b('G/ker φ≅G′ tidak otomatis jika φ tidak onto. Contoh φ:Z→Z×Z, n↦(n,0), mempunyai image Z×{0}, bukan seluruh target.', 'G/ker φ≅G′ does not follow automatically without surjectivity. For φ:Z→Z×Z, n↦(n,0), the image is Z×{0}, not the whole target.'),
    examplePrompt: b('Gunakan φ:Z→Z₈, φ(n)=[n]₈.', 'Use φ:Z→Z₈, φ(n)=[n]₈.'),
    exampleSteps: [s('Homomorfisme dan onto', 'Homomorphism and onto', 'Reduksi menjaga penjumlahan. Setiap kelas mempunyai wakil bilangan bulat, jadi φ onto.', 'Reduction preserves addition. Every class has an integer representative, so φ is onto.', String.raw`\varphi(a+b)=[a+b]_8=[a]_8+[b]_8`), s('Kernel lalu kuosien', 'Kernel then quotient', 'Yang dipetakan ke [0] adalah tepat kelipatan 8. Teorema memberi Z/8Z≅Z₈ melalui 8Z+n↦[n]₈.', 'Exactly the multiples of 8 map to [0]. The theorem gives Z/8Z≅Z₈ by 8Z+n↦[n]₈.', String.raw`\ker\varphi=8\mathbb Z,\qquad\mathbb Z/8\mathbb Z\cong\mathbb Z_8`)],
    check: { question: b('Untuk θ↦eⁱᶿ dari (R,+) ke lingkaran satuan, apa kernelnya?', 'For θ↦eⁱᶿ from (R,+) to the unit circle, what is the kernel?'), answer: b('2πZ. Peta onto dan menjaga operasi, jadi R/(2πZ)≅U(1). Sudut yang berbeda 2πk menjadi titik yang sama.', '2πZ. The map is onto and preserves operations, so R/(2πZ)≅U(1). Angles differing by 2πk become the same point.') },
  }),
  correspondence: topic({
    visual: 'correspondence', title: b('Teorema Korespondensi: naik dan turun (2.7)', 'Correspondence theorem: lifting and projecting (2.7)'),
    question: b('Subgrup mana yang masih dapat dibedakan setelah mengambil kuosien?', 'Which subgroups remain distinguishable after quotienting?'),
    meaning: b('Untuk φ:G→G′ onto dengan kernel K, subgrup G′ cocok satu-satu dengan subgrup H≤G yang memuat K. Turun lewat image φ(H); naik lewat preimage φ⁻¹(H′).', 'For an onto φ:G→G′ with kernel K, subgroups of G′ correspond bijectively to subgroups H≤G containing K. Project using φ(H); lift using φ⁻¹(H′).'),
    tex: String.raw`K\subseteq H\le G\longleftrightarrow H'\le G',\quad H'=\varphi(H),\quad H=\varphi^{-1}(H'),\quad H/K\cong H'`,
    picture: b('Setiap dZ yang memuat 12Z di kiri dipasangkan dengan subgrup yang dibangkitkan [d] di Z₁₂.', 'Each dZ containing 12Z on the left is paired with the subgroup generated by [d] in Z₁₂.'),
    steps: [s('Ambil seluruh preimage', 'Take the full preimage', 'Untuk H′≤G′, H=φ⁻¹(H′) memuat e dan tertutup terhadap ab⁻¹ karena φ(ab⁻¹)=φ(a)φ(b)⁻¹∈H′.', 'For H′≤G′, H=φ⁻¹(H′) contains e and is closed under ab⁻¹ because φ(ab⁻¹)=φ(a)φ(b)⁻¹∈H′.', String.raw`H=\varphi^{-1}(H')\le G`), s('Kernel wajib termuat', 'The kernel must be included', 'Semua k∈K mempunyai image e′∈H′. Pembatasan φ|H onto H′ dengan kernel K; Homomorfisme I memberi H/K≅H′.', 'Each k∈K maps to e′∈H′. The restriction φ|H is onto H′ with kernel K; the first theorem gives H/K≅H′.', String.raw`K\subseteq H,\qquad H/K\cong H'`), s('Buktikan kedua arah membatalkan', 'Prove the directions undo each other', 'φ⁻¹(φ(H))=HK; jika K⊆H, hasilnya H. Onto memberi φ(φ⁻¹(H′))=H′. Normalitas juga bersesuaian karena konjugasi dijaga φ.', 'φ⁻¹(φ(H))=HK; for K⊆H this is H. Surjectivity gives φ(φ⁻¹(H′))=H′. Normality also corresponds because φ preserves conjugation.', String.raw`\varphi^{-1}(\varphi(H))=H,\quad\varphi(\varphi^{-1}(H'))=H',\quad H\triangleleft G\iff H'\triangleleft G'`)],
    conditions: [b('φ onto; H harus memuat seluruh K. Preimage mengambil semua wakil, bukan satu wakil tiap koset.', 'φ is onto; H must contain all of K. The preimage takes all representatives, not one per coset.')],
    failure: b('Subgrup tanpa K tetap mempunyai image, tetapi proses naik lagi menghasilkan HK, yang dapat lebih besar daripada H.', 'A subgroup missing K still has an image, but lifting back gives HK, which may be larger than H.'),
    examplePrompt: b('Daftar subgrup Z₁₂ melalui Z→Z₁₂.', 'List the subgroups of Z₁₂ using Z→Z₁₂.'),
    exampleSteps: [s('Periksa inklusi di Z', 'Check containment in Z', 'Kernel adalah 12Z. Subgrup dZ memuat 12Z tepat ketika d membagi 12.', 'The kernel is 12Z. A subgroup dZ contains 12Z exactly when d divides 12.', String.raw`d\mid12:\quad d=1,2,3,4,6,12`), s('Proyeksikan', 'Project', 'Image dZ dibangkitkan [d] dan berorde 12/d. Untuk d=4 diperoleh {0,4,8}; untuk d=12 diperoleh {0}.', 'The image of dZ is generated by [d] and has order 12/d. d=4 gives {0,4,8}; d=12 gives {0}.', String.raw`4\mathbb Z/12\mathbb Z\cong\{[0],[4],[8]\}\le\mathbb Z_{12}`)],
    check: { question: b('Apakah 5Z memuat 12Z?', 'Does 5Z contain 12Z?'), answer: b('Tidak: 12 bukan kelipatan 5. Image 5Z di Z₁₂ adalah seluruh Z₁₂; preimage-nya kembali Z, bukan 5Z.', 'No: 12 is not a multiple of 5. The image of 5Z in Z₁₂ is all of Z₁₂; its preimage is Z rather than 5Z.') },
  }),
  secondIso: topic({
    visual: 'secondIso', title: b('Teorema Homomorfisme II: gabungan dan irisan (2.7)', 'Second homomorphism theorem: product and intersection (2.7)'),
    question: b('Mengapa HN/N≅H/(H∩N)?', 'Why is HN/N≅H/(H∩N)?'),
    meaning: b('Jika N dianggap identitas, unsur N dalam H ikut hilang. Informasi H yang tersisa sama dengan informasi HN setelah N dihilangkan. Dalam grup aditif, HN ditulis H+N.', 'When N becomes the identity, the part of N already inside H also disappears. The remaining information in H equals that in HN after removing N. In additive groups HN is written H+N.'),
    tex: String.raw`H\le G,\quad N\triangleleft G\implies HN/N\cong H/(H\cap N)`,
    picture: b('Untuk H=6Z dan N=4Z, gabungannya 2Z dan irisannya 12Z. Kedua kuosien di gambar mempunyai dua kelas.', 'For H=6Z and N=4Z, the sum is 2Z and the intersection 12Z. Both depicted quotients have two classes.'),
    steps: [s('Pastikan objeknya sah', 'Ensure valid objects', 'Normalitas N membuat HN=NH suatu subgrup. Irisan H∩N normal dalam H: konjugasi oleh h∈H menjaga H dan N.', 'Normality makes HN=NH a subgroup. H∩N is normal in H because conjugation by h∈H preserves both H and N.', String.raw`HN\le G,\qquad H\cap N\triangleleft H`), s('Bangun homomorfisme', 'Construct a homomorphism', 'Petakan h∈H ke Nh dalam HN/N. Setiap kelas N(hn) sama dengan Nh karena N normal; jadi peta onto.', 'Map h∈H to Nh in HN/N. Each class N(hn) equals Nh since N is normal, so the map is onto.', String.raw`\psi:H\twoheadrightarrow HN/N,\qquad\psi(h)=Nh`), s('Temukan kernel dan terapkan I', 'Find the kernel and apply I', 'ψ(h)=N tepat jika h∈N. Karena h sudah di H, kernel adalah H∩N. Homomorfisme I memberi hasilnya.', 'ψ(h)=N exactly when h∈N. Since h is already in H, the kernel is H∩N. Apply the first theorem.', String.raw`\ker\psi=H\cap N,\qquad H/(H\cap N)\cong HN/N`)],
    conditions: [b('H subgrup dan N normal di G. H tidak perlu normal di G.', 'H is a subgroup and N is normal in G. H need not be normal in G.')],
    failure: b('HN bukan gabungan himpunan H∪N. Ia berisi hasil kali hn; untuk grup aditif berisi semua h+n.', 'HN is not the set union H∪N. It contains products hn; in additive groups all sums h+n.'),
    examplePrompt: b('Ambil H=6Z dan N=4Z di (Z,+).', 'Take H=6Z and N=4Z in (Z,+).'),
    exampleSteps: [s('Hitung dua himpunan', 'Compute the two sets', 'Semua jumlah 6a+4b membentuk 2Z, karena gcd(6,4)=2. Kelipatan bersama membentuk lcm(6,4)Z=12Z.', 'All sums 6a+4b form 2Z because gcd(6,4)=2. Common multiples form lcm(6,4)Z=12Z.', String.raw`H+N=2\mathbb Z,\qquad H\cap N=12\mathbb Z`), s('Bandingkan struktur', 'Compare structure', '2Z/4Z mempunyai kelas [0] dan [2]; 6Z/12Z mempunyai [0] dan [6]. Peta [h]₁₂↦[h]₄ menghubungkan keduanya dan menjaga penjumlahan.', '2Z/4Z has classes [0] and [2]; 6Z/12Z has [0] and [6]. The map [h]₁₂↦[h]₄ pairs them and preserves addition.', String.raw`2\mathbb Z/4\mathbb Z\cong6\mathbb Z/12\mathbb Z\cong\mathbb Z_2`)],
    check: { question: b('Untuk H=8Z, N=12Z, berapa orde kedua kuosien?', 'For H=8Z and N=12Z, what are the orders of the two quotients?'), answer: b('H+N=4Z, H∩N=24Z. Jadi |4Z/12Z|=3 dan |8Z/24Z|=3; peta alami memberi isomorfisma.', 'H+N=4Z and H∩N=24Z. Thus |4Z/12Z|=3 and |8Z/24Z|=3; the natural map gives the isomorphism.') },
  }),
  thirdIso: topic({
    visual: 'thirdIso', title: b('Teorema Homomorfisme III: kuosien dua tahap (2.7)', 'Third homomorphism theorem: quotienting twice (2.7)'),
    question: b('Kapan kuosien dua tahap sama dengan satu tahap?', 'When does a two-stage quotient equal a single stage?'),
    meaning: b('Jika K⊆N dan keduanya normal di G, pertama gabungkan berdasarkan K, lalu gabungkan kelas yang berasal dari N. Hasilnya sama dengan langsung mengambil G/N.', 'If K⊆N and both are normal in G, first merge by K, then merge the classes coming from N. The result equals taking G/N directly.'),
    tex: String.raw`K\subseteq N\triangleleft G,\ K\triangleleft G\implies (G/K)/(N/K)\cong G/N`,
    picture: b('Z/12Z mempunyai 12 kelas. Kelompokkan kelas yang berbeda sebesar 4: menjadi empat kotak, sama dengan Z/4Z.', 'Z/12Z has 12 classes. Group classes differing by 4 into four boxes, matching Z/4Z.'),
    steps: [s('Periksa arah inklusi', 'Check the inclusion direction', 'N/K hanya bermakna jika K⊆N. Di Z, 12Z⊆4Z karena setiap kelipatan 12 adalah kelipatan 4.', 'N/K requires K⊆N. In Z, 12Z⊆4Z because every multiple of 12 is a multiple of 4.', String.raw`K=12\mathbb Z\subseteq N=4\mathbb Z`), s('Bangun peta antar-kuosien', 'Construct the quotient map', 'Definisikan ψ(Ka)=Na. Jika Ka=Kb, ab⁻¹∈K⊆N, sehingga Na=Nb. Jadi peta terdefinisi baik dan onto.', 'Define ψ(Ka)=Na. If Ka=Kb then ab⁻¹∈K⊆N, hence Na=Nb. This makes the map well defined and onto.', String.raw`\psi:G/K\twoheadrightarrow G/N,\qquad Ka\mapsto Na`), s('Hitung kernel', 'Compute the kernel', 'Ka dipetakan ke N tepat ketika a∈N. Kernel ψ adalah kumpulan kelas Ka dengan a∈N, yaitu N/K.', 'Ka maps to N exactly when a∈N. The kernel consists of those classes Ka, namely N/K.', String.raw`\ker\psi=N/K`), s('Terapkan Homomorfisme I', 'Apply the first theorem', 'Membagi domain G/K oleh kernel N/K memberikan image G/N. Ini alasan matematis “pencoretan”, bukan aturan pecahan biasa.', 'Quotienting the domain G/K by its kernel N/K gives the image G/N. This justifies “cancellation”; it is not ordinary fraction arithmetic.', String.raw`(G/K)/(N/K)\cong G/N`)],
    conditions: [b('K dan N normal di G, dan K⊆N. Untuk subgrup bilangan bulat, inklusi berlawanan dengan besar pembangkitnya.', 'K and N are normal in G, with K⊆N. For integer subgroups, containment reverses the generator size.')],
    failure: b('6Z⊆18Z salah: 6 bukan kelipatan 18. Yang benar 18Z⊆6Z. Periksa inklusi sebelum menulis N/K.', '6Z⊆18Z is false: 6 is not a multiple of 18. The correct direction is 18Z⊆6Z. Check containment before writing N/K.'),
    examplePrompt: b('Ambil G=Z, K=12Z, N=4Z.', 'Take G=Z, K=12Z, N=4Z.'),
    exampleSteps: [s('Identifikasi kuosien pertama', 'Identify the first quotient', 'G/K≅Z₁₂ dan N/K={ [0],[4],[8] }, subgrup berorde 3.', 'G/K≅Z₁₂ and N/K={ [0],[4],[8] }, a subgroup of order 3.', String.raw`N/K=\{[0],[4],[8]\}\le\mathbb Z_{12}`), s('Kelompokkan tiga anggota per kelas', 'Group three elements per class', 'Kelas hasilnya {0,4,8}, {1,5,9}, {2,6,10}, {3,7,11}; operasi kelas adalah penjumlahan sisa modulo 4.', 'The resulting classes are {0,4,8}, {1,5,9}, {2,6,10}, {3,7,11}; their operation is addition of remainders modulo 4.', String.raw`(\mathbb Z/12\mathbb Z)/(4\mathbb Z/12\mathbb Z)\cong\mathbb Z/4\mathbb Z\cong\mathbb Z_4`)],
    check: { question: b('Dengan K=18Z dan N=6Z, berapa orde (Z/K)/(N/K)?', 'For K=18Z and N=6Z, what is the order of (Z/K)/(N/K)?'), answer: b('6. Kuosien pertama berorde 18, N/K berorde 3, lalu 18/3=6; hasilnya isomorfik dengan Z₆.', '6. The first quotient has order 18, N/K has order 3, and 18/3=6; the result is isomorphic to Z₆.') },
  }),
  symmetricFunctions: topic({
    visual: 'symmetricFunctions', title: b('Bijeksi dan polinomial simetris (3.1)', 'Bijections and symmetric polynomials (3.1)'),
    question: b('Apa yang diubah permutasi, dan apa yang tetap?', 'What does a permutation change, and what stays fixed?'),
    meaning: b('Permutasi adalah bijeksi suatu himpunan ke dirinya. Ia mengubah posisi label. Polinomial simetris tidak berubah ketika variabelnya dipermutasi dengan cara apa pun.', 'A permutation is a bijection from a set to itself. It changes label positions. A symmetric polynomial stays unchanged under every permutation of its variables.'),
    tex: String.raw`S_n=\{\sigma:\{1,\ldots,n\}\to\{1,\ldots,n\}\text{ bijective}\},\quad |S_n|=n!`,
    picture: b('Tiga nilai bertukar posisi. Jumlah tetap 7, tetapi ekspresi x₁²x₂ berubah: tidak setiap ekspresi simetris.', 'Three values exchange positions. Their sum stays 7, but x₁²x₂ changes: not every expression is symmetric.'),
    steps: [s('Bangun grup bijeksi', 'Build the bijection group', 'Komposisi dua bijeksi kembali bijeksi; identitas tidak memindahkan apa pun dan invers membatalkan pemetaan. Asosiativitas berasal dari komposisi fungsi.', 'Composing bijections gives a bijection; the identity moves nothing and an inverse undoes the map. Associativity comes from function composition.', String.raw`(\sigma\tau)(i)=\sigma(\tau(i))`), s('Hitung dan urutkan', 'Count and order', 'Ada n pilihan image pertama, n−1 pilihan berikutnya, hingga 1. Dalam στ, kerjakan τ dahulu. Untuk n≥3, dua permutasi dapat tidak komutatif.', 'There are n choices for the first image, n−1 for the next, down to 1. In στ apply τ first. For n≥3 permutations may fail to commute.', String.raw`|S_n|=n(n-1)\cdots1=n!,\quad(12)(23)\ne(23)(12)`), s('Uji invariansi', 'Test invariance', 'x₁+x₂+x₃ dan x₁x₂x₃ tetap sama untuk setiap urutan variabel. x₁²x₂ tidak: menukar x₁ dan x₂ sudah menghasilkan ekspresi berbeda.', 'x₁+x₂+x₃ and x₁x₂x₃ stay the same under every variable ordering. x₁²x₂ does not: swapping x₁ and x₂ already changes it.', String.raw`p(x_{\sigma(1)},\ldots,x_{\sigma(n)})=p(x_1,\ldots,x_n)\quad(\forall\sigma\in S_n)`)],
    conditions: [b('Komposisi dibaca kanan ke kiri, sesuai slide. Sifat simetris berarti untuk semua permutasi dan sebagai identitas polinomial.', 'Read composition right to left, following the slides. Symmetry means invariance under every permutation as a polynomial identity.')],
    failure: b('Satu percobaan numerik yang tidak berubah tidak membuktikan simetri. Satu percobaan yang berubah cukup untuk menyangkalnya.', 'One unchanged numerical trial does not prove symmetry. One changed trial disproves it.'),
    examplePrompt: b('Uji x₁²x₂ dengan (x₁,x₂)=(1,2), lalu tukar.', 'Test x₁²x₂ at (x₁,x₂)=(1,2), then swap.'),
    exampleSteps: [s('Nilai awal', 'Initial value', 'Substitusi memberi 1²·2=2.', 'Substitution gives 1²·2=2.', String.raw`p(1,2)=2`), s('Nilai sesudah tukar', 'After swapping', 'Substitusi terbalik memberi 2²·1=4. Karena 2≠4, polinomial tidak simetris.', 'The swapped values give 2²·1=4. Since 2≠4, the polynomial is not symmetric.', String.raw`p(2,1)=4\ne2=p(1,2)`)],
    check: { question: b('Apakah x₁x₂+x₁x₃+x₂x₃ simetris?', 'Is x₁x₂+x₁x₃+x₂x₃ symmetric?'), answer: b('Ya. Setiap permutasi hanya mengubah urutan tiga pasangan tak berurutan {1,2},{1,3},{2,3}; jumlahnya sama.', 'Yes. Each permutation only reorders the three unordered pairs {1,2},{1,3},{2,3}; the sum is unchanged.') },
  }),
  cycleConjugation: topic({
    visual: 'cycleConjugation', title: b('Konjugasi siklus sebagai penggantian label (3.2)', 'Cycle conjugation as relabeling (3.2)'),
    question: b('Apa yang dilakukan σ terhadap τ saat membentuk στσ⁻¹?', 'What does σ do to τ when forming στσ⁻¹?'),
    meaning: b('Konjugasi mengganti nama anggota siklus tanpa mengganti hubungan “berikutnya”. Karena panjang siklus tetap, orde dan tipe siklus juga tetap.', 'Conjugation renames cycle members without changing which member comes next. Cycle lengths stay fixed, preserving order and cycle type.'),
    tex: String.raw`\sigma(a_1\ a_2\ \cdots\ a_k)\sigma^{-1}=(\sigma(a_1)\ \sigma(a_2)\ \cdots\ \sigma(a_k))`,
    picture: b('Segitiga siklus 1→2→3→1 berubah menjadi 4→5→3→4. Panahnya tetap; labelnya diganti σ=(14)(25).', 'The cycle triangle 1→2→3→1 becomes 4→5→3→4. The arrows stay; labels change under σ=(14)(25).'),
    steps: [s('Mulai dari label baru', 'Start at the new label', 'Pilih σ(aᵢ). Faktor paling kanan σ⁻¹ mengembalikannya ke nama lama aᵢ.', 'Start at σ(aᵢ). The rightmost factor σ⁻¹ returns it to the old name aᵢ.', String.raw`\sigma^{-1}(\sigma(a_i))=a_i`), s('Lakukan gerakan lama', 'Apply the old move', 'Siklus τ membawa aᵢ ke aᵢ₊₁, dengan anggota terakhir kembali ke anggota pertama.', 'The cycle τ sends aᵢ to aᵢ₊₁, with the last member returning to the first.', String.raw`\tau(a_i)=a_{i+1}`), s('Kembalikan nama baru', 'Restore the new name', 'σ membawa hasil ke σ(aᵢ₊₁). Jadi pola panah sama, hanya semua nama diganti σ.', 'σ sends the result to σ(aᵢ₊₁). The arrow pattern is unchanged; all names are replaced by σ.', String.raw`(\sigma\tau\sigma^{-1})(\sigma(a_i))=\sigma(a_{i+1})`)],
    conditions: [b('σ suatu permutasi pada semesta yang sama; anggota di luar siklus tetap juga direlabel.', 'σ is a permutation of the same universe; fixed points outside the cycle are also relabeled.')],
    failure: b('στσ⁻¹ berbeda dari sekadar στ. σ⁻¹ mengembalikan nama lama sebelum τ bekerja.', 'στσ⁻¹ differs from στ. The σ⁻¹ first restores the old names before τ acts.'),
    examplePrompt: b('Hitung σ(123)σ⁻¹ untuk σ=(14)(25).', 'Compute σ(123)σ⁻¹ for σ=(14)(25).'),
    exampleSteps: [s('Petakan setiap label', 'Map each label', 'σ(1)=4, σ(2)=5, σ(3)=3.', 'σ(1)=4, σ(2)=5, σ(3)=3.', String.raw`(1,2,3)\mapsto(4,5,3)`), s('Bentuk siklus baru', 'Form the new cycle', 'Hasilnya (453). Cek 4: σ⁻¹ membawa 4→1, siklus membawa 1→2, lalu σ membawa 2→5.', 'The result is (453). Check 4: σ⁻¹ sends 4→1, the cycle sends 1→2, and σ sends 2→5.', String.raw`\sigma(123)\sigma^{-1}=(453),\quad o((453))=3`)],
    check: { question: b('Apakah konjugasi dapat mengubah siklus panjang 3 menjadi transposisi?', 'Can conjugation turn a 3-cycle into a transposition?'), answer: b('Tidak. Konjugasi mempertahankan panjang siklus dan orde; 3-cycle berorde 3, transposisi berorde 2.', 'No. Conjugation preserves cycle length and order; a 3-cycle has order 3, a transposition order 2.') },
  }),
  parityProof: topic({
    visual: 'parityProof', title: b('Mengapa paritas terdefinisi dengan baik? (3.3)', 'Why is parity well defined? (3.3)'),
    question: b('Jika dekomposisi transposisi tidak tunggal, mengapa genap/ganjil tetap?', 'If transposition decompositions are nonunique, why does even/odd stay fixed?'),
    meaning: b('Gunakan ekspresi pembeda Δ=∏ᵢ<ⱼ(xᵢ−xⱼ). Satu transposisi membalik tanda Δ. Jadi hasil permutasi menentukan tanda (−1)ʳ dan memaksa semua dekomposisi mempunyai paritas r yang sama.', 'Use the alternating expression Δ=∏ᵢ<ⱼ(xᵢ−xⱼ). Each transposition reverses its sign. A permutation therefore fixes the sign (−1)ʳ, forcing all decompositions to have the same parity.'),
    tex: String.raw`\Delta=\prod_{i<j}(x_i-x_j),\quad\sigma\Delta=(-1)^r\Delta,\quad\operatorname{sgn}(\sigma)=(-1)^r`,
    picture: b('Δ bernilai −2 pada (1,2,3). Satu pertukaran memberi +2; pertukaran yang sama dua kali mengembalikan −2. Angka ini mengilustrasikan bukti formal.', 'Δ is −2 at (1,2,3). One swap gives +2; applying that swap twice returns −2. These values illustrate the formal proof.'),
    steps: [s('Satu pertukaran mengubah tanda', 'One swap reverses the sign', 'Saat dua variabel ditukar, faktor selisih di antara keduanya berubah tanda; faktor lain dapat dipasangkan tanpa perubahan produk.', 'Swapping two variables reverses the difference between them; the other factors pair up without changing their product.', String.raw`\tau\Delta=-\Delta\quad(\tau\ \text{a transposition})`), s('Ulangi r kali', 'Repeat r times', 'Jika σ adalah hasil kali r transposisi, setiap faktor memberi −1. Jadi σΔ=(−1)ʳΔ.', 'If σ is a product of r transpositions, each contributes −1, giving σΔ=(−1)ʳΔ.', String.raw`\sigma=\tau_1\cdots\tau_r\implies\sigma\Delta=(-1)^r\Delta`), s('Bandingkan dua dekomposisi', 'Compare two decompositions', 'Jika σ juga mempunyai s transposisi, kedua ekspresi σΔ sama. Karena Δ polinomial bukan nol, (−1)ʳ=(−1)ˢ; r dan s mempunyai paritas sama.', 'If σ also has a decomposition of length s, both expressions for σΔ agree. Since Δ is a nonzero polynomial, (−1)ʳ=(−1)ˢ, so r and s have equal parity.', String.raw`(-1)^r\Delta=(-1)^s\Delta\implies r\equiv s\pmod2`), s('Bangun Aₙ', 'Build Aₙ', 'Tanda hasil kali adalah hasil kali tanda. Aₙ=ker(sgn) normal. Untuk n≥2, sebuah transposisi mempunyai tanda −1, sehingga indeks Aₙ adalah 2.', 'Product signs multiply. Aₙ=ker(sgn) is normal. For n≥2, a transposition has sign −1, so Aₙ has index 2.', String.raw`A_n=\ker(\operatorname{sgn})\triangleleft S_n,\qquad |A_n|=n!/2\quad(n\ge2)`)],
    conditions: [b('Δ diperlakukan sebagai polinomial formal atas R atau Q. Jika nilai xᵢ kebetulan sama, Δ numerik nol dan tidak dapat digunakan untuk membatalkan.', 'Treat Δ as a formal polynomial over R or Q. If numerical xᵢ values coincide, Δ evaluates to zero and cannot be canceled.')],
    failure: b('Panjang siklus genap memberi permutasi ganjil: siklus panjang k diuraikan menjadi k−1 transposisi.', 'An even cycle length gives an odd permutation: a length-k cycle uses k−1 transpositions.'),
    examplePrompt: b('Tentukan tanda σ=(123)(45).', 'Find the sign of σ=(123)(45).'),
    exampleSteps: [s('Hitung panjang minus satu', 'Count length minus one', '3-cycle memberi 2 transposisi; 2-cycle memberi 1. Jumlahnya 3.', 'The 3-cycle contributes 2 transpositions and the 2-cycle 1, totaling 3.', String.raw`r=(3-1)+(2-1)=3`), s('Ambil tandanya', 'Take its sign', 'Tandanya −1. Menambah dua transposisi identik membatalkan gerakan dan tetap mempertahankan paritas ganjil.', 'Its sign is −1. Adding two identical transpositions cancels their action and preserves odd parity.', String.raw`\operatorname{sgn}(\sigma)=(-1)^3=-1,\quad\sigma\notin A_5`)],
    check: { question: b('Berapa orde A₄? Apakah semua 3-cycle di dalamnya?', 'What is the order of A₄? Does it contain every 3-cycle?'), answer: b('12. |A₄|=4!/2; setiap 3-cycle adalah dua transposisi, jadi genap dan termasuk A₄.', '12. |A₄|=4!/2; each 3-cycle uses two transpositions, so is even and belongs to A₄.') },
  }),
  subringTest: topic({
    visual: 'subringTest', title: b('Uji subgelanggang dan konvensi satuan (4.1–4.2)', 'Subring test and identity convention (4.1–4.2)'),
    question: b('Bagaimana memeriksa subgelanggang tanpa mengulang semua aksioma?', 'How do we check a subring without repeating every axiom?'),
    meaning: b('S⊆R adalah subgelanggang jika bukan kosong dan tertutup terhadap a−b serta ab. Selisih memastikan struktur grup aditif; asosiativitas dan distributivitas diwarisi dari R.', 'S⊆R is a subring if nonempty and closed under a−b and ab. Differences ensure the additive group structure; associativity and distributivity are inherited from R.'),
    tex: String.raw`S\le R\iff S\ne\varnothing,\quad a,b\in S\Rightarrow a-b\in S\ \text{and}\ ab\in S`,
    picture: b('Ambil a=2 dan b=4 di 2Z. Selisih −2 dan produk 8 tetap bilangan genap; 1 tidak berada di subgelanggang ini.', 'Take a=2 and b=4 in 2Z. The difference −2 and product 8 remain even; 1 is absent from this subring.'),
    steps: [s('Temukan nol dan negatif', 'Find zero and negatives', 'Pilih a∈S. Closure selisih memberi 0=a−a∈S dan −a=0−a∈S; lalu a+b=a−(−b)∈S.', 'Choose a∈S. Difference closure gives 0=a−a∈S and −a=0−a∈S; then a+b=a−(−b)∈S.', String.raw`0\in S,\quad -a\in S,\quad a+b\in S`), s('Uji perkalian internal', 'Test internal multiplication', 'Untuk a,b∈S, pastikan ab∈S. Asosiativitas dan dua hukum distributif otomatis benar karena operasi sama dengan R.', 'For a,b∈S, check ab∈S. Associativity and both distributive laws hold automatically because the operations come from R.', String.raw`a,b\in S\implies ab\in S`), s('Baca konvensi kuliah', 'Read the course convention', 'Slide dan Herstein tidak mewajibkan gelanggang memiliki 1. Karena itu 2Z adalah subgelanggang Z meskipun tidak mempunyai satuan perkalian.', 'The slides and Herstein do not require a multiplicative identity. Thus 2Z is a subring of Z despite having no multiplicative identity.', String.raw`2\mathbb Z\le\mathbb Z,\quad1\notin2\mathbb Z`)],
    conditions: [b('Gunakan konvensi slide. Buku yang mewajibkan subring mengandung 1R akan memberi definisi berbeda.', 'Use the slide convention. Books requiring a subring to contain 1R use a different definition.')],
    failure: b('Ideal perlu menyerap perkalian oleh semua r∈R. Uji subring hanya memakai dua anggota S; ini syarat yang lebih lemah.', 'An ideal must absorb multiplication by every r∈R. The subring test only uses two members of S, a weaker requirement.'),
    examplePrompt: b('Buktikan nZ subgelanggang Z.', 'Prove nZ is a subring of Z.'),
    exampleSteps: [s('Selisih', 'Difference', 'Nol termasuk. Jika a=nk dan b=nℓ, maka a−b=n(k−ℓ) ada dalam nZ.', 'Zero belongs. For a=nk and b=nℓ, a−b=n(k−ℓ) lies in nZ.', String.raw`nk-n\ell=n(k-\ell)\in n\mathbb Z`), s('Produk', 'Product', 'ab=n²kℓ=n(nkℓ) masih kelipatan n. Jadi kedua closure terpenuhi.', 'ab=n²kℓ=n(nkℓ) remains a multiple of n. Both closure conditions hold.', String.raw`(nk)(n\ell)=n(nk\ell)\in n\mathbb Z`)],
    check: { question: b('Z⊆Q adalah subring. Mengapa bukan ideal Q?', 'Z⊆Q is a subring. Why is it not an ideal of Q?'), answer: b('1∈Z tetapi (1/2)·1=1/2∉Z, padahal 1/2∈Q. Penyerapan oleh gelanggang asal gagal.', '1∈Z but (1/2)·1=1/2∉Z, with 1/2∈Q. Absorption by the ambient ring fails.') },
  }),
  booleanRing: topic({
    visual: 'booleanRing', title: b('Gelanggang Boole: a²=a (4.2)', 'Boolean rings: a²=a (4.2)'),
    question: b('Mengapa gelanggang Boole selalu komutatif?', 'Why is every Boolean ring commutative?'),
    meaning: b('Dalam gelanggang Boole, setiap a memenuhi a²=a. Contoh konkret: P(U) dengan penjumlahan beda simetris dan perkalian irisan. Dari aksioma ini dapat dibuktikan 2a=0 dan ab=ba.', 'In a Boolean ring every a satisfies a²=a. A concrete example is P(U), with symmetric difference as addition and intersection as multiplication. The axioms imply 2a=0 and ab=ba.'),
    tex: String.raw`a^2=a\ (\forall a)\implies a+a=0,\quad ab=ba;\qquad A+B=A\triangle B,\quad AB=A\cap B`,
    picture: b('Kotak menunjukkan empat subset {1,2}. Geser A; beda simetris menyisakan anggota yang hanya ada di satu himpunan, sedangkan irisan menyisakan anggota bersama.', 'The boxes show four subsets of {1,2}. Change A; symmetric difference retains members in exactly one set, while intersection retains shared members.'),
    steps: [s('Bangun contoh', 'Build the example', 'Beda simetris A△A kosong; irisan A∩A=A. Jadi nol adalah ∅, negatif A sama dengan A, dan semua anggota idempoten.', 'A△A is empty and A∩A=A. Thus zero is ∅, each A is its own negative, and every element is idempotent.', String.raw`A+A=\varnothing,\qquad A^2=A`), s('Buktikan 2a=0', 'Prove 2a=0', 'Terapkan idempotensi ke a+a: (a+a)²=a+a. Ekspansi memberi 4a²=2a; karena a²=a, 4a=2a. Kurangi 2a di grup aditif.', 'Apply idempotence to a+a: (a+a)²=a+a. Expansion gives 4a²=2a; since a²=a, 4a=2a. Subtract 2a in the additive group.', String.raw`4a=2a\implies2a=0`), s('Buktikan komutatif', 'Prove commutativity', 'Ekspansi (a+b)²=a+b memberi a+b+ab+ba=a+b, jadi ab+ba=0. Karena setiap c memenuhi −c=c, diperoleh ab=ba.', 'Expanding (a+b)²=a+b yields a+b+ab+ba=a+b, so ab+ba=0. Every c satisfies −c=c, hence ab=ba.', String.raw`ab+ba=0\implies ab=-ba=ba`)],
    conditions: [b('Idempotensi harus berlaku untuk semua anggota. Gelanggang Boole bukan nol mempunyai karakteristik 2.', 'Idempotence must hold for every element. A nonzero Boolean ring has characteristic 2.')],
    failure: b('Operasi + pada P(U) adalah beda simetris, bukan gabungan biasa. Gabungan tidak memberikan invers aditif.', 'Addition on P(U) is symmetric difference, not ordinary union. Union does not provide additive inverses.'),
    examplePrompt: b('Untuk A={1}, B={1,2}, hitung A+B dan AB.', 'For A={1}, B={1,2}, find A+B and AB.'),
    exampleSteps: [s('Anggota yang berbeda', 'Different members', '1 muncul di kedua himpunan sehingga terhapus dari beda simetris. 2 hanya di B sehingga tersisa.', '1 occurs in both sets and disappears from the symmetric difference. 2 occurs only in B and remains.', String.raw`A+B=\{2\}`), s('Anggota yang bersama', 'Shared members', 'Anggota bersama adalah 1, jadi AB={1}. Juga A²=A dan A+A=∅.', 'The shared member is 1, so AB={1}. Also A²=A and A+A=∅.', String.raw`AB=\{1\},\quad A^2=A,\quad A+A=\varnothing`)],
    check: { question: b('Apakah Z₄ gelanggang Boole? Apakah Z₂?', 'Is Z₄ Boolean? What about Z₂?'), answer: b('Z₄ tidak: 2²=0≠2. Z₂ ya: 0²=0 dan 1²=1.', 'Z₄ is not: 2²=0≠2. Z₂ is: 0²=0 and 1²=1.') },
  }),
  ringTheorems: topic({
    visual: 'ringTheorems', title: b('Empat teorema untuk gelanggang (4.3)', 'Four theorems for rings (4.3)'),
    question: b('Apa yang berubah ketika teorema grup dipakai pada gelanggang?', 'What changes when group theorems are applied to rings?'),
    meaning: b('Homomorfisme gelanggang harus menjaga + dan ×. Kernel adalah ideal dua sisi. Kuosien dan peta isomorfisma harus menjaga kedua operasi; ideal menggantikan subgrup normal.', 'A ring homomorphism must preserve + and ×. Its kernel is a two-sided ideal. Quotients and isomorphism maps must preserve both operations; ideals replace normal subgroups.'),
    tex: String.raw`R/\ker\varphi\cong\varphi(R),\quad (S+I)/I\cong S/(S\cap I),\quad (R/I)/(J/I)\cong R/J`,
    picture: b('Empat langkah memakai ideal bilangan bulat: kernel, korespondensi, subring+ideal, lalu kuosien dua tahap. Setiap panah harus menjaga penjumlahan dan perkalian.', 'Four frames use integer ideals: kernel, correspondence, subring plus ideal, then a two-stage quotient. Every arrow must preserve addition and multiplication.'),
    steps: [s('Homomorfisme I', 'First theorem', 'Peta [r]↦φ(r) terdefinisi baik karena selisih dua wakil berada dalam kernel. Selain penjumlahan, cek φ(rs)=φ(r)φ(s). Image adalah subring.', 'The map [r]↦φ(r) is well defined because representatives differ by an element of the kernel. Besides addition, check φ(rs)=φ(r)φ(s). The image is a subring.', String.raw`R/\ker\varphi\cong\varphi(R)`), s('Korespondensi ideal', 'Ideal correspondence', 'Untuk φ onto, ideal pada target berpasangan dengan ideal R yang memuat kernel, melalui image dan preimage. Inklusi ideal dipertahankan.', 'For onto φ, target ideals pair with ideals of R containing the kernel through image and preimage. Ideal inclusions are preserved.', String.raw`\ker\varphi\subseteq J\triangleleft R\longleftrightarrow J'\triangleleft R'`), s('Homomorfisme II', 'Second theorem', 'Untuk S subring R dan I ideal R, petakan s↦s+I. Image adalah (S+I)/I dan kernel S∩I, suatu ideal S. Terapkan I.', 'For a subring S and ideal I of R, map s↦s+I. The image is (S+I)/I and the kernel S∩I, an ideal of S. Apply the first theorem.', String.raw`(S+I)/I\cong S/(S\cap I)`), s('Homomorfisme III', 'Third theorem', 'Jika I⊆J ideal R, petakan r+I↦r+J. Kernel J/I dan onto R/J; kedua operasi dijaga. Terapkan I sekali lagi.', 'For ideals I⊆J of R, map r+I↦r+J. The kernel is J/I and the image all of R/J; both operations are preserved. Apply the first theorem again.', String.raw`(R/I)/(J/I)\cong R/J`)],
    conditions: [b('Ideal dua sisi diperlukan dalam gelanggang nonkomutatif. Kuliah tidak mewajibkan homomorfisme menjaga 1; jika onto antara gelanggang bersatuan, 1 otomatis dipetakan ke 1.', 'Two-sided ideals are required in noncommutative rings. The course does not require homomorphisms to preserve 1; an onto map between rings with identity automatically does so.')],
    failure: b('Determinannya homomorfisme grup GLₙ(R)→R*, tetapi bukan homomorfisme gelanggang matriks: det(A+B) umumnya bukan det A+det B.', 'The determinant is a group homomorphism GLₙ(R)→R*, but not a ring homomorphism of matrix rings: det(A+B) generally differs from det A+det B.'),
    examplePrompt: b('Terapkan II pada R=Z, S=2Z, I=3Z.', 'Apply II to R=Z, S=2Z, I=3Z.'),
    exampleSteps: [s('Sum dan irisan', 'Sum and intersection', '2Z+3Z=Z karena gcd=1; 2Z∩3Z=6Z. Jadi domain yang dibagi adalah S=2Z.', '2Z+3Z=Z since the gcd is 1, while 2Z∩3Z=6Z. The domain to quotient is S=2Z.', String.raw`(2\mathbb Z+3\mathbb Z)/3\mathbb Z\cong2\mathbb Z/6\mathbb Z`), s('Cek kedua operasi', 'Check both operations', 'Peta 2k+6Z↦[2k]₃ memberi tiga kelas dan menjaga jumlah serta produk. Maka 2Z/6Z≅Z₃ sebagai gelanggang; identitas kuosien di kiri adalah 4+6Z.', 'The map 2k+6Z↦[2k]₃ gives three classes and preserves sums and products. Thus 2Z/6Z≅Z₃ as rings; the quotient identity on the left is 4+6Z.', String.raw`2\mathbb Z/6\mathbb Z\cong\mathbb Z_3,\qquad[4]\mapsto[1]_3`)],
    check: { question: b('Untuk R=Z, I=6Z, J=3Z, identifikasi (R/I)/(J/I).', 'For R=Z, I=6Z, J=3Z, identify (R/I)/(J/I).'), answer: b('Z₃. J/I={ [0],[3] } dalam Z₆; kuosien mempunyai kelas {0,3},{1,4},{2,5}, dengan operasi modulo 3.', 'Z₃. J/I={ [0],[3] } inside Z₆; the quotient classes are {0,3},{1,4},{2,5}, with operations modulo 3.') },
  }),
  formalPolynomials: topic({
    visual: 'formalPolynomials', title: b('Polinomial formal, derajat, dan unit (4.5)', 'Formal polynomials, degree, and units (4.5)'),
    question: b('Bisakah dua polinomial berbeda memberi fungsi yang sama?', 'Can different polynomials define the same function?'),
    meaning: b('Polinomial formal adalah daftar koefisien hingga, dengan x sebagai tak-tentu. Kesamaan berarti setiap koefisien sama. Pada lapangan hingga, dua polinomial berbeda dapat mempunyai nilai sama di semua titik.', 'A formal polynomial is a finite coefficient list, with x an indeterminate. Equality means equality of every coefficient. Over a finite field, distinct polynomials may agree at every input.'),
    tex: String.raw`\sum a_ix^i=\sum b_ix^i\iff a_i=b_i\ (\forall i),\quad\deg(fg)=\deg f+\deg g\quad(f,g\ne0)`,
    picture: b('Di F₂, polinomial x²+x berbeda dari 0 pada koefisiennya, tetapi kedua tabel nilainya identik untuk input 0 dan 1.', 'Over F₂, x²+x differs from 0 in its coefficients, but their value tables agree at inputs 0 and 1.'),
    steps: [s('Bandingkan koefisien', 'Compare coefficients', '0 mempunyai semua koefisien nol. x²+x mempunyai koefisien x dan x² sebesar 1, jadi bukan polinomial nol.', 'Zero has every coefficient zero. x²+x has coefficients 1 at x and x², so it is not the zero polynomial.', String.raw`x^2+x\ne0\quad\text{in }\mathbb F_2[x]`), s('Bandingkan fungsi evaluasi', 'Compare evaluation functions', 'Di F₂ hanya ada input 0 dan 1. Keduanya memberi a²+a=0. Jadi fungsi evaluasinya nol meskipun polinomialnya bukan nol.', 'F₂ has only inputs 0 and 1. Both satisfy a²+a=0, so the evaluation function is zero although the polynomial is nonzero.', String.raw`f(0)=0,\qquad f(1)=1+1=0`), s('Gunakan suku utama', 'Use the leading term', 'Untuk f,g bukan nol atas lapangan, hasil kali koefisien utama tidak nol; derajat bertambah. Jika fg=1, kedua derajat harus 0, sehingga unit F[x] tepat konstanta tak nol.', 'For nonzero f,g over a field, their leading coefficients have nonzero product, so degrees add. If fg=1 both degrees must be 0; units of F[x] are exactly the nonzero constants.', String.raw`F[x]^\times=F\setminus\{0\}`)],
    conditions: [b('F lapangan untuk aturan derajat dan klasifikasi unit ini. Derajat polinomial nol tidak dipakai; pembagian memerlukan g≠0.', 'F is a field for this degree rule and unit classification. Do not use the zero polynomial’s degree; division requires g≠0.')],
    failure: b('Kesamaan sebagai fungsi bukan selalu kesamaan polinomial di lapangan hingga. “F[x] lapangan” juga salah: x tidak mempunyai invers polinomial.', 'Function equality need not mean polynomial equality over finite fields. F[x] is not a field either: x has no polynomial inverse.'),
    examplePrompt: b('Tentukan derajat f+g dan fg di F₅ untuk f=2x⁹+4x⁷, g=3x⁹+1.', 'Find the degrees of f+g and fg over F₅ for f=2x⁹+4x⁷, g=3x⁹+1.'),
    exampleSteps: [s('Penjumlahan dapat turun derajat', 'Addition may lower degree', 'Koefisien x⁹ adalah 2+3=0 di F₅. Maka f+g=4x⁷+1 berderajat 7.', 'The x⁹ coefficient is 2+3=0 in F₅. Thus f+g=4x⁷+1 has degree 7.', String.raw`\deg(f+g)=7<9`), s('Produk tidak kehilangan suku utama', 'The product keeps its leading term', 'Koefisien x¹⁸ adalah 2·3=1 modulo 5, bukan nol. Maka derajat fg=9+9=18.', 'The x¹⁸ coefficient is 2·3=1 modulo 5, not zero. Hence deg(fg)=9+9=18.', String.raw`\deg(fg)=18`)],
    check: { question: b('Apakah 2 dan x unit di Q[x]?', 'Are 2 and x units in Q[x]?'), answer: b('2 unit, dengan invers 1/2. x bukan unit: untuk g bukan nol, deg(xg)=1+deg g≥1, sehingga xg≠1.', '2 is a unit with inverse 1/2. x is not: for nonzero g, deg(xg)=1+deg g≥1, so xg≠1.') },
  }),
}

export const ALGEBRA_ORDER = [
  ['setMembership', 'setBuilder', 'abstractSets', 'setEquality'],
  ['0.0', '0.1', 'equivalence', '0.2', '0.3', '0.4', 'firstIso', 'correspondence', 'secondIso', 'thirdIso'],
  ['symmetricFunctions', '1.0', 'cycleConjugation', '1.1', 'parityProof'],
  ['2.0', 'subringTest', 'booleanRing', '2.1', 'ringTheorems', 'formalPolynomials', '2.2', '2.3'],
]
export function extendAlgebra<T>(base: T[][], additions: Record<string, T>): T[][] {
  return ALGEBRA_ORDER.map(part => part.map(key => {
    if (/^\d\.\d$/.test(key)) { const [p, e] = key.split('.').map(Number); return base[p][e] }
    return additions[key]
  }))
}
export const SLIDE_ENTRIES = Object.fromEntries(Object.entries(ALGEBRA_SLIDE_TOPICS).map(([k, t]) => [k, t.entry]))
export const SLIDE_LESSONS = Object.fromEntries(Object.entries(ALGEBRA_SLIDE_TOPICS).map(([k, t]) => [k, t.lesson]))
export const SLIDE_EXAMPLES = Object.fromEntries(Object.entries(ALGEBRA_SLIDE_TOPICS).map(([k, t]) => [k, t.example]))
export const SLIDE_DEFINITIONS = Object.fromEntries(Object.entries(ALGEBRA_SLIDE_TOPICS).map(([k, t]) => [k, t.definition])) as Record<AlgebraSlideKind, Definition>
export const SLIDE_CONCEPTS = Object.fromEntries(Object.keys(ALGEBRA_SLIDE_TOPICS).map(k => [k, [] as VisualTheorem[]])) as Record<AlgebraSlideKind, VisualTheorem[]>
