import type { Bilingual } from './summary-examples'
import type { VisualKind } from './summary-lessons'
const b = (id: string, en: string): Bilingual => ({ id, en })
export const ALGEBRA_DECKS: { file: string; title: Bilingual; topics: VisualKind[] }[] = [
  { file: 'bab1_tinjauan himpunan.pdf', title: b('Bab 1 · Tinjauan himpunan', 'Chapter 1 · Set foundations'), topics: ['setMembership', 'setBuilder', 'abstractSets', 'setEquality'] },
  { file: 'bab2_grup_definisi_dan_sifat_1.pdf', title: b('2.1–2.2 · Definisi grup dan sifat dasar', '2.1–2.2 · Groups and basic properties'), topics: ['group'] },
  { file: 'bab2t3_subgrup.pdf', title: b('2.3 · Subgrup, pusat, dan grup siklik', '2.3 · Subgroups, centers, and cyclic groups'), topics: ['cyclic'] },
  { file: 'bab2t4_teorema_lagrange.pdf', title: b('2.4 · Ekuivalensi, koset, dan Lagrange', '2.4 · Equivalence, cosets, and Lagrange'), topics: ['equivalence', 'cosets'] },
  { file: 'bab2t5_homomorfisme_grup.pdf', title: b('2.5 · Homomorfisme dan normalitas', '2.5 · Homomorphisms and normality'), topics: ['kernel'] },
  { file: 'bab2t6_grup_faktor.pdf', title: b('2.6 · Grup faktor', '2.6 · Quotient groups'), topics: ['quotient'] },
  { file: 'bab2t7_teorema_homomorfisme_preview.pdf', title: b('2.7 · Empat teorema homomorfisme', '2.7 · Four homomorphism theorems'), topics: ['firstIso', 'correspondence', 'secondIso', 'thirdIso'] },
  { file: 'bab3t1_grup_simetris.pdf', title: b('3.1 · Grup simetris', '3.1 · Symmetric groups'), topics: ['symmetricFunctions', 'cycles'] },
  { file: 'bab3t2_dekomposisi_siklus.pdf', title: b('3.2 · Dekomposisi dan konjugasi siklus', '3.2 · Cycle decomposition and conjugation'), topics: ['cycles', 'cycleConjugation', 'parity'] },
  { file: 'bab3t3_permutasi_genap_ganjil_PREVIEW.pdf', title: b('3.3 · Paritas dan Aₙ', '3.3 · Parity and Aₙ'), topics: ['parity', 'parityProof'] },
  { file: 'bab4_gelanggang.pdf', title: b('4.1–4.2 · Gelanggang, subring, dan Boole', '4.1–4.2 · Rings, subrings, and Boolean rings'), topics: ['ring', 'subringTest', 'booleanRing'] },
  { file: 'bab4t3_homomorfisme_gelanggang.pdf', title: b('4.3 · Homomorfisme, ideal, dan kuosien', '4.3 · Homomorphisms, ideals, and quotients'), topics: ['ideal', 'ringTheorems'] },
  { file: 'bab4t4_ideal_maksimal.pdf', title: b('4.4 · Ideal maksimal', '4.4 · Maximal ideals'), topics: ['ideal'] },
  { file: 'bab4t5_gelanggang_polinomial.pdf', title: b('4.5 · Gelanggang polinomial', '4.5 · Polynomial rings'), topics: ['formalPolynomials', 'division'] },
  { file: 'bab4t6_polinomial_rasional.pdf', title: b('4.6 · Polinomial rasional, Gauss, Eisenstein', '4.6 · Rational polynomials, Gauss, Eisenstein'), topics: ['eisenstein'] },
]
export type StudyExercise = { question: Bilingual; solution: Bilingual; tex: string }
const q = (id: string, en: string, answerId: string, answerEn: string, tex: string): StudyExercise => ({ question: b(id, en), solution: b(answerId, answerEn), tex })
/** Extra proof practice for the original textbook entries; new entries already have worked slide examples. */
export const ALGEBRA_PRACTICE: Partial<Record<VisualKind, StudyExercise[]>> = {
  group: [
    q('Buktikan komposisi Tₐ,ᵦ(x)=ax+b, a≠0, membentuk grup.', 'Prove Tₐ,ᵦ(x)=ax+b, a≠0, forms a group under composition.', 'Komposisi Tₐ,ᵦ∘T𝚌,𝚍=Tₐ𝚌,ₐ𝚍₊ᵦ tetap mempunyai koefisien utama tak nol. Identitas T₁,₀; invers T₁/ₐ,₋ᵦ/ₐ. Asosiativitas berasal dari komposisi fungsi.', 'Composition Tₐ,ᵦ∘T𝚌,𝚍=Tₐ𝚌,ₐ𝚍₊ᵦ retains a nonzero leading coefficient. The identity is T₁,₀; the inverse is T₁/ₐ,₋ᵦ/ₐ. Function composition is associative.', String.raw`T_{a,b}T_{c,d}=T_{ac,ad+b},\qquad T_{a,b}^{-1}=T_{1/a,-b/a}`),
    q('Dari ab=ac, di sisi mana invers a harus dikalikan?', 'From ab=ac, which side must be multiplied by a⁻¹?', 'Di kiri: a⁻¹(ab)=a⁻¹(ac). Asosiativitas lalu memberi eb=ec. Perkalian di kanan tidak membuat a dan a⁻¹ berdampingan.', 'On the left: a⁻¹(ab)=a⁻¹(ac). Associativity then gives eb=ec. Right multiplication does not put a next to a⁻¹.', String.raw`a^{-1}(ab)=a^{-1}(ac)\implies b=c`),
  ],
  cyclic: [
    q('Buktikan H={n∈Z:n² genap} subgrup (Z,+) langsung dari predikat.', 'Prove H={n∈Z:n² is even} is a subgroup of (Z,+) directly from the predicate.', '0∈H. Untuk m,n∈H, (m+n)²=m²+2mn+n² genap, jadi m+n∈H. Juga (−n)²=n² genap. Kita memakai sifat anggota, tanpa mengasumsikan m atau n sebuah kuadrat.', '0∈H. For m,n∈H, (m+n)²=m²+2mn+n² is even, so m+n∈H. Also (−n)²=n² is even. We use member properties without assuming m or n is a square.', String.raw`(m+n)^2=m^2+2mn+n^2,\qquad(-n)^2=n^2`),
    q('Untuk G abelian, buktikan H={a:a²=e} subgrup. Di mana asumsi abelian dipakai?', 'For abelian G, prove H={a:a²=e} is a subgroup. Where is commutativity used?', 'e∈H. Closure menggunakan (ab)²=a²b²=e karena ab=ba. Invers memenuhi (a⁻¹)²=(a²)⁻¹=e. Tanpa abelian, (12),(23) di S₃ memenuhi kuadrat=e tetapi produknya 3-cycle, sehingga closure dapat gagal.', 'e∈H. Closure uses (ab)²=a²b²=e because ab=ba. Also (a⁻¹)²=(a²)⁻¹=e. Without commutativity, (12),(23) in S₃ square to e but their product is a 3-cycle, so closure may fail.', String.raw`(ab)^2=e\quad(ab=ba),\qquad((12)(23))^2\ne e`),
  ],
  cosets: [
    q('Di Z₁₅, H={0,5,10}. Daftar koset dan tentukan indeksnya.', 'In Z₁₅ let H={0,5,10}. List the cosets and their index.', 'Koset H+r={r,r+5,r+10} untuk r=0,1,2,3,4. Kelimanya lepas dan menutupi 15 anggota; setiap koset berukuran 3, jadi indeks 5. Setiap r lain menghasilkan salah satu koset ini.', 'The cosets are H+r={r,r+5,r+10} for r=0,1,2,3,4. They are disjoint and cover all 15 elements; each has size 3, so the index is 5. Every other representative repeats one of them.', String.raw`[\mathbb Z_{15}:H]=15/3=5`),
    q('Mengapa operasi [a]+[b]=[a+b] pada Zₙ tidak bergantung wakil?', 'Why is [a]+[b]=[a+b] on Zₙ independent of representatives?', 'Jika a′=a+kn dan b′=b+ℓn, maka a′+b′=(a+b)+(k+ℓ)n. Selisih hasil adalah kelipatan n, sehingga kelasnya sama.', 'If a′=a+kn and b′=b+ℓn, then a′+b′=(a+b)+(k+ℓ)n. The difference is a multiple of n, so the result is the same class.', String.raw`[a']=[a],\ [b']=[b]\implies[a'+b']=[a+b]`),
  ],
  kernel: [
    q('Jelaskan mengapa ln:(R⁺,×)→(R,+) adalah isomorfisma.', 'Explain why ln:(R⁺,×)→(R,+) is an isomorphism.', 'ln(xy)=ln x+ln y menjaga operasi; exp adalah invers fungsi, jadi bijektif. Kernel {1}, karena ln x=0 iff x=1. Identitas domain adalah 1, sedangkan identitas target 0.', 'ln(xy)=ln x+ln y preserves operations; exp is its inverse function, giving bijectivity. The kernel is {1}, since ln x=0 iff x=1. The domain identity is 1, the target identity 0.', String.raw`\ker(\ln)=\{1\},\qquad(\mathbb R^+,\times)\cong(\mathbb R,+)`),
    q('Tentukan image dan kernel det:GLₙ(R)→R*.', 'Find the image and kernel of det:GLₙ(R)→R*.', 'det(AB)=det A·det B. Untuk r≠0, diag(r,1,...,1) mempunyai determinan r, jadi onto. Kernel SLₙ(R), matriks dengan determinan 1, dan normal karena kernel.', 'det(AB)=det A·det B. For r≠0, diag(r,1,...,1) has determinant r, so the map is onto. Its kernel is SLₙ(R), the matrices with determinant 1, and is normal as a kernel.', String.raw`\operatorname{GL}_n(\mathbb R)/\operatorname{SL}_n(\mathbb R)\cong\mathbb R^*`),
  ],
  quotient: [
    q('Buktikan perkalian koset kanan Na·Nb=Nab terdefinisi dengan baik.', 'Prove right-coset multiplication Na·Nb=Nab is well defined.', 'Tuliskan a′=n₁a dan b′=n₂b. Maka a′b′=n₁(an₂a⁻¹)ab. Normalitas N membuat faktor sebelum ab berada di N; jadi Na′b′=Nab. Inilah tempat syarat normal dipakai.', 'Write a′=n₁a and b′=n₂b. Then a′b′=n₁(an₂a⁻¹)ab. Normality puts the factor before ab in N, so Na′b′=Nab. This is where normality is used.', String.raw`a'b'=n_1(an_2a^{-1})ab\in Nab`),
    q('Apa kernel proyeksi π:G→G/N? Apa identitas dan invers dalam G/N?', 'What is the kernel of π:G→G/N? What are the quotient identity and inverses?', 'π(a)=Na adalah homomorfisme onto. π(a)=N tepat ketika a∈N, jadi kernel N. Identitasnya koset N, bukan satu unsur e; invers Na adalah Na⁻¹.', 'π(a)=Na is an onto homomorphism. π(a)=N iff a∈N, so its kernel is N. The identity is the coset N, not the element e; the inverse of Na is Na⁻¹.', String.raw`\ker\pi=N,\quad e_{G/N}=N,\quad(Na)^{-1}=Na^{-1}`),
  ],
  cycles: [q('Hitung (12)(23), inversnya, dan ordenya.', 'Compute (12)(23), its inverse, and its order.', 'Kerjakan (23) dahulu: 1→2, 2→3, 3→1. Jadi (123); invers (132); orde 3. Produk terbalik adalah (132), sehingga urutan mengubah hasil.', 'Apply (23) first: 1→2, 2→3, 3→1. Thus the product is (123), its inverse (132), and its order 3. The reversed product is (132), so order matters.', String.raw`(12)(23)=(123),\quad((12)(23))^{-1}=(132)`)],
  parity: [q('Daftar jenis anggota A₄ dan cek |A₄|.', 'List the types of elements in A₄ and check its order.', 'Ada identitas, delapan 3-cycle, dan tiga produk dua transposisi lepas: (12)(34), (13)(24), (14)(23). Semuanya genap; jumlah 1+8+3=12=4!/2.', 'There are the identity, eight 3-cycles, and three products of disjoint transpositions: (12)(34), (13)(24), (14)(23). All are even; 1+8+3=12=4!/2.', String.raw`|A_4|=1+8+3=12`)],
  ring: [q('Buktikan daerah integral berhingga adalah lapangan.', 'Prove a finite integral domain is a field.', 'Untuk a≠0, peta x↦ax injektif karena kanselasi. Pada himpunan hingga, injektif berarti onto; jadi ada x dengan ax=1. Komutativitas memberi xa=1. Setiap anggota tak nol memiliki invers.', 'For a≠0, x↦ax is injective by cancellation. On a finite set, injective means onto, so some x satisfies ax=1. Commutativity gives xa=1. Every nonzero element has an inverse.', String.raw`ax=ay\implies x=y,\qquad\exists x:\ ax=1`)],
  ideal: [
    q('Mengapa perkalian pada R/I memerlukan penyerapan ideal?', 'Why does multiplication in R/I require ideal absorption?', 'Ganti wakil a,b oleh a+i,b+j. Selisih produknya aj+ib+ij ada di I karena I menyerap perkalian dari kedua sisi. Jadi kelas produk tidak berubah.', 'Replace representatives a,b by a+i,b+j. Their product difference aj+ib+ij belongs to I because it absorbs multiplication on both sides. The product class is unchanged.', String.raw`(a+i)(b+j)-ab=aj+ib+ij\in I`),
    q('Buktikan M maksimal iff R/M lapangan untuk R komutatif bersatuan.', 'Prove M maximal iff R/M is a field for a commutative ring with identity.', 'M harus ideal sejati. Jika a∉M dan M maksimal, ideal M+(a)=R; tulis 1=m+ra. Maka [r][a]=[1], sehingga semua kelas tak nol unit. Sebaliknya ideal antara M dan R bersesuaian dengan ideal lapangan R/M; lapangan hanya memiliki ideal 0 dan seluruh lapangan, jadi tidak ada ideal di antaranya.', 'M must be proper. If a∉M and M is maximal, M+(a)=R; write 1=m+ra. Then [r][a]=[1], so every nonzero class is a unit. Conversely, intermediate ideals correspond to ideals of the field R/M, which has only zero and the whole field, so there is no intermediate ideal.', String.raw`a\notin M\Rightarrow1=m+ra\Rightarrow[r][a]=[1]`),
    q('Mengapa (3) maksimal di Z[i], tetapi (5) tidak?', 'Why is (3) maximal in Z[i], whereas (5) is not?', 'Modulo 3 ada sembilan kelas a+bi. Untuk kelas tak nol, a²+b²≠0 di F₃ karena kuadrat hanya 0 atau 1; invers adalah (a−bi)/(a²+b²). Jadi kuosien lapangan. Modulo 5, (2+i)(2−i)=0, dengan kedua faktor tak nol: ada pembagi nol, sehingga bukan lapangan.', 'Modulo 3 there are nine classes a+bi. For a nonzero class, a²+b²≠0 in F₃ since squares are only 0 or 1; the inverse is (a−bi)/(a²+b²). Thus the quotient is a field. Modulo 5, (2+i)(2−i)=0 with both factors nonzero, giving zero divisors rather than a field.', String.raw`(1+i)(2+i)=1\pmod3,\qquad(2+i)(2-i)=5`),
  ],
  division: [
    q('Hitung gcd(x³+1,x²−1) dan identitas Bézout di Q[x].', 'Find gcd(x³+1,x²−1) and a Bézout identity in Q[x].', 'Pembagian pertama memberi x³+1=x(x²−1)+(x+1). Berikutnya x²−1=(x−1)(x+1), dengan sisa nol. Gcd monik adalah x+1; substitusi balik memberi x+1=(x³+1)−x(x²−1).', 'First divide: x³+1=x(x²−1)+(x+1). Then x²−1=(x−1)(x+1), with zero remainder. The monic gcd is x+1; back substitution gives x+1=(x³+1)−x(x²−1).', String.raw`\gcd(f,g)=x+1=f-xg`),
    q('Mengapa setiap ideal tak nol F[x] utama, dan kapan (p) maksimal?', 'Why is every nonzero ideal of F[x] principal, and when is (p) maximal?', 'Pilih g∈I bukan nol berderajat minimum. Untuk f∈I, pembagian f=qg+r memberi r∈I dengan derajat lebih kecil jika bukan nol; mustahil, jadi r=0 dan I=(g). Untuk p berderajat positif, (p) maksimal iff p irreduksibel. Jika p irreduksibel, gcd(a,p)=1 untuk kelas [a]≠0; Bézout memberi inversnya. Faktorisasi tunggal diperoleh dari pembagian dan lema Euclid untuk faktor irreduksibel.', 'Choose nonzero g∈I of minimum degree. Dividing f∈I by g gives r∈I of lower degree if nonzero, impossible; thus r=0 and I=(g). For positive-degree p, (p) is maximal iff p is irreducible. If p is irreducible, every nonzero [a] has gcd(a,p)=1 and a Bézout inverse. Unique factorization follows from division and Euclid’s lemma for irreducible factors.', String.raw`ap+bf=1\implies[b][f]=[1]\ \text{in }F[x]/(p)`),
    q('Bangun F₄ dari F₂[x]/(x²+x+1).', 'Construct F₄ as F₂[x]/(x²+x+1).', 'Polinomial kuadrat ini tidak punya akar di F₂: nilainya 1 di 0 dan 1. Maka irreduksibel dan kuosien lapangan. Wakilnya 0,1,x,x+1; aturan x²=x+1 memberi x(x+1)=1.', 'This quadratic has no root in F₂: its value is 1 at both 0 and 1. Hence it is irreducible and the quotient a field. Representatives are 0,1,x,x+1; the rule x²=x+1 gives x(x+1)=1.', String.raw`\mathbb F_4\cong\mathbb F_2[x]/(x^2+x+1),\quad x^{-1}=x+1`),
  ],
  eisenstein: [
    q('Mengapa produk dua polinomial primitif tetap primitif?', 'Why is a product of primitive polynomials primitive?', 'Jika suatu prima p membagi semua koefisien fg, reduksi modulo p memberi f̄ḡ=0. Primitivitas menjamin f̄ dan ḡ bukan nol, bertentangan dengan Fₚ[x] daerah integral. Jadi tidak ada prima yang membagi seluruh koefisien produk. Keluarkan isi masing-masing faktor untuk memperoleh cont(fg)=cont(f)cont(g), inti Lemma Gauss.', 'If a prime p divided every coefficient of fg, reduction modulo p would give f̄ḡ=0. Primitivity makes both reductions nonzero, contradicting the integral domain Fₚ[x]. Thus no prime divides every product coefficient. Extract each factor’s content to obtain cont(fg)=cont(f)cont(g), the core of Gauss’s lemma.', String.raw`\operatorname{cont}(fg)=\operatorname{cont}(f)\operatorname{cont}(g)`),
    q('Gunakan Eisenstein pada 2x³+6x+3. Mengapa x²+4x+4 gagal?', 'Apply Eisenstein to 2x³+6x+3. Why does x²+4x+4 fail?', 'Prima 3 membagi koefisien nonutama 0,6,3; tidak membagi 2; dan 9 tidak membagi 3. Jadi polinomial pertama irreduksibel atas Q. Untuk yang kedua dengan p=2, konstanta 4 habis dibagi p²; bahkan x²+4x+4=(x+2)².', 'The prime 3 divides nonleading coefficients 0,6,3, misses 2, and 9 does not divide 3. Thus the first polynomial is irreducible over Q. For the second at p=2 the constant 4 is divisible by p²; indeed x²+4x+4=(x+2)².', String.raw`2x^3+6x+3\ \text{irreducible over }\mathbb Q,\qquad x^2+4x+4=(x+2)^2`),
  ],
}
