import type { VisualKind } from './summary-lessons'
type Bi = { id: string; en: string }
export interface ComplexActivity { tool: Bi; task: Bi; limitation: Bi; rows?: string[]; lab?: string; mode: 'calculator' | 'experiment' | 'proof' }
type Kind = 'triangle' | 'polar' | 'roots' | 'disc' | 'map' | 'derivative' | 'cr' | 'harmonic' | 'exp' | 'branch' | 'trig' | 'integral' | 'primitive' | 'cauchy' | 'series' | 'singularities' | 'residue' | 'cxLimitProof' | 'cxDerivativeRules' | 'cxAnalyticIdentity' | 'cxHarmonicConjugate' | 'cxElementaryDerivatives' | 'cxInverseFunctions' | 'cxRealParameter' | 'cxContourBranches' | 'cxDomains' | 'cxMaximum' | 'cxSequences' | 'cxSeriesConvergence' | 'cxPowerSeries' | 'cxTaylorCoefficients' | 'cxLaurentCoefficients' | 'cxZeros' | 'cxZeroPole' | 'cxLocalBehavior' | 'cxResidueInfinity' | 'cxResidueApplications'
const b = (id: string, en: string): Bi => ({ id, en })
const activity = (mode: ComplexActivity['mode'], toolId: string, toolEn: string, taskId: string, taskEn: string, limitationId: string, limitationEn: string, extras: Pick<ComplexActivity, 'rows' | 'lab'> = {}): ComplexActivity => ({ mode, tool: b(toolId, toolEn), task: b(taskId, taskEn), limitation: b(limitationId, limitationEn), ...extras })
const metadata = {
  triangle: activity('calculator', 'Studio: aritmetika dan Argand', 'Studio: arithmetic and Argand', 'Ubah z,w. Bandingkan |z+w| dengan |z|+|w|; cari kapan sama. Periksa pembagian dengan konjugat.', 'Change z,w. Compare |z+w| with |z|+|w| and find equality cases. Check division using conjugates.', 'Contoh numerik tidak membuktikan identitas untuk semua bilangan.', 'Numerical examples do not prove identities for every number.', { rows: ['z = 3+4i', 'w = 1-2i', 'z+w', 'abs(z+w)', 'abs(z)+abs(w)', 'conj(w)', 'z/w'] }),
  polar: activity('calculator', 'Studio: polar, Arg dan pangkat', 'Studio: polar, Arg and powers', 'Hitung polar dari −1+i, lalu kuadratnya. Jelaskan penjumlahan sudut modulo 2π.', 'Compute the polar form of −1+i and its square. Explain angle addition modulo 2π.', 'Arg utama mempunyai potongan; argumen 0 tidak ada.', 'Principal Arg has a cut; 0 has no argument.', { rows: ['z = -1+i', 'polar(z)', 'Arg(z)', 'pow(z, 2)', 'polar(z*z)'] }),
  roots: activity('calculator', 'Studio: akar ke-n', 'Studio: nth roots', 'Cari tiga akar −8i dan periksa pangkat ketiganya. Jelaskan jarak sudut 2π/3.', 'Find the three roots of −8i and verify their cubes. Explain the angular spacing 2π/3.', 'roots(w,n) menerima 1≤n≤24; hasil berbeda dari satu akar cabang utama.', 'roots(w,n) accepts 1≤n≤24 and differs from a single principal branch root.', { rows: ['roots(-8i, 3)', 'pow(2i, 3)'] }),
  disc: activity('calculator', 'Studio: daerah', 'Studio: regions', 'Ubah pusat dan kedua radius anulus. Nyatakan batas mana termasuk dan apakah himpunan terbuka.', 'Change the annulus center and radii. State which boundaries are included and whether the set is open.', 'Untuk ketaksamaan arbitrer, grid hanya sampel; sifat topologis umum perlu argumen sendiri.', 'For arbitrary inequalities the grid is only sampled; general topological properties require your own argument.', { rows: ['region(1 < |z-i| <= 2)', 'region(|z-i| < 2)'], lab: 'map' }),
  map: activity('experiment', 'Lab pemetaan', 'Mapping lab', 'Masukkan z²+1. Gerakkan titik dan segmen di bidang masukan, lalu hubungkan citranya dengan u,v.', 'Enter z²+1. Move input points and segments and connect their images to u,v.', 'Grid dan titik menunjukkan perilaku sampel, bukan bukti satu-ke-satu global.', 'Grid points show sampled behavior, not global injectivity.', { rows: ['f(z) = z^2+1', 'f(1+i)'], lab: 'mapping' }),
  derivative: activity('calculator', 'Studio: turunan dan lintasan limit', 'Studio: derivatives and sampled limits', 'Bandingkan derivative(z²,1+i), derivative(|z|²,0), dan limit(conj(z)/z,0). Bedakan turunan satu titik dari analitik.', 'Compare derivative(z²,1+i), derivative(|z|²,0), and limit(conj(z)/z,0). Distinguish differentiability at a point from analyticity.', 'Limit lewat beberapa lintasan adalah eksperimen; kesepakatan tidak membuktikan limit.', 'A finite collection of approach paths is an experiment; agreement does not prove a limit.', { rows: ['derivative(z^2, 1+i)', 'derivative(|z|^2, 0)', 'limit(conj(z)/z, 0)', 'limit((2z+1)/(z+1), inf)'] }),
  cxLimitProof: activity('proof', 'Bukti ε–δ dengan gambar', 'An ε–δ proof with a picture', 'Untuk z²→1, pilih δ=min(1,ε/3). Ubah ε dan tulis estimasi untuk semua z dalam cakram.', 'For z²→1 choose δ=min(1,ε/3). Change ε and write the bound for every z in the disc.', 'Sampel titik dan limit Studio tidak menggantikan kuantor ∀ε ∃δ ∀z.', 'Sampled points and Studio estimates do not replace the quantifiers ∀ε ∃δ ∀z.'),
  cxDerivativeRules: activity('calculator', 'Studio: produk, kuosien dan rantai', 'Studio: product, quotient and chain rules', 'Turunkan (2z²+i)⁵ dan z²eᶻ/(z−1). Sebutkan domain tiap rumus sebelum substitusi.', 'Differentiate (2z²+i)⁵ and z²eᶻ/(z−1). State each formula’s domain before substitution.', 'Rumus turunan tidak membuktikan fungsi terdiferensialkan pada titik cabang atau penyebut nol.', 'Derivative formulas do not establish differentiability at branch points or denominator zeros.', { rows: ['derivative((2z^2+i)^5)', 'derivative(z^2*exp(z)/(z-1), 0)'] }),
  cr: activity('calculator', 'Studio: syarat Cauchy–Riemann', 'Studio: Cauchy–Riemann conditions', 'Bandingkan CR untuk z², conj(z), dan |z|². Periksa kontinuitas parsial dan lingkungan terbuka.', 'Compare CR for z², conj(z), and |z|². Check continuous partial derivatives and an open neighborhood.', 'CR di satu titik tanpa hipotesis cukup tidak otomatis memberi turunan atau analitik.', 'CR at one point without sufficient hypotheses does not automatically imply a derivative or analyticity.', { rows: ['cr(z^2)', 'cr(conj(z))', 'cr(|z|^2)'] }),
  harmonic: activity('calculator', 'Studio: Laplace', 'Studio: Laplace test', 'Masukkan x²−y², lalu x²+y². Jelaskan hubungan CR dengan Δu=0.', 'Enter x²−y², then x²+y². Explain how CR relates to Δu=0.', 'Kalkulator konjugat menangani polinomial; eksistensi global pada domain berlubang perlu syarat integral loop.', 'The conjugate calculator handles polynomials; global existence on a domain with holes needs loop-integral conditions.', { rows: ['harmonic(x^2-y^2)', 'harmonic(x^2+y^2)'] }),
  cxHarmonicConjugate: activity('calculator', 'Studio: konjugat harmonik', 'Studio: harmonic conjugates', 'Cari v untuk y³−3x²y, lalu periksa kedua CR dan f=iz³. Ubah menjadi x²−y²+2x.', 'Find v for y³−3x²y, then verify both CR equations and f=iz³. Change it to x²−y²+2x.', 'Konjugat lokal belum tentu tunggal global; konstanta berbeda di komponen terpisah.', 'A local conjugate need not be globally single-valued; separate components may have different constants.', { rows: ['harmonic(y^3-3x^2*y)', 'cr(i*z^3)', 'harmonic(x^2-y^2+2x)'] }),
  cxAnalyticIdentity: activity('proof', 'Bukti keunikan dan nol terisolasi', 'Uniqueness and isolated-zero proof', 'Bandingkan f(1/n)=1/n untuk f entire dengan sin(π/z) pada C∖{0}. Tentukan apakah titik limit berada dalam domain.', 'Compare f(1/n)=1/n for an entire f with sin(π/z) on C∖{0}. Decide whether the accumulation point belongs to the domain.', 'Tidak ada solver yang menyimpulkan identitas dari beberapa nilai; keterhubungan dan titik limit interior wajib.', 'No solver infers an identity from finitely many values; connectedness and an interior accumulation point are essential.'),
  exp: activity('calculator', 'Studio dan pemetaan eksponensial', 'Studio and exponential mapping', 'Bandingkan exp(1+iπ/3) dan exp(1+iπ/3+2πi); jelaskan periodisitas dan modulus.', 'Compare exp(1+iπ/3) and exp(1+iπ/3+2πi); explain periodicity and modulus.', 'Pemetaan entire ini bukan satu-ke-satu global; diagram periodik bukan bukti otomatis.', 'This entire map is not globally one-to-one; a periodic diagram is not an automatic proof.', { rows: ['exp(1+i*pi/3)', 'exp(1+i*pi/3+2*pi*i)', 'derivative(exp(z))'], lab: 'mapping' }),
  branch: activity('calculator', 'Studio: log, Log dan pangkat', 'Studio: log, Log and powers', 'Bandingkan log(−1), Log(−1), dan i^i. Tulis seluruh keluarga nilai sebelum memilih cabang.', 'Compare log(−1), Log(−1), and i^i. Write the full value family before selecting a branch.', 'Evaluasi numerik memakai nilai utama; fungsi Log analitik hanya di domain yang menghindari potongan dan 0.', 'Numerical evaluation uses the principal value; Log is analytic only on a domain avoiding its cut and 0.', { rows: ['log(-1)', 'Log(-1)', 'i^i', 'derivative(log(z), 1)'], lab: 'map' }),
  trig: activity('calculator', 'Studio: trigonometri kompleks', 'Studio: complex trigonometry', 'Hitung sin(i), cos(i), dan identitas sin²i+cos²i. Bandingkan dengan jumlah kuadrat modulus.', 'Compute sin(i), cos(i), and sin²i+cos²i. Compare with the sum of squared magnitudes.', 'Identitas aljabar tidak memberi batas modulus real pada seluruh bidang kompleks.', 'An algebraic identity does not impose the real-variable magnitude bound on the complex plane.', { rows: ['sin(i)', 'cos(i)', 'sin(i)^2+cos(i)^2', 'abs(sin(i))^2+abs(cos(i))^2'] }),
  cxElementaryDerivatives: activity('calculator', 'Studio: turunan elementer', 'Studio: elementary derivatives', 'Turunkan sin(z²), tan(z), dan tanh(2z). Temukan nol penyebut yang harus dikeluarkan.', 'Differentiate sin(z²), tan(z), and tanh(2z). Locate denominator zeros that must be excluded.', 'Kutub kuosien bukan titik tempat rumus turunan berlaku.', 'Quotient poles are not points where the derivative formula applies.', { rows: ['derivative(sin(z^2))', 'derivative(tan(z), 0)', 'derivative(tanh(2z), 0)'] }),
  cxInverseFunctions: activity('calculator', 'Studio: invers melalui log dan akar', 'Studio: invers through logarithms and roots', 'Bangun Arcsin(z)=−iLog(iz+√(1−z²)), hitung di i, dan periksa sin dari hasilnya.', 'Build Arcsin(z)=−iLog(iz+√(1−z²)), evaluate at i, and check the sine of the result.', 'Ini cabang utama pada domain berpotongan; formula numerik tidak membuat invers global tunggal.', 'This is a principal branch on a cut domain; a numerical formula does not create a single global inverse.', { rows: ['f(z) = -i*log(i*z+sqrt(1-z^2))', 'a = f(i)', 'sin(a)', 'derivative(f, i)'] }),
  cxRealParameter: activity('experiment', 'Lab parameter real', 'Real-parameter lab', 'Ubah w(t), t₀, h dan interval. Bandingkan kuosien kiri/kanan, turunan dan integral definit; coba abs(t) di 0.', 'Change w(t), t₀, h and the interval. Compare left/right quotients, derivative and definite integral; try abs(t) at 0.', 'Selisih simetris dan dua resolusi Simpson tidak membuktikan keberadaan turunan atau memberi batas galat tersertifikasi.', 'Symmetric differences and two Simpson resolutions do not prove derivative existence or certify an error bound.', { lab: 'syllabus' }),
  integral: activity('calculator', 'Studio: integral kontur dan ML', 'Studio: contour integrals and ML', 'Hitung integral z² dan conj(z) di ruas 0→1+i. Ubah lintasan dan jelaskan faktor z′(t).', 'Integrate z² and conj(z) on 0→1+i. Change paths and explain the z′(t) factor.', 'Integral umum numerik; estimasi ML dari sampel maksimum perlu batas analitik yang dibuktikan.', 'General integrals are numerical; an ML estimate from a sampled maximum needs a proved analytic bound.', { rows: ['integral(z^2, segment(0, 1+i))', 'integral(conj(z), segment(0, 1+i))', 'ml(1/(z^2+1), circle(0, 3))'] }),
  cxContourBranches: activity('experiment', 'Studio dan domain cabang', 'Studio and branch domains', 'Bandingkan integral log(z) pada ruas 1→1+i dengan lingkaran yang memotong potongan utama.', 'Compare the integral of log(z) on 1→1+i with a circle crossing its principal cut.', 'Memasukkan log ke integrator tidak membuktikan cabang kontinu pada seluruh lintasan. Titik potongan harus dianalisis.', 'Entering log in the integrator does not establish a continuous branch on the entire path. Cut intersections must be analyzed.', { rows: ['integral(log(z), segment(1, 1+i))'], lab: 'map' }),
  primitive: activity('proof', 'Studio dan bukti kebebasan lintasan', 'Studio and path-independence proof', 'Bandingkan integral z² pada dua lintasan dengan ujung sama: jumlahkan dua integral ruas lewat 1. Bangun F=z³/3 dan jelaskan kapan antiturunan global ada.', 'Compare z² integrals on two paths with the same endpoints: add the two segment integrals through 1. Construct F=z³/3 and explain when a global antiderivative exists.', 'Beberapa lintasan sama belum membuktikan kebebasan semua lintasan; integral 1/z pada domain berlubang memberi penyangkal.', 'Agreement on a few paths does not prove path independence; integrating 1/z on a punctured domain gives a counterexample.', { rows: ['integral(z^2, segment(0, 1+i))', 'integral(z^2, segment(0, 1))', 'integral(z^2, segment(1, 1+i))', 'integral(1/z, circle(0, 1))'] }),
  cxDomains: activity('proof', 'Domain dan hipotesis Cauchy–Goursat', 'Domains and Cauchy–Goursat hypotheses', 'Bandingkan cakram, anulus dan domain terhapus. Untuk 1/z, jelaskan mengapa lingkaran mengelilingi 0 tidak dapat dikontraksikan di domain.', 'Compare a disc, annulus and punctured domain. For 1/z explain why a circle around 0 cannot be contracted inside the domain.', 'Grid daerah tidak menentukan simply connected secara otomatis; nyatakan lubang dan hipotesis teorema.', 'A region grid does not automatically decide simple connectedness; state holes and theorem hypotheses.', { rows: ['region(0 < |z| < 2)', 'integral(1/z, circle(0, 1))'], lab: 'map' }),
  cauchy: activity('calculator', 'Studio: rumus Cauchy', 'Studio: Cauchy formulas', 'Hitung integral e^(2z)/z⁴ pada lingkaran radius 2 dengan turunan ketiga di 0. Verifikasi faktor 3!.', 'Integrate e^(2z)/z⁴ on a radius-2 circle using the third derivative at 0. Verify the 3! factor.', 'f harus analitik pada dan di dalam kontur; a tidak boleh di luar atau pada kontur. Liouville perlu batas global.', 'f must be analytic on and inside the contour; a cannot lie outside or on it. Liouville requires a global bound.', { rows: ['C = circle(0, 2)', 'cauchy(exp(2z), 0, C, 3)', 'integral(exp(2z)/z^4, C)'] }),
  cxMaximum: activity('proof', 'Bukti modulus maksimum', 'Maximum-modulus proof', 'Bandingkan z² pada cakram dengan fungsi konstan. Jelaskan mengapa maksimum interior fungsi analitik memaksa konstan pada domain terhubung.', 'Compare z² on a disc with a constant function. Explain why an interior maximum forces an analytic function to be constant on a connected domain.', 'Nilai grid tidak membuktikan maksimum global; kesimpulan batas cakram perlu kontinuitas pada penutupan.', 'Grid values do not prove a global maximum; a disc-boundary conclusion needs continuity on the closure.'),
  cxSequences: activity('experiment', 'Lab barisan kompleks', 'Complex-sequence lab', 'Ubah q pada q^n dan p pada 1/n^p. Tambah N, bandingkan kedua komponen dan target L.', 'Change q in q^n and p in 1/n^p. Increase N and compare both components with a target L.', 'Ekor hingga yang tampak stabil tidak membuktikan semua suku setelah N memenuhi toleransi.', 'A stable finite tail does not prove every term after N satisfies the tolerance.', { lab: 'syllabus' }),
  cxSeriesConvergence: activity('experiment', 'Lab deret dan jumlah parsial', 'Series and partial-sum lab', 'Bandingkan geometri, Σ1/n dan Σ(−1)^(n−1)/n. Pisahkan suku, jumlah parsial dan konvergensi absolut.', 'Compare geometric series, Σ1/n and Σ(−1)^(n−1)/n. Separate terms, partial sums and absolute convergence.', 'Suku aₙ→0 belum cukup. Diameter ekor dan rasio sampel tidak memutuskan deret kustom.', 'aₙ→0 is insufficient. A sampled tail diameter and ratio do not decide a custom series.', { lab: 'syllabus' }),
  cxPowerSeries: activity('experiment', 'Lab deret pangkat', 'Power-series lab', 'Pada keluarga q^n, ganti q dengan titik z di dalam, di luar dan pada lingkaran satuan. Buktikan radius geometri R=1.', 'In the q^n family replace q with z inside, outside and on the unit circle. Prove the geometric radius R=1.', 'Eksperimen q^n mencakup satu deret pangkat; radius deret arbitrer perlu limsup atau informasi singularitas yang benar.', 'The q^n experiment covers one power series; an arbitrary radius needs a limsup or reliable singularity information.', { lab: 'syllabus', rows: ['taylor(1/(1-z), 0, 6)'] }),
  series: activity('calculator', 'Studio: Taylor dan Laurent', 'Studio: Taylor and Laurent', 'Kembangkan 1/[z(z−1)] di anulus 0<|z|<1 dan |z|>1. Jelaskan mengapa koefisien berbeda.', 'Expand 1/[z(z−1)] on 0<|z|<1 and |z|>1. Explain why the coefficients differ.', 'Koefisien dihitung numerik. Untuk fungsi umum, pencarian singularitas terbatas tidak menyertifikasi radius maksimum.', 'Coefficients are numerical. For general functions a bounded singularity search does not certify the maximal radius.', { rows: ['taylor(1/(1-z), 0, 6)', 'laurent(1/(z*(z-1)), 0, 4, 0.5)', 'laurent(1/(z*(z-1)), 0, 4, 2)'] }),
  cxTaylorCoefficients: activity('calculator', 'Studio: koefisien Taylor', 'Studio: Taylor coefficients', 'Bandingkan cₖ=f^(k)(0)/k! untuk e^(2z) dengan hasil Taylor. Jelaskan 2^k/k!.', 'Compare cₖ=f^(k)(0)/k! for e^(2z) with the Taylor result. Explain 2^k/k!.', 'Integral koefisien di Studio numerik; tulis turunan eksak dan radius sendiri untuk bukti.', 'Studio coefficient integrals are numerical; supply exact derivatives and the radius for a proof.', { rows: ['taylor(exp(2z), 0, 6)', 'derivative(exp(2z), 0)'] }),
  cxLaurentCoefficients: activity('calculator', 'Studio: koefisien pada anulus', 'Studio: coefficients on an annulus', 'Ubah radius ρ=0.5 dan 2 untuk fungsi yang sama. Kenali c₋₁ dan bagian utama tiap anulus.', 'Change ρ between 0.5 and 2 for the same function. Identify c₋₁ and each annulus’s principal part.', 'ρ tidak boleh melalui singularitas; anulus berbeda boleh memberi residu koefisien c₋₁ yang berbeda di pusat yang sama.', 'ρ must avoid singularities; different annuli may have different c₋₁ coefficients at the same center.', { rows: ['laurent(1/(z*(z-1)), 0, 4, 0.5)', 'laurent(1/(z*(z-1)), 0, 4, 2)'] }),
  singularities: activity('calculator', 'Studio: klasifikasi singularitas', 'Studio: singularity classification', 'Bandingkan sin(z)/z, 1/z² dan exp(1/z) di 0. Hubungkan jenisnya dengan pangkat negatif Laurent.', 'Compare sin(z)/z, 1/z² and exp(1/z) at 0. Connect their types with negative Laurent powers.', 'Deret negatif terpotong dan pola numerik tidak membuktikan singularitas esensial untuk fungsi arbitrer.', 'A truncated negative series and numerical patterns do not prove an essential singularity for an arbitrary function.', { rows: ['classify(sin(z)/z, 0)', 'classify(1/z^2, 0)', 'classify(exp(1/z), 0)', 'laurent(exp(1/z), 0, 5)'], lab: 'sing' }),
  cxZeros: activity('experiment', 'Lab orde faktor dan Studio nol', 'Factor-order lab and zero Studio', 'Ubah m pada c(z−a)^m. Hitung jumlah putaran citra dan bandingkan daftar nol (z−1)³(z+2).', 'Change m in c(z−a)^m. Count image turns and compare the zero list for (z−1)³(z+2).', 'Orde faktor yang dinyatakan eksak; pencarian Newton Studio tidak menjamin seluruh nol fungsi nonpolinomial.', 'Declared factor orders are exact; Studio Newton searches do not guarantee all nonpolynomial zeros.', { lab: 'syllabus', rows: ['zeros((z-1)^3*(z+2))'] }),
  cxZeroPole: activity('experiment', 'Lab pembatalan orde', 'Order-cancellation lab', 'Ubah m,n dalam c(z−a)^m/(z−a)^n. Bedakan fungsi asal yang mengeluarkan a dari perluasan removable.', 'Change m,n in c(z−a)^m/(z−a)^n. Distinguish the original punctured domain from a removable extension.', 'Mencoret faktor tidak otomatis memasukkan a kembali ke domain asal.', 'Cancelling a factor does not automatically restore a to the original domain.', { lab: 'syllabus', rows: ['classify((z-1)^3/(z-1), 1)'] }),
  cxLocalBehavior: activity('experiment', 'Lab modulus dan putaran lokal', 'Local magnitude and winding lab', 'Perkecil r dan bandingkan |f| pada r dan r/2. Untuk kutub, lihat putaran terbalik dan modulus membesar.', 'Shrink r and compare |f| at r and r/2. For a pole observe reversed winding and growing magnitudes.', 'Model faktor monomial tidak membuktikan teorema Picard atau perilaku esensial fungsi arbitrer.', 'A monomial factor model does not prove Picard’s theorem or arbitrary essential-singularity behavior.', { lab: 'syllabus', rows: ['classify(exp(1/z), 0)'] }),
  residue: activity('calculator', 'Studio: residu finite', 'Studio: finite residues', 'Hitung residu eᶻ/z² di 0 dan 1/(z²+1)² di i. Bandingkan dengan koefisien Laurent c₋₁.', 'Find residues of eᶻ/z² at 0 and 1/(z²+1)² at i. Compare with the Laurent coefficient c₋₁.', 'Residu orde tinggi dan koefisien umum numerik; cocokkan dengan rumus turunan untuk kutub orde m.', 'Higher-order residues and general coefficients are numerical; compare with the derivative formula for an order-m pole.', { rows: ['residue(exp(z)/z^2, 0)', 'residue(1/(z^2+1)^2, i)', 'laurent(exp(z)/z^2, 0, 4)'] }),
  cxResidueInfinity: activity('experiment', 'Lab residu di tak hingga', 'Infinity-residue lab', 'Masukkan fungsi rasional; ambil negatif koefisien z⁻¹. Ubah R dan bandingkan integral lingkaran dengan −Res∞.', 'Enter a rational function and negate its z⁻¹ coefficient. Change R and compare the circle integral with −Res∞.', 'Pembagian formal memakai floating point. Lingkaran hanya cocok bila semua kutub berada di dalam dan tidak ada pada kontur.', 'Formal division uses floating point. The circle agrees only when every finite pole is inside and none is on the contour.', { lab: 'syllabus', rows: ['residues((5z-2)/(z*(z-1)), circle(0, 2))'] }),
  cxResidueApplications: activity('proof', 'Residu dan integral real', 'Residues and real integrals', 'Untuk 1/(1+z²), hitung residu i lalu buktikan integral busur atas menuju 0. Deduksi integral real dari −∞ sampai ∞.', 'For 1/(1+z²), find the residue at i and prove the upper-arc integral tends to 0. Deduce the real integral over the whole line.', 'Integral real tak hingga tidak dihitung otomatis oleh Studio; pemilihan kontur, kutub dan estimasi busur memerlukan bukti.', 'Studio does not automatically evaluate improper real integrals; contour choice, pole location and arc estimates require a proof.', { rows: ['residue(1/(1+z^2), i)'] }),
} satisfies Record<Kind, ComplexActivity>
export const COMPLEX_ACTIVITIES: Partial<Record<VisualKind, ComplexActivity>> = metadata
