import type { VisualKind } from './summary-lessons'

type B = { id: string; en: string }
export type GeometryActivity = { tool: B; task: B; limitation: B; rows?: string[]; dimension?: '2D' | '3D'; lab?: string; mode: 'calculator' | 'experiment' | 'proof' }
const b = (id: string, en: string): B => ({ id, en })
const calc = (task: B, rows: string[], dimension: '2D' | '3D' = '2D', limitation: B = b('Ubah masukan lalu cocokkan langkah hitungan dengan rumus. Grafik numerik bukan bukti untuk semua data.', 'Edit the inputs and compare the calculation steps with the formula. A numerical plot is not a proof for every input.')): GeometryActivity => ({ tool: b('Studio Geometri', 'Geometry Studio'), task, limitation, rows, dimension, mode: 'calculator' })
const experiment = (task: B, limitation: B): GeometryActivity => ({ tool: b('Eksperimen geometri dengan masukan langsung', 'Geometry experiment with live inputs'), task, limitation, lab: 'syllabus', dimension: '3D', mode: 'experiment' })
const numerical = b('Kesimpulan nol, rank dan kesamaan memakai toleransi numerik. Jelaskan klaim umum dengan pembuktian.', 'Zero, rank and equality conclusions use numerical tolerances. Justify general claims with a proof.')
const lines = ['A=(0,0,0)', 'B=(2,1,1)', 'l=line(A,B)', 'P=(1,2,3)', 'p=plane(1,1,1,-3)']
const conic = ['C=5x^2+4xy+2y^2-8x-4y-1=0', 'classify(C)']
const quadric = ['Q=x^2+y^2-z^2-1=0', 'classify(Q)']
const maps = ['P=(2,1)', 'Q=(0,1)', 'T=affine(0,-1,1,0,1,0)', 'apply(T,P)', 'apply(T,Q)', 'classify(T)']

/** All 42 geometry lessons have a concrete reproducible activity, not just a generic link. */
export const GEOMETRY_ACTIVITIES: Partial<Record<VisualKind, GeometryActivity>> = {
  incidence: experiment(b('Ubah P untuk menguji apakah ia pada garis AB atau bidang ABC. Buat C segaris dengan A,B dan jelaskan hilangnya bidang unik.', 'Change P to check membership in line AB or plane ABC. Make C collinear with A,B and explain the loss of a unique plane.'), b('Percobaan insidensi memakai koordinat Euclid. Aksioma umum tetap memerlukan argumen tertulis.', 'The incidence experiment uses Euclidean coordinates. General axioms still require a written argument.')),
  freeVectors: experiment(b('Ubah u,v,k; cocokkan penjumlahan paralelogram dan perkalian skalar. Jelaskan mengapa pangkal panah boleh dipindah.', 'Change u,v,k; compare parallelogram addition and scalar multiplication. Explain why an arrow’s tail may move.'), numerical),
  signedRatio: experiment(b('Uji t=0.4, t=1 dan t=1.5. Bandingkan pembagian dalam, titik ujung dan pembagian luar.', 'Try t=0.4, t=1 and t=1.5. Compare internal division, an endpoint and external division.'), b('Rasio t/(1−t) tidak terdefinisi saat t=1; A=B membuat ruas degenerat.', 'The ratio t/(1−t) is undefined at t=1; A=B makes the segment degenerate.')),
  basis: experiment(b('Ubah kolom B dan titik P. Rekonstruksi P=O+Bc. Buat dua kolom sama untuk melihat basis singular.', 'Edit B’s columns and P. Reconstruct P=O+Bc. Make two columns equal to observe a singular basis.'), numerical),
  affineFrames: experiment(b('Geser O sementara B dan P tetap. Jelaskan mengapa koordinat titik berubah tetapi basis vektor tetap.', 'Move O while B and P stay fixed. Explain why point coordinates change while the vector basis stays the same.'), numerical),
  products: experiment(b('Hitung u·v, u×v dan (u×v)·w. Buat u,v sejajar, lalu tukar urutannya untuk memeriksa orientasi.', 'Compute u·v, u×v and (u×v)·w. Make u,v parallel, then swap their order to inspect orientation.'), b('Sudut gambar proyeksi dapat berbeda dari sudut ruang yang dihitung. Vektor nol tidak mempunyai sudut arah.', 'A projected picture angle may differ from the computed spatial angle. A zero vector has no direction angle.')),
  curveSurface: experiment(b('Edit tiga fungsi kurva dan tiga fungsi permukaan. Coba heliks, bidang dan permukaan kerucut; periksa turunan lokal dan normal.', 'Edit three curve and three surface functions. Try a helix, plane and cone surface; inspect local derivatives and normals.'), b('Turunan merupakan beda hingga h=10⁻⁴. Sampling pada domain terbatas tidak membuktikan regularitas global atau seluruh lokus.', 'Derivatives use finite differences h=10⁻⁴. Sampling on bounded domains does not establish global regularity or the entire locus.')),
  plane: calc(b('Bangun garis dari A,B dan bidang dari tiga titik tidak segaris. Bandingkan persamaan normal dan titik potong.', 'Construct a line from A,B and a plane from three noncollinear points. Compare the normal equation and intersection.'), [...lines, 'intersect(l,p)', 'plane((0,0,0),(1,0,0),(0,1,1))'], '3D'),
  lineSystems: calc(b('Ubah garis m untuk menghasilkan garis berpotongan, sejajar atau bersilangan. Cocokkan position dengan distance.', 'Edit m to obtain intersecting, parallel or skew lines. Compare position with distance.'), ['l=line((0,0,0),(1,1,0))', 'm=line((0,0,1),(1,-1,1))', 'position(l,m)', 'distance(l,m)', 'perpendicular(l,m)'], '3D'),
  projection: calc(b('Ubah P dan normal bidang. Periksa bahwa kaki proyeksi berada pada bidang dan perpindahannya sejajar normal.', 'Edit P and the plane normal. Check that the projection foot lies on the plane and the displacement follows the normal.'), [...lines, 'projection(P,p)', 'projection(P,l)', 'distance(P,p)'], '3D'),
  spatialDistances: calc(b('Bandingkan jarak titik–garis, titik–bidang dan dua garis bersilangan; gunakan panel Langkah untuk rumusnya.', 'Compare point–line, point–plane and skew-line distances; use the Steps panel for the formulas.'), [...lines, 'm=line((0,0,2),(1,-1,2))', 'distance(P,l)', 'distance(P,p)', 'distance(l,m)'], '3D'),
  halfSpaces: experiment(b('Ubah P dan λ. Tentukan tanda Fλ(P) dan jarak bertanda; negasikan normal serta konstanta untuk menukar label sisi.', 'Edit P and λ. Determine the sign of Fλ(P) and signed distance; negate both normal and constant to swap side labels.'), b('Tanda bergantung orientasi normal. Jika normal menjadi nol, persamaan bukan bidang biasa.', 'The sign depends on normal orientation. If the normal vanishes, the equation is not an ordinary plane.')),
  pencilsBundles: experiment(b('Ubah λ pada kombinasi dua persamaan bidang. Periksa titik irisan yang tetap di setiap anggota dan parameter degenerat.', 'Edit λ in a combination of two plane equations. Inspect a common intersection point and degenerate parameters.'), b('Panel ini menghitung pensil dua bidang. Bundel tiga pembentuk dan klaim umum dijelaskan melalui langkah pembuktian.', 'This panel computes a two-plane pencil. Three-generator bundles and general claims use the proof steps.')),
  locusGenerators: calc(b('Iris bola dengan bidang dan ubah konstanta bidang; bandingkan lingkaran real, singgung dan irisan kosong.', 'Intersect a sphere with a plane and change the plane constant; compare real circles, tangency and empty intersections.'), ['s=sphere((0,0,0),3)', 'p=plane(0,0,1,-1)', 'intersect(s,p)'], '3D', b('Contoh menghasilkan lokus irisan bola–bidang. Pembuktian lokus lain tetap mengikuti syarat geometri masing-masing.', 'This example generates a sphere–plane intersection locus. Other locus proofs still follow their own geometric conditions.')),
  circleSphereData: calc(b('Ubah koefisien lingkaran/bola; tentukan pusat, radius serta kasus radius kuadrat nol/negatif dari persamaan.', 'Edit circle/sphere coefficients; find centers, radii and zero/negative squared-radius cases from the equations.'), ['c=x^2+y^2-4x-2y-4=0', 's=x^2+y^2+z^2-2x+4y-9=0', 'center(c)', 'radius(c)', 'center(s)', 'radius(s)'], '3D'),
  secantDiscriminant: calc(b('Geser garis l untuk memperoleh dua, satu atau nol titik potong lingkaran. Baca diskriminan pada panel Langkah.', 'Move l to obtain two, one or zero circle intersections. Read the discriminant in the Steps panel.'), ['c=circle((0,0),2)', 'l=line((-3,1),(3,1))', 'intersect(l,c)']),
  power: calc(b('Gerakkan P melintasi batas lingkaran; cocokkan tanda kuasa dengan posisi luar, pada, atau dalam.', 'Move P across the circle boundary; match the power sign to outside, on-circle or inside positions.'), ['c=circle((0,0),2)', 'P=(3,1)', 'power(P,c)', 'tangent(P,c)']),
  sphereTangency: calc(b('Ubah titik P pada bola; tentukan bidang singgung melalui polar. Titik luar mempunyai bidang kontak, bukan satu bidang singgung di P.', 'Edit the on-sphere point P and find its tangent plane using the polar. An exterior point has a contact plane, not a tangent plane at P.'), ['s=sphere((0,0,0),2)', 'P=(2,0,0)', 'polar(P,s)', 'tangent(P,s)'], '3D'),
  radical: calc(b('Ubah pusat/radius dua lingkaran dan bandingkan kuasa titik pada sumbu radikal.', 'Edit two circle centers/radii and compare point powers on the radical axis.'), ['c1=circle((0,0),2)', 'c2=circle((2,0),2)', 'radical(c1,c2)', 'P=(1,1)', 'power(P,c1)', 'power(P,c2)']),
  radicalSystems: experiment(b('Ubah tiga bola. Hitung dua bidang radikal dan rank sistemnya; bedakan garis, keluarga dan sistem tidak konsisten.', 'Edit three spheres. Compute two radical planes and system rank; distinguish a line, family and inconsistent system.'), numerical),
  circlePencil: { ...experiment(b('Muat dua lingkaran ke Studio lalu ubah bobot pencil. Di eksperimen bola, ubah λ dan cocokkan pusat/radius kuadrat dengan kombinasi persamaannya.', 'Load two circles into Studio and edit the pencil weight. In the sphere experiment, edit λ and compare the center/squared radius with the equation combination.'), b('Eksperimen memperluas pensil ke bola. Anggota radikal membutuhkan bentuk tak ternormalisasi; lokus dengan radius kuadrat negatif kosong.', 'The experiment extends pencils to spheres. The radical member needs an unnormalized form; negative squared radius means an empty real locus.')), rows: ['c1=circle((0,0),2)', 'c2=circle((2,0),2)', 'pencil(c1,c2,0.5)', 'radical(c1,c2)'], dimension: '2D' },
  conic: calc(b('Ubah koefisien konik lalu cocokkan klasifikasi, pusat dan bentuk kanonik. Mulai dengan elips berotasi.', 'Edit conic coefficients and compare classification, center and canonical form. Begin with a rotated ellipse.'), conic),
  focusDirectrix: calc(b('Bandingkan parabola y²=4x dengan konik lain. Hubungkan parameter kanonik dengan definisi fokus–direktriks.', 'Compare the parabola y²=4x with other conics. Connect canonical parameters to the focus–directrix definition.'), ['C=y^2-4x=0', 'classify(C)'], '2D', b('Studio mengklasifikasikan persamaan dan parameter kanonik; gambar/langkah konsep menjelaskan fokus–direktriks. Tidak semua kurva mempunyai direktriks dari perintah tersendiri.', 'Studio classifies equations and canonical parameters; concept visuals/steps explain focus–directrix. There is no separate directrix command for every curve.')),
  quadric: calc(b('Ubah tanda dan konstanta kuadrik. Putar tampilan 3D dan cocokkan bentuk kanonik dengan tipe permukaan.', 'Edit quadric signs and constants. Orbit the 3D view and compare the canonical form with the surface type.'), quadric, '3D'),
  quadraticMatrix: experiment(b('Masukkan A simetris, a dan α; cocokkan F(p), gradien dan pusat dengan persamaan kuadrat. Perhatikan faktor 2 pada suku campuran/linear.', 'Enter symmetric A, a and α; compare F(p), gradient and center with the quadratic equation. Mind the factor 2 on mixed/linear terms.'), numerical),
  asymptoticDirections: experiment(b('Cari u≠0 dengan uᵀAu=0. Bandingkan syarat itu dengan syarat garis penuh: F(p)=0 dan (Ap+a)·u=0 juga harus terpenuhi.', 'Find nonzero u with uᵀAu=0. Compare this with the full-line conditions: F(p)=0 and (Ap+a)·u=0 must also hold.'), b('Arah isotropik saja belum menjamin garis generator pada titik yang dipilih. Kesamaan numerik membutuhkan pembuktian koefisien.', 'An isotropic direction alone does not guarantee a generator through the selected point. Numerical equality needs a coefficient proof.')),
  quadricRulings: experiment(b('Pada x²+y²−z²=1, mulai p=(1,0,0), u=(0,1,1). Periksa tiga koefisien F(p+tu), lalu ubah u untuk melihat garis yang tidak menjadi generator.', 'For x²+y²−z²=1, start at p=(1,0,0), u=(0,1,1). Inspect the three coefficients of F(p+tu), then edit u to obtain a nongenerator.'), numerical),
  geoTangent: experiment(b('Hitung polar untuk p, lalu uji apakah p pada lokus dan gradien tidak nol. Hanya dalam kasus regular pada lokus, polar menjadi bidang singgung.', 'Compute the polar of p, then check locus membership and a nonzero gradient. Only at a regular on-locus point does the polar become the tangent plane.'), b('Gradien nol tidak menentukan satu bidang singgung dari rumus biasa. Polar dengan normal nol dapat kosong atau seluruh ruang.', 'A zero gradient does not define a unique tangent plane by the ordinary formula. A polar with zero normal can be empty or all space.')),
  geoCenter: experiment(b('Edit A dan a untuk mendapatkan pusat unik, keluarga pusat atau tidak ada pusat. Jelaskan rank A dan konsistensi Ax=−a.', 'Edit A and a to obtain a unique center, center family or no center. Explain rank A and consistency of Ax=−a.'), numerical),
  geoConjugate: experiment(b('Ubah u,v agar uᵀAv=0. Bandingkan dengan dot product biasa; konjugasi bergantung bentuk A.', 'Edit u,v so uᵀAv=0. Compare with the ordinary dot product; conjugacy depends on A.'), b('Arah nol bukan arah garis. Hubungan konjugat tidak harus berarti tegak lurus Euclid.', 'A zero vector is not a line direction. Conjugacy need not mean Euclidean perpendicularity.')),
  eigen: calc(b('Ubah suku xy dan baca arah utama/nilai eigen. Cocokkan rotasi sumbu dengan hilangnya suku campuran.', 'Edit the xy term and read principal directions/eigenvalues. Compare axis rotation with removal of mixed terms.'), conic),
  reduce: calc(b('Baca translasi, rotasi dan persamaan kanonik setelah classify. Periksa mengapa transformasi koordinat tidak mengubah lokus geometrinya.', 'Read the translation, rotation and canonical equation after classify. Explain why coordinate changes preserve the geometric locus.'), conic),
  geoConicClass: calc(b('Ubah a dari 1 ke −1 dan 0; cocokkan tipe eliptik, hiperbolik dan degenerasi. Ubah konstanta untuk kasus kosong/titik.', 'Change a from 1 to −1 and 0; compare elliptic, hyperbolic and degenerate types. Change the constant for empty/point cases.'), ['a=1', 'C=x^2+a*y^2-1=0', 'classify(C)']),
  geoQuadricClass: calc(b('Ubah tanda a dan konstanta kuadrik; periksa rank, inersia dan bentuk kanonik dengan galeri 17 kelas.', 'Edit a’s sign and the quadric constant; compare rank, inertia and canonical form with the 17-class gallery.'), ['a=-1', 'Q=x^2+y^2+a*z^2-1=0', 'classify(Q)'], '3D'),
  geoInvariants: calc(b('Klasifikasikan C dan bayangannya oleh rotasi. Bandingkan invarian ortogonal dan jelaskan mengapa penskalaan seluruh persamaan mengubah nilai mentah.', 'Classify C and its rotated image. Compare orthogonal invariants and explain why scaling the whole equation changes raw values.'), [...conic, 'T=rotate(30)', 'D=apply(T,C)', 'classify(D)']),
  geoComposition: experiment(b('Ubah T,S lalu bandingkan S(T(P)) dengan T(S(P)). Cocokkan matriks NM dan vektor Nc+d dengan substitusi berurutan.', 'Edit T,S and compare S(T(P)) with T(S(P)). Match NM and Nc+d with successive substitution.'), b('Urutan komposisi harus disebutkan. Titik contoh yang kebetulan sama tidak membuktikan kedua peta identik.', 'State the composition order. Agreement at one example point does not prove two maps identical.')),
  affine: experiment(b('Ubah M,c pada peta 3D. Bandingkan matriks invertibel dengan singular dan jelaskan pengaruhnya pada titik serta arah.', 'Edit M,c in the 3D map. Compare invertible and singular matrices and explain the effect on points and directions.'), numerical),
  geoAffineFrame: experiment(b('Gunakan kolom B sebagai arah kerangka. Geser O, ubah P, dan jelaskan hubungan koordinat baru dengan kerangka lama.', 'Use B’s columns as frame directions. Move O, edit P, and explain the relation between new and old coordinates.'), numerical),
  geoSimilarity: experiment(b('Masukkan M=kR untuk R ortogonal; periksa MᵀM=k²I dan perubahan panjang. Bandingkan dengan shear.', 'Enter M=kR for orthogonal R; check MᵀM=k²I and length scaling. Compare with a shear.'), b('Panjang satu pasangan tidak cukup untuk similaritas. Gunakan kondisi matriks, dengan k>0.', 'A single pair’s length is insufficient for similarity. Use the matrix condition with k>0.')),
  isometry: calc(b('Bandingkan P,Q dan bayangannya oleh peta 2D. Baca classify(T) untuk syarat ortogonal dan orientasi.', 'Compare P,Q and their images under the 2D map. Read classify(T) for orthogonality and orientation.'), maps),
  geoMotions: experiment(b('Coba rotasi 3D, refleksi bidang dan refleksi pusat. Bandingkan det M dan MᵀM; jelaskan bahwa refleksi pusat 3D membalik orientasi.', 'Try a 3D rotation, plane reflection and central reflection. Compare det M and MᵀM; explain that 3D central reflection reverses orientation.'), b('Nama gerakan tidak ditentukan hanya oleh gambar proyeksi. Syarat matriks dan dimensi menentukan orientasi.', 'The projected picture alone does not identify a motion. Matrix conditions and dimension determine orientation.')),
  geoInversion: experiment(b('Ubah P dan k, lalu cocokkan I(I(P))=P. Coba k<0 dan jelaskan arah radial serta ketiadaan titik tetap real.', 'Edit P and k, then check I(I(P))=P. Try negative k and explain radial direction and the absence of real fixed points.'), b('Pusat O dan k=0 tidak diperbolehkan. Inversi dihitung di ℝ³; lingkaran pada gambar adalah irisan dari bola radius √|k|.', 'The center O and k=0 are excluded. Inversion is computed in ℝ³; the pictured circle is a section of the radius-√|k| sphere.')),
}
