import type { VisualKind } from './summary-lessons'
import { b, step, geometryTopic, exercise } from './geometry-slide-model'
import type { GeometryTopic, GeometryDeck, GeometrySection, GeometryExercise } from './geometry-slide-model'

export type ClassificationKind = 'geoTangent' | 'geoCenter' | 'geoConjugate' | 'geoConicClass' | 'geoQuadricClass' | 'geoInvariants' | 'geoComposition' | 'geoAffineFrame' | 'geoSimilarity' | 'geoMotions' | 'geoInversion'
const s = step
const tex = String.raw

export const CONIC_CASES = [
  { name: b('Elips nyata', 'Real ellipse'), equation: tex`X^2/4+Y^2=1` },
  { name: b('Elips imajiner: lokus real kosong', 'Imaginary ellipse: empty real locus'), equation: tex`X^2+Y^2=-1` },
  { name: b('Hiperbola', 'Hyperbola'), equation: tex`X^2-Y^2=1` },
  { name: b('Parabola', 'Parabola'), equation: tex`Y^2=2X` },
  { name: b('Dua garis berpotongan nyata', 'Two real intersecting lines'), equation: tex`X^2-Y^2=0` },
  { name: b('Garis imajiner berpotongan: satu titik real', 'Imaginary intersecting lines: one real point'), equation: tex`X^2+Y^2=0` },
  { name: b('Dua garis sejajar nyata', 'Two real parallel lines'), equation: tex`X^2=1` },
  { name: b('Garis sejajar imajiner: lokus real kosong', 'Imaginary parallel lines: empty real locus'), equation: tex`X^2=-1` },
  { name: b('Garis berhimpit', 'Double line'), equation: tex`X^2=0` },
]
export const QUADRIC_CASES = [
  { name: b('Elipsoida nyata', 'Real ellipsoid'), equation: tex`X^2+Y^2+Z^2=1` },
  { name: b('Elipsoida imajiner: kosong', 'Imaginary ellipsoid: empty'), equation: tex`X^2+Y^2+Z^2=-1` },
  { name: b('Hiperboloida satu lembar', 'One-sheet hyperboloid'), equation: tex`X^2+Y^2-Z^2=1` },
  { name: b('Hiperboloida dua lembar', 'Two-sheet hyperboloid'), equation: tex`Z^2-X^2-Y^2=1` },
  { name: b('Paraboloida eliptik', 'Elliptic paraboloid'), equation: tex`X^2+Y^2=2Z` },
  { name: b('Paraboloida hiperbolik', 'Hyperbolic paraboloid'), equation: tex`X^2-Y^2=2Z` },
  { name: b('Kerucut nyata', 'Real cone'), equation: tex`X^2+Y^2-Z^2=0` },
  { name: b('Kerucut imajiner: satu titik real', 'Imaginary cone: one real point'), equation: tex`X^2+Y^2+Z^2=0` },
  { name: b('Tabung eliptik', 'Elliptic cylinder'), equation: tex`X^2+Y^2=1` },
  { name: b('Tabung hiperbolik', 'Hyperbolic cylinder'), equation: tex`X^2-Y^2=1` },
  { name: b('Tabung parabolik', 'Parabolic cylinder'), equation: tex`Y^2=2X` },
  { name: b('Tabung imajiner: kosong', 'Imaginary cylinder: empty'), equation: tex`X^2+Y^2=-1` },
  { name: b('Dua bidang berpotongan nyata', 'Two real intersecting planes'), equation: tex`X^2-Y^2=0` },
  { name: b('Bidang imajiner berpotongan: satu garis real', 'Imaginary intersecting planes: one real line'), equation: tex`X^2+Y^2=0` },
  { name: b('Dua bidang sejajar nyata', 'Two real parallel planes'), equation: tex`X^2=1` },
  { name: b('Bidang sejajar imajiner: kosong', 'Imaginary parallel planes: empty'), equation: tex`X^2=-1` },
  { name: b('Bidang berhimpit', 'Double plane'), equation: tex`X^2=0` },
]

export const CLASSIFICATION_TOPICS: Record<ClassificationKind, GeometryTopic> = {
  geoTangent: geometryTopic({
    visual: 'geoTangent', title: b('Singgung, polar, normal dan sudut kuadratik (3.3)', 'Quadratic tangents, polars, normals and angles (3.3)'),
    question: b('Bagaimana satu bentuk bilinear menghasilkan garis polar dan bidang singgung?', 'How does one bilinear form produce both polars and tangent planes?'),
    meaning: b('Untuk f(r)=rᵀAr+2aᵀr+α dengan A simetris, polarisasi mengganti satu salinan r oleh titik p. Pada titik kurva yang reguler, hasilnya singgung; di luar kurva, hasilnya polar.', 'For f(r)=rᵀAr+2aᵀr+α with symmetric A, polarization replaces one copy of r by the point p. At a regular point of the curve it gives the tangent; off the curve it gives the polar.'),
    tex: tex`P_p(r)=r^TAp+a^T(r+p)+\alpha=0`,
    picture: b('Lingkaran berjari-jari 2, titik luar P, polarnya, lalu singgung di titik Q.', 'A circle of radius 2, an external point P, its polar, then the tangent at Q.'),
    steps: [
      s('Pisahkan bentuk simetris', 'Separate the symmetric form', 'Karena xy muncul dua kali di rᵀAr, koefisien xy dibagi dua dalam matriks A. Koefisien linear juga dibagi dua untuk a.', 'Because xy occurs twice in rᵀAr, halve its coefficient in A. Also halve the linear coefficients to obtain a.', tex`f(r)=r^TAr+2a^Tr+\alpha,\quad A=A^T`),
      s('Polarisasi, bukan substitusi penuh', 'Polarize, rather than fully substitute', 'Ganti rᵀAr oleh rᵀAp, dan 2aᵀr oleh aᵀ(r+p). Jika p bukan titik pada objek, ini merupakan polar p.', 'Replace rᵀAr by rᵀAp, and 2aᵀr by aᵀ(r+p). If p is off the object, this is its polar.', tex`P_p(r)=r^TAp+a^T(r+p)+\alpha`),
      s('Di titik reguler, dapatkan singgung', 'At a regular point, obtain the tangent', 'Jika f(p)=0, persamaan polar sama dengan (Ap+a)ᵀ(r−p)=0. Gradien 2(Ap+a) adalah normalnya. Vektor normal tak nol diperlukan.', 'If f(p)=0, the polar equation equals (Ap+a)ᵀ(r−p)=0. Its normal is the gradient 2(Ap+a). A nonzero normal is required.', tex`\nabla f(p)=2(Ap+a),\quad (Ap+a)^T(r-p)=0`),
      s('Gunakan normal untuk sudut dan arah singgung', 'Use normals for angles and tangent directions', 'Normal melalui p berarah Ap+a. Sudut lancip dua objek reguler yang berpotongan memakai nilai mutlak hasil kali skalar kedua normal. Kontak yang sejajar v memenuhi vᵀ(Ap+a)=0.', 'The normal through p has direction Ap+a. The acute angle between intersecting regular objects uses the absolute dot product of their normals. Contact parallel to v satisfies vᵀ(Ap+a)=0.', tex`r=p+t(Ap+a),\quad\cos\theta=\frac{|n_1\cdot n_2|}{\|n_1\|\|n_2\|},\quad v^T(Ap+a)=0`),
    ],
    conditions: [b('Koordinat ortonormal diperlukan untuk membaca normal dan sudut Euclid dari koefisien. Polarisasi selalu memberi persamaan, tetapi garis/bidang polar memerlukan Ap+a≠0; bila nol, persamaan konstan dapat kosong atau seluruh ruang. Contoh: polar pusat x²+y²=4 menjadi −4=0, jadi kosong. Singgung unik memerlukan f(p)=0 dan Ap+a≠0.', 'Use orthonormal coordinates to read Euclidean normals and angles from coefficients. Polarization always gives an equation, but a polar line/plane requires Ap+a≠0; otherwise the constant equation may be empty or all space. For example, the polar of the center of x²+y²=4 gives−4=0, hence an empty set. A unique tangent requires f(p)=0 and Ap+a≠0.')],
    failure: b('Pada p=(0,0) untuk x²−y²=0, gradien nol dan polarisasi menjadi 0=0: dua cabang punya dua arah singgung, bukan satu garis singgung unik.', 'At p=(0,0) for x²−y²=0, the gradient vanishes and polarization gives 0=0: the two branches have two tangent directions, not one unique tangent.'),
    examplePrompt: b('Cari polar P=(3,0), singgung dan normal Q=(0,2) terhadap x²+y²=4.', 'Find the polar of P=(3,0), and the tangent and normal at Q=(0,2), for x²+y²=4.'),
    exampleSteps: [
      s('Baca koefisien', 'Read the coefficients', 'Matriks I, a=0 dan α=−4 membuat polar cukup berupa r·p−4=0.', 'A=I, a=0 and α=−4 make the polar simply r·p−4=0.', tex`A=I,\quad a=0,\quad P_p(r)=r\cdot p-4`),
      s('Titik luar menghasilkan polar', 'An exterior point gives a polar', 'P tidak ada pada lingkaran karena 9≠4. Garis x=4/3 adalah polar, bukan singgung di P.', 'P is off the circle since 9≠4. The line x=4/3 is its polar, not a tangent at P.', tex`P_P(r)=3x-4=0\quad\Rightarrow x=4/3`),
      s('Titik pada lingkaran menghasilkan singgung', 'A point on the circle gives a tangent', 'Q memenuhi persamaan dan normalnya (0,2) tak nol. Singgung y=2; normal x=0 melewati Q dan pusat.', 'Q satisfies the equation and its normal (0,2) is nonzero. The tangent is y=2; the normal x=0 passes through Q and the center.', tex`2y-4=0,\quad r=(0,2)+t(0,2)`),
    ], check: { question: b('Untuk bola x²+y²+z²=9, apa singgung di (1,2,2)?', 'For x²+y²+z²=9, what is the tangent at (1,2,2)?'), answer: b('x+2y+2z=9; normal berarah (1,2,2). Titik tersebut memenuhi 1+4+4=9.', 'x+2y+2z=9; the normal has direction (1,2,2). The point satisfies 1+4+4=9.') },
  }),
  geoCenter: geometryTopic({
    visual: 'geoCenter', title: b('Pusat simetri: unik, banyak atau tidak ada (3.3)', 'Symmetry centers: unique, many or none (3.3)'),
    question: b('Mengapa pusat ditemukan dari sistem linear, dan kapan rumus invers gagal?', 'Why are centers found through a linear system, and when does the inverse formula fail?'),
    meaning: b('Pusat aljabar adalah titik h yang membuat f(h+u)=f(h−u) untuk setiap u. Pergeseran ke pusat menghapus seluruh suku linear. Untuk matriks singular, periksa konsistensi sistem sebelum menyimpulkan pusat.', 'An algebraic center h makes f(h+u)=f(h−u) for every u. Translating to a center removes all linear terms. For a singular matrix, check consistency before claiming a center exists.'),
    tex: tex`Ah=-a,\quad f(h+u)-f(h-u)=4u^T(Ah+a)`,
    picture: b('Elips dengan pasangan titik berlawanan; parabola tanpa pusat; pasangan garis dengan banyak pusat.', 'An ellipse with opposite point pairs; a parabola with no center; parallel lines with many centers.'),
    steps: [
      s('Bandingkan pasangan berlawanan', 'Compare opposite pairs', 'Kembangkan f(h+u) dan f(h−u). Suku kuadrat serta konstanta sama; hanya suku linear berganti tanda.', 'Expand f(h+u) and f(h−u). Their quadratic and constant terms agree; only the linear part changes sign.', tex`f(h+u)=u^TAu+2(Ah+a)^Tu+f(h)`),
      s('Hilangkan bagian ganjil', 'Remove the odd part', 'Kesamaan untuk semua u memaksa Ah+a=0. Ini cara aman mencari pusat, termasuk ketika A singular.', 'Equality for every u forces Ah+a=0. This is a reliable way to find centers, including when A is singular.', tex`f(h+u)=f(h-u)\ \forall u\iff Ah=-a`),
      s('Periksa jumlah solusi', 'Check the number of solutions', 'A invertibel memberi satu pusat. A singular yang konsisten memberi h₀+ker A, jadi banyak pusat. Sistem tidak konsisten berarti tidak ada pusat.', 'Invertible A gives one center. A consistent singular system gives h₀+ker A, hence many centers. An inconsistent system gives no center.', tex`\operatorname{rank}A=\operatorname{rank}[A\mid-a]\quad\Longleftrightarrow\quad\text{a center exists}`),
      s('Jangan menebak dari dua determinan', 'Do not guess from two determinants', 'Untuk kuadrik, δ=det A dan Δ=det Ã keduanya nol belum menjamin konsistensi. Tabung parabolik y²−2x=0 tidak punya pusat meski δ=Δ=0.', 'For quadrics, δ=det A and Δ=det Ã both vanishing does not guarantee consistency. The parabolic cylinder y²−2x=0 has no center although δ=Δ=0.', tex`A=\operatorname{diag}(0,1,0),\ a=(-1,0,0)^T:\quad Ah=-a\Rightarrow0=1`),
    ], conditions: [b('Pusat di sini merujuk simetri persamaan kuadratik, bukan simetri vakum himpunan kosong. Rumus h=−A⁻¹a hanya untuk det A≠0.', 'Here a center means symmetry of the quadratic equation, rather than the vacuous symmetry of an empty set. Use h=−A⁻¹a only if det A≠0.')],
    failure: b('Menghapus suku linear dari (x−1)²+y²=4 dengan menggeser ke (0,0) gagal; titik tengah pasangan berlawanan adalah (1,0), bukan titik asal lama.', 'Trying to remove the linear term of (x−1)²+y²=4 by shifting to (0,0) fails; the midpoint of opposite pairs is (1,0), not the old origin.'),
    examplePrompt: b('Bandingkan pusat x²−1=0 dan y²−2x=0.', 'Compare the centers of x²−1=0 and y²−2x=0.'),
    exampleSteps: [
      s('Pasangan garis', 'Parallel lines', 'Untuk x²−1, A=diag(1,0) dan a=0. Persamaan pusat hanya membatasi hₓ=0; hᵧ bebas.', 'For x²−1, A=diag(1,0) and a=0. The center equation only requires hₓ=0; hᵧ is free.', tex`h=(0,t),\quad t\in\mathbb R`),
      s('Parabola', 'Parabola', 'Untuk y²−2x, A=diag(0,1) dan a=(−1,0). Baris pertama meminta 0=1; tidak ada solusi.', 'For y²−2x, A=diag(0,1) and a=(−1,0). The first row asks for 0=1; there is no solution.', tex`\begin{pmatrix}0&0\\0&1\end{pmatrix}\binom{h_x}{h_y}=\binom10\quad\text{has no solution}`),
    ], check: { question: b('Apa pusat x²+2y²−4x+8y−1=0?', 'What is the center of x²+2y²−4x+8y−1=0?'), answer: b('(2,−2), karena diag(1,2)h=−(−2,4).', '(2,−2), because diag(1,2)h=−(−2,4).') },
  }),
  geoConjugate: geometryTopic({
    visual: 'geoConjugate', title: b('Tali busur, diameter terkonjugasi dan sumbu utama (3.3)', 'Chords, conjugate diameters and principal axes (3.3)'),
    question: b('Mengapa titik tengah tali busur sejajar terletak pada satu diameter?', 'Why do the midpoints of parallel chords lie on one diameter?'),
    meaning: b('Untuk arah v, titik tengah tali busur memenuhi vᵀ(Am+a)=0. Arah w pada diameter itu memenuhi wᵀAv=0: konjugasi memakai A, sehingga umumnya berbeda dari tegak lurus Euclid.', 'For direction v, chord midpoints satisfy vᵀ(Am+a)=0. A direction w along that diameter satisfies wᵀAv=0: conjugacy uses A, so it generally differs from Euclidean perpendicularity.'),
    tex: tex`v^T(Am+a)=0,\qquad w^TAv=0`,
    picture: b('Tali busur miring pada elips; titik tengah membentuk diameter lain yang tidak tegak lurus.', 'Slanted chords of an ellipse; their midpoints form another diameter that is not perpendicular.'),
    steps: [
      s('Potong dengan satu garis', 'Intersect with a line', 'Tuliskan garis r=m+tv. Substitusi ke f memberi persamaan kuadrat dalam t.', 'Write the line as r=m+tv. Substitution into f gives a quadratic equation in t.', tex`(v^TAv)t^2+2v^T(Am+a)t+f(m)=0`),
      s('Titik tengah membuat akar berlawanan', 'A midpoint makes the roots opposite', 'Jika m titik tengah dua perpotongan, parameternya ±t. Jumlah akar nol membuat koefisien linear nol.', 'If m is the midpoint of two intersections, their parameters are ±t. Zero root sum makes the linear coefficient zero.', tex`t_1+t_2=0\Rightarrow v^T(Am+a)=0`),
      s('Kurangkan dua titik pada diameter', 'Subtract two points on the diameter', 'Selisih dua titik midpoint searah w. Karena A simetris, wᵀAv=0 juga berarti vᵀAw=0: konjugasi timbal balik.', 'The difference of two midpoints has direction w. Since A is symmetric, wᵀAv=0 also means vᵀAw=0: conjugacy is mutual.', tex`w^TAv=0\iff v^TAw=0`),
      s('Arah utama memakai eigenvector', 'Principal directions use eigenvectors', 'Diameter terkonjugasi normal terhadap Av. Agar diameter tegak lurus v, perlu Av=λv. Untuk λ≠0, diameter utama menjadi sumbu simetri; arah kernel perlu diperiksa terpisah.', 'The conjugate diameter is normal to Av. For it to be perpendicular to v, require Av=λv. If λ≠0, the principal diameter is a symmetry axis; kernel directions require a separate check.', tex`Av=\lambda v,\quad\det(A-\lambda I)=0`),
    ], conditions: [b('Gunakan dua titik potong nyata berbeda dan vᵀAv≠0 untuk argumen akar kuadrat. Persamaan diameter adalah garis/bidang pembawa; hanya bagian dengan tali busur nyata yang merupakan lokus midpoint. Jika Av=0, persamaan dapat kosong atau tidak menentukan diameter.', 'Use two distinct real intersections and vᵀAv≠0 for the quadratic-root argument. The diameter equation gives the supporting line or plane; only the portion with real chords is the midpoint locus. If Av=0, the equation may be empty or fail to define a diameter.')],
    failure: b('Pada elips x²/4+y²=1, v=(1,1) berkonjugasi dengan w=(4,−1), tetapi v·w=3≠0. Konjugasi bukan sinonim tegak lurus.', 'For x²/4+y²=1, v=(1,1) is conjugate to w=(4,−1), yet v·w=3≠0. Conjugacy does not mean perpendicularity.'),
    examplePrompt: b('Cari diameter yang membagi tali busur berarah (1,1) pada elips x²/4+y²=1.', 'Find the diameter bisecting chords with direction (1,1) on x²/4+y²=1.'),
    exampleSteps: [
      s('Baca A dan arah', 'Read A and the direction', 'Elips berpusat di asal, jadi a=0. Kalikan A dengan v=(1,1).', 'The ellipse is centered at the origin, so a=0. Multiply A by v=(1,1).', tex`A=\operatorname{diag}(1/4,1),\quad Av=(1/4,1)`),
      s('Tulis pembawa midpoint', 'Write the midpoint carrier', 'Persamaan m·Av=0 menjadi x/4+y=0. Arah (4,−1) memang berada pada garis itu dan memenuhi konjugasi.', 'The equation m·Av=0 becomes x/4+y=0. Direction (4,−1) lies along this line and satisfies conjugacy.', tex`x/4+y=0,\quad(4,-1)^TA(1,1)=1-1=0`),
    ], check: { question: b('Pada lingkaran, mengapa diameter terkonjugasi selalu tegak lurus v?', 'For a circle, why is the conjugate diameter perpendicular to v?'), answer: b('A adalah kelipatan I, sehingga wᵀAv=0 setara w·v=0.', 'A is a scalar multiple of I, so wᵀAv=0 is equivalent to w·v=0.') },
  }),
  geoConicClass: geometryTopic({
    visual: 'geoConicClass', title: b('Sembilan kelas konik dan lokus realnya (3.4)', 'Nine conic classes and their real loci (3.4)'),
    question: b('Apakah persamaan kuadrat selalu menggambar elips, hiperbola atau parabola?', 'Does a quadratic equation always draw an ellipse, hyperbola or parabola?'),
    meaning: b('Rotasi menghapus suku campuran; translasi menghapus suku linear yang bisa dihapus. Tanda kuadrat, rank dan konstanta menentukan bentuk nyata, termasuk titik, garis dan himpunan kosong. Istilah imajiner di slide tidak berarti ada kurva nyata untuk digambar.', 'Rotation removes mixed terms; translation removes whichever linear terms can be removed. Quadratic signs, rank and constants determine the real shape, including points, lines and the empty set. The word imaginary in the slides does not imply a real curve to draw.'),
    tex: tex`\lambda_1X^2+\lambda_2Y^2+2b_1X+2b_2Y+c=0`,
    picture: b('Pilih salah satu dari sembilan persamaan; gambar menampilkan lokus real yang benar.', 'Choose one of nine equations; the picture displays its actual real locus.'),
    steps: [
      s('Mulai dari bentuk kanonik', 'Start with a canonical form', 'A simetris dapat didiagonalkan secara ortogonal. Lengkapi kuadrat hanya pada arah dengan eigenvalue tidak nol.', 'A symmetric matrix can be diagonalized orthogonally. Complete squares only in directions with nonzero eigenvalues.', tex`r=QX+h,\quad Q^TAQ=\operatorname{diag}(\lambda_1,\lambda_2)`),
      s('Rank dua: tanda dan konstanta', 'Rank two: signs and constant', 'Tanda sama memberi elips nyata, kosong, atau satu titik ketika konstanta tepat nol. Tanda berbeda memberi hiperbola atau dua garis berpotongan ketika konstanta nol.', 'Equal signs give a real ellipse, empty locus, or one point when the constant is zero. Opposite signs give a hyperbola or two intersecting lines when the constant is zero.', tex`\begin{gathered}X^2/a^2+Y^2/b^2=1\ ;\ X^2+Y^2=-1\ ;\ X^2+Y^2=0\\X^2/a^2-Y^2/b^2=1\ ;\ X^2-Y^2=0\end{gathered}`),
      s('Rank satu dengan suku linear bebas', 'Rank one with a free linear term', 'Jika arah kernel masih punya suku linear, muncul parabola. Koefisien linear tersebut tidak boleh dihilangkan dengan rumus invers A.', 'If the kernel direction retains a linear term, a parabola appears. That coefficient cannot be removed using an inverse of A.', tex`Y^2=2pX,\quad p\ne0`),
      s('Rank satu tanpa suku linear bebas', 'Rank one without a free linear term', 'Persamaan X²=d memberi dua garis jika d>0, satu garis berhimpit jika d=0, dan kosong jika d<0. Ini melengkapi sembilan kelas pada slide.', 'The equation X²=d gives two lines if d>0, a double line if d=0, and an empty locus if d<0. This completes the nine slide classes.', tex`X^2=1\ ;\ X^2=0\ ;\ X^2=-1`),
    ], conditions: [b('Koefisien real, A simetris dan bagian kuadrat bukan nol. Skala positif pada koordinat menghasilkan bentuk afin yang dinormalisasi; rotasi/translasi menjaga panjang tetapi skala umum tidak.', 'Real coefficients, symmetric A and a nonzero quadratic part. Positive coordinate scales give normalized affine forms; rotations/translations preserve lengths but general scaling does not.')],
    failure: b('Diskriminan kuadrat negatif tidak memastikan elips nyata: x²+y²+1=0 kosong. x²+y²=0 hanya satu titik real walau slide menamainya dua garis imajiner berpotongan.', 'A negative quadratic discriminant does not ensure a real ellipse: x²+y²+1=0 is empty. x²+y²=0 has just one real point although the slides call it imaginary intersecting lines.'),
    examplePrompt: b('Klasifikasikan x²−y²−2x−4y−3=0.', 'Classify x²−y²−2x−4y−3=0.'),
    exampleSteps: [
      s('Lengkapi kuadrat', 'Complete squares', 'Gabungkan x²−2x dan −y²−4y dengan konstanta yang tepat.', 'Combine x²−2x and −y²−4y with the required constants.', tex`(x-1)^2-(y+2)^2=0`),
      s('Faktorkan bentuk nol', 'Factor the zero form', 'Pusat (1,−2), tetapi konstanta tereduksi nol. Maka ini dua garis berpotongan, bukan hiperbola nondegenerasi.', 'The center is (1,−2), but the reduced constant is zero. Thus these are intersecting lines, not a nondegenerate hyperbola.', tex`(x-y-3)(x+y+1)=0`),
    ], check: { question: b('Apa lokus (x−2)²+(y+1)²=0?', 'What is the locus of (x−2)²+(y+1)²=0?'), answer: b('Satu titik real (2,−1): jumlah dua kuadrat hanya nol jika keduanya nol.', 'One real point (2,−1): a sum of two squares vanishes only when both do.') },
  }),
  geoQuadricClass: geometryTopic({
    visual: 'geoQuadricClass', title: b('Tujuh belas kelas kuadrik: permukaan dan degenerasi (3.4)', 'Seventeen quadric classes: surfaces and degeneracies (3.4)'),
    question: b('Bagaimana tanda kuadrat dan irisan membantu mengenali semua kelas kuadrik?', 'How do quadratic signs and cross-sections reveal every quadric class?'),
    meaning: b('Setelah reduksi, tiga tanda kuadrat membedakan elipsoida, hiperboloida dan kerucut. Arah tanpa kuadrat dapat menjadi arah bebas tabung atau suku linear paraboloida. Beberapa kelas imajiner memiliki lokus real kosong, titik atau garis.', 'After reduction, the three quadratic signs distinguish ellipsoids, hyperboloids and cones. A direction without a quadratic term may be free in a cylinder or linear in a paraboloid. Some imaginary classes have empty, point or line real loci.'),
    tex: tex`\lambda_1X^2+\lambda_2Y^2+\lambda_3Z^2+2b^TX+c=0`,
    picture: b('Galeri 17 kelas; kawat permukaan ditampilkan dalam proyeksi miring, bukan grafik 2D.', 'Gallery of 17 classes; surface wireframes are shown in an oblique projection, not a 2D graph.'),
    steps: [
      s('Enam kelas nondegenerasi', 'Six nondegenerate classes', 'Elipsoida nyata/imajiner; hiperboloida satu/dua lembar; paraboloida eliptik/hiperbolik. Untuk dua lembar, irisan z tetap hanya ada jika |z|≥1 pada bentuk yang ditunjukkan.', 'Real/imaginary ellipsoids; one/two-sheet hyperboloids; elliptic/hyperbolic paraboloids. For two sheets, constant-z sections exist only if |z|≥1 in the displayed form.', tex`\begin{gathered}X^2+Y^2+Z^2=\pm1\\X^2+Y^2-Z^2=1\ ;\ Z^2-X^2-Y^2=1\\X^2+Y^2=2Z\ ;\ X^2-Y^2=2Z\end{gathered}`),
      s('Dua kelas kerucut', 'Two cone classes', 'Konstanta nol dan tiga kuadrat campuran tanda memberi kerucut nyata. Semua tanda sama menghasilkan hanya titik asal real, disebut kerucut imajiner pada slide.', 'Zero constant and mixed quadratic signs give a real cone. Equal signs yield only the real origin, called an imaginary cone in the slides.', tex`X^2+Y^2-Z^2=0\ ;\ X^2+Y^2+Z^2=0`),
      s('Empat kelas tabung', 'Four cylinder classes', 'Tidak adanya Z membuat setiap titik potong bidang XY dapat digeser bebas sejajar sumbu Z. Ada tabung eliptik, hiperbolik, parabolik dan imajiner.', 'Absence of Z means every point of the XY section can move freely parallel to Z. The classes are elliptic, hyperbolic, parabolic and imaginary cylinders.', tex`\begin{gathered}X^2+Y^2=1\ ;\ X^2-Y^2=1\\Y^2=2X\ ;\ X^2+Y^2=-1\end{gathered}`),
      s('Lima kelas pasangan bidang', 'Five plane-pair classes', 'Bidang berpotongan nyata/imajiner, bidang sejajar nyata/imajiner, dan bidang berhimpit melengkapi 17 kelas. X²+Y²=0 berarti sumbu Z dalam koordinat real.', 'Real/imaginary intersecting planes, real/imaginary parallel planes, and a double plane complete the 17 classes. X²+Y²=0 means the Z axis over the reals.', tex`X^2-Y^2=0\ ;\ X^2+Y^2=0\ ;\ X^2=1\ ;\ X^2=-1\ ;\ X^2=0`),
    ], conditions: [b('Klasifikasi dilakukan atas persamaan kuadratik real nonnol, setelah rotasi/translasi dan normalisasi skala. Periksa rank serta suku linear pada kernel; tanda tiga eigenvalue saja belum cukup.', 'Classify a nonzero real quadratic equation after rotation/translation and scale normalization. Check rank and linear terms along the kernel; three eigenvalue signs alone do not suffice.')],
    failure: b('x²+y²−z²=0 adalah kerucut, bukan hiperboloida. x²+y²=1 adalah tabung tak terbatas, bukan elipsoida; z sama sekali tidak dibatasi.', 'x²+y²−z²=0 is a cone, not a hyperboloid. x²+y²=1 is an unbounded cylinder, not an ellipsoid; z is unrestricted.'),
    examplePrompt: b('Bedakan x²+y²−z²=1 dan z²−x²−y²=1 menggunakan irisan.', 'Distinguish x²+y²−z²=1 and z²−x²−y²=1 using sections.'),
    exampleSteps: [
      s('Satu lembar: semua tinggi', 'One sheet: every height', 'Pada z=t, jari-jari irisan √(1+t²) selalu positif. Permukaan tersambung melalui lingkaran pinggang z=0.', 'At z=t, the section radius √(1+t²) is always positive. The surface connects through the waist circle at z=0.', tex`x^2+y^2=1+t^2`),
      s('Dua lembar: celah di tengah', 'Two sheets: a middle gap', 'Pada z=t, radius²=t²−1. Tidak ada titik untuk −1<t<1; bagian atas dan bawah terpisah.', 'At z=t, radius squared is t²−1. There are no points for −1<t<1; the upper and lower sheets are separate.', tex`x^2+y^2=t^2-1\ge0\iff |t|\ge1`),
    ], check: { question: b('Apa bentuk x²−y²−2z=0, dan irisan z=0?', 'What is x²−y²−2z=0, and its section at z=0?'), answer: b('Paraboloida hiperbolik (pelana). Irisan z=0 adalah dua garis x=±y.', 'A hyperbolic paraboloid (saddle). Its z=0 section is the pair x=±y.') },
  }),
  geoInvariants: geometryTopic({
    visual: 'geoInvariants', title: b('Determinan, degenerasi dan perubahan bingkai (3.4)', 'Determinants, degeneracy and frame changes (3.4)'),
    question: b('Mengapa dua determinan membantu klasifikasi, tetapi nilai angkanya bukan invarian afin?', 'Why do two determinants help classification while their numerical values are not affine invariants?'),
    meaning: b('δ=det A memeriksa bagian kuadrat; Δ=det Ã memeriksa bentuk homogen lengkap. Di bawah perubahan koordinat invertibel, keduanya dikalikan kuadrat det S. Kenolannya tetap, tetapi nilai angkanya umumnya berubah.', 'δ=det A checks the quadratic part; Δ=det Ã checks the full homogenized form. Under an invertible coordinate change, both are multiplied by the square of det S. Their vanishing is preserved, but their numerical values usually change.'),
    tex: tex`\widetilde A=\begin{pmatrix}A&a\\a^T&\alpha\end{pmatrix},\quad\delta=\det A,\quad\Delta=\det\widetilde A`,
    picture: b('Elips yang sama pada dua bingkai; determinan berubah oleh faktor positif.', 'The same ellipse in two frames; determinants change by a positive factor.'),
    steps: [
      s('Homogenkan dengan koordinat 1', 'Homogenize with coordinate 1', 'Tambahkan koordinat terakhir 1 sehingga konstanta dan suku linear masuk satu matriks simetris.', 'Append a final coordinate 1 so that constants and linear terms belong to one symmetric matrix.', tex`f(r)=\chi^T\widetilde A\chi,\quad\chi=(r,1)^T`),
      s('Ubah koordinat, bukan titik geometri', 'Change coordinates, not geometric points', 'Untuk r=Su+h, S invertibel, matriks homogen berubah melalui kongruensi HᵀÃH, bukan kemiripan S⁻¹AS.', 'For r=Su+h with invertible S, the homogeneous matrix changes by congruence HᵀÃH, not similarity S⁻¹AS.', tex`H=\begin{pmatrix}S&h\\0&1\end{pmatrix},\quad\widetilde A'=H^T\widetilde AH,\quad A'=S^TAS`),
      s('Ambil determinan', 'Take determinants', 'Karena det H=det S, kedua determinan dikali faktor positif (det S)². Nilai nol/tak nol tetap; tanda tetap untuk persamaan dengan skala yang dipertahankan.', 'Since det H=det S, both determinants gain the positive factor (det S)². Zero/nonzero status is preserved; signs are preserved when the equation scale is retained.', tex`\delta'=(\det S)^2\delta,\quad\Delta'=(\det S)^2\Delta`),
      s('Gunakan klasifikasi dengan uji real', 'Classify with a reality check', 'Δ≠0 berarti bentuk homogen nondegenerasi. Untuk konik nondegenerasi, δ>0 memberi tipe elips (nyata atau imajiner), δ<0 hiperbola, δ=0 parabola. Uji konstanta diperlukan untuk elips nyata.', 'Δ≠0 means the homogeneous form is nondegenerate. For nondegenerate conics, δ>0 gives ellipse type (real or imaginary), δ<0 a hyperbola, δ=0 a parabola. Check the reduced constant to decide if an ellipse is real.', tex`\Delta\ne0:\quad\delta>0\Rightarrow\text{ellipse type},\ \delta<0\Rightarrow\text{hyperbola},\ \delta=0\Rightarrow\text{parabola}`),
    ], conditions: [b('S invertibel. Ini invarian terhadap perubahan koordinat; mengalikan seluruh persamaan dengan c≠0 mengubah det A oleh cⁿ dan det Ã oleh cⁿ⁺¹. Tanda Δ konik dapat berbalik saat c<0, sedangkan tanda Δ kuadrik tidak.', 'S must be invertible. These are invariants under coordinate changes; multiplying the whole equation by c≠0 multiplies det A by cⁿ and det Ã by cⁿ⁺¹. The sign of a conic Δ can reverse for c<0, whereas a quadric Δ does not.')],
    failure: b('Δ≠0 tidak berarti ada titik real: x²+y²+1=0 mempunyai Δ=1, namun lokus realnya kosong. δ=0 juga tidak berarti parabola tanpa syarat Δ≠0.', 'Δ≠0 does not imply real points exist: x²+y²+1=0 has Δ=1 but an empty real locus. δ=0 also does not imply a parabola unless Δ≠0.'),
    examplePrompt: b('Ubah x²/4+y²−1=0 dengan x=2u, y=v.', 'Change x²/4+y²−1=0 using x=2u, y=v.'),
    exampleSteps: [
      s('Hitung sebelum perubahan', 'Compute before the change', 'A=diag(1/4,1) dan Ã=diag(1/4,1,−1).', 'A=diag(1/4,1) and Ã=diag(1/4,1,−1).', tex`\delta=1/4,\quad\Delta=-1/4`),
      s('Hitung faktor skala', 'Compute the scale factor', 'det S=2, jadi faktor4. Persamaan menjadi u²+v²−1=0, dengan δ′=1, Δ′=−1; jenisnya tetap.', 'det S=2, so the factor is4. The equation becomes u²+v²−1=0, with δ′=1 and Δ′=−1; the type is preserved.', tex`S=\operatorname{diag}(2,1),\quad\delta'=4\delta=1,\quad\Delta'=4\Delta=-1`),
    ], check: { question: b('Mengapa 2x²+2y²+2=0 masih kosong?', 'Why is 2x²+2y²+2=0 still empty?'), answer: b('Mengalikan persamaan dengan 2 tidak mengubah titik solusinya; jangan klasifikasikan dari besar determinan saja.', 'Multiplying an equation by2 does not change its solution set; do not classify by determinant magnitude alone.') },
  }),
  geoComposition: geometryTopic({
    visual: 'geoComposition', title: b('Transformasi, invers, komposisi dan grup (4.1)', 'Transformations, inverses, composition and groups (4.1)'),
    question: b('Mengapa menggeser lalu memutar berbeda dari memutar lalu menggeser?', 'Why does translating then rotating differ from rotating then translating?'),
    meaning: b('Transformasi geometris pada slide adalah bijeksi antara himpunan titik. Invers membalik korespondensi; komposisi dibaca dari kanan ke kiri. Transformasi afin invertibel pada ruang yang sama membentuk grup.', 'A geometric transformation in these slides is a bijection between point sets. The inverse reverses correspondence; composition is read right to left. Invertible affine transformations of the same space form a group.'),
    tex: tex`\psi\circ\phi(r)=BA r+Bb+c\quad[\phi(r)=Ar+b,\ \psi(r)=Br+c]`,
    picture: b('Titik yang sama melalui dua jalur: translasi→rotasi dan rotasi→translasi.', 'The same point follows two paths: translation→rotation and rotation→translation.'),
    steps: [
      s('Pastikan ada invers', 'Make sure an inverse exists', 'Setiap titik asal punya tepat satu peta, peta berbeda tidak menyatu, dan setiap titik target dicapai. Untuk r↦Ar+b, det A≠0 memberi bijeksi.', 'Every source point has exactly one image, distinct points stay distinct, and every target point is reached. For r↦Ar+b, det A≠0 gives a bijection.', tex`\phi^{-1}(s)=A^{-1}(s-b)`),
      s('Substitusi menentukan urutan', 'Substitution fixes the order', 'Pada ψ∘φ, terapkan φ lebih dahulu. Karena B juga bekerja pada b, komposisinya tidak cukup menjumlahkan translasi.', 'For ψ∘φ, apply φ first. Since B also acts on b, composition cannot merely add translations.', tex`\psi(\phi(r))=B(Ar+b)+c=BA r+Bb+c`),
      s('Asosiatif tetapi tidak komutatif', 'Associative but not commutative', 'Pengelompokan tiga komposisi tidak mengubah hasil, tetapi menukar urutan umumnya mengubah hasil.', 'Grouping three compositions does not change the result, but swapping their order generally does.', tex`(\chi\circ\psi)\circ\phi=\chi\circ(\psi\circ\phi),\quad\psi\circ\phi\ne\phi\circ\psi\ \text{in general}`),
      s('Hubungkan dengan grup', 'Connect with groups', 'Pada ruang yang sama, keluarga afin invertibel tertutup terhadap komposisi dan invers. Identitas serta sifat asosiatif melengkapi aksioma grup.', 'On one space, invertible affine maps are closed under composition and inverses. Identity and associativity complete the group axioms.', tex`\phi^{-1}\circ\phi=\mathrm{id}_{\mathcal F},\quad\phi\circ\phi^{-1}=\mathrm{id}_{\mathcal F'}`),
    ], conditions: [b('Domain komposisi harus cocok. Transformasi bijektif dari ℱ ke ℱ′ tidak harus sebuah anggota grup pada satu himpunan jika ℱ≠ℱ′. Peta afin singular bukan transformasi invertibel.', 'Composition domains must match. A bijection from ℱ to ℱ′ need not belong to a group on one set when ℱ≠ℱ′. A singular affine map is not invertible.')],
    failure: b('Peta (x,y)↦(x,0) meruntuhkan banyak titik ke satu titik dan tidak punya invers pada bidang. Ia peta afin, tetapi bukan anggota grup afin invertibel.', 'The map (x,y)↦(x,0) collapses many points into one and has no inverse on the plane. It is an affine map, but not a member of the invertible affine group.'),
    examplePrompt: b('P=(1,0), translasi T oleh (1,0), rotasi R sebesar90°: bandingkan R∘T dan T∘R.', 'P=(1,0), translation T by (1,0), rotation R by90°: compare R∘T and T∘R.'),
    exampleSteps: [
      s('Geser lalu putar', 'Translate then rotate', 'T(P)=(2,0); rotasi90° berlawanan jarum jam memberi (0,2).', 'T(P)=(2,0); a90° counterclockwise rotation gives (0,2).', tex`(R\circ T)(1,0)=R(2,0)=(0,2)`),
      s('Putar lalu geser', 'Rotate then translate', 'R(P)=(0,1); translasi memberi (1,1). Dua hasil berbeda membuktikan ketidakkomutatifan.', 'R(P)=(0,1); translation gives (1,1). The distinct results prove noncommutativity.', tex`(T\circ R)(1,0)=T(0,1)=(1,1)\ne(0,2)`),
    ], check: { question: b('Apa invers φ(x,y)=(2x+1,3y−2)?', 'What is the inverse of φ(x,y)=(2x+1,3y−2)?'), answer: b('φ⁻¹(u,v)=((u−1)/2,(v+2)/3).', 'φ⁻¹(u,v)=((u−1)/2,(v+2)/3).') },
  }),
  geoAffineFrame: geometryTopic({
    visual: 'geoAffineFrame', title: b('Menentukan peta afin dari bingkai dan orientasi (4.2)', 'Recovering affine maps from frames and orientation (4.2)'),
    question: b('Mengapa tiga titik tak segaris cukup menentukan satu transformasi afin bidang?', 'Why do three noncollinear points determine one planar affine transformation?'),
    meaning: b('Asal menentukan translasi b; peta dua vektor basis menentukan dua kolom A. Di ruang3D perlu empat titik tak sebidang. Determinan A mengukur faktor volume bertanda, bukan sekadar invertibilitas.', 'The origin determines translation b; images of two basis vectors determine the two columns of A. In3D, four noncoplanar points are needed. det A measures the signed volume factor, not just invertibility.'),
    tex: tex`A=[P'_1-P'_0\ \cdots\ P'_n-P'_0]\,[P_1-P_0\ \cdots\ P_n-P_0]^{-1},\quad b=P'_0-AP_0`,
    picture: b('Segitiga asal dan bayangannya; panah basis menentukan kolom matriks.', 'A source triangle and its image; basis arrows determine matrix columns.'),
    steps: [
      s('Gunakan bingkai independen', 'Use an independent frame', 'Selisih Pᵢ−P₀ harus membentuk basis. Di bidang, ini sama dengan tiga titik tak segaris.', 'The differences Pᵢ−P₀ must form a basis. In the plane, this means three noncollinear points.', tex`E=[P_1-P_0\ \cdots\ P_n-P_0],\quad\det E\ne0`),
      s('Kirim vektor basis', 'Map the basis vectors', 'Translasi hilang ketika dua peta titik dikurangkan. Karena AE=E′, satu-satunya kemungkinan adalah A=E′E⁻¹.', 'Translation disappears when two point images are subtracted. Since AE=E′, the only possible matrix is A=E′E⁻¹.', tex`P_i'-P_0'=A(P_i-P_0),\quad A=E'E^{-1}`),
      s('Pulihkan translasi', 'Recover the translation', 'Substitusi P₀ untuk mendapat b. Agar peta bijektif, bingkai target juga harus independen.', 'Substitute P₀ to obtain b. For the map to be bijective, the target frame must also be independent.', tex`b=P_0'-AP_0,\quad\det E'\ne0\Rightarrow\det A\ne0`),
      s('Baca orientasi dan volume', 'Read orientation and volume', 'Volume bertanda dikali det A, volume biasa dikali |det A|. Pergantian basis S membuat matriks operator S⁻¹AS, dengan determinan yang sama.', 'Signed volume is multiplied by det A; ordinary volume by |det A|. A basis change S gives the operator matrix S⁻¹AS with the same determinant.', tex`V'=\det(A)V,\quad\widetilde A=S^{-1}AS,\quad\det\widetilde A=\det A`),
    ], conditions: [b('Bingkai sumber dan target independen. Koordinat menggunakan konvensi vektor kolom. Perubahan matriks operator adalah kemiripan; perubahan matriks bentuk kuadrat pada topik sebelumnya adalah kongruensi.', 'Source and target frames must be independent. Coordinates use column vectors. Operator matrices change by similarity; quadratic-form matrices in the previous topic change by congruence.')],
    failure: b('Tiga titik segaris tidak cukup menentukan peta afin bidang: kolom yang bekerja pada arah melintang masih bebas.', 'Three collinear points do not determine a planar affine map: its action in the transverse direction is still free.'),
    examplePrompt: b('Peta (0,0)↦(1,1), (1,0)↦(−1,1), (0,1)↦(1,−1). Tentukan persamaannya.', 'Map (0,0)↦(1,1), (1,0)↦(−1,1), (0,1)↦(1,−1). Find its equation.'),
    exampleSteps: [
      s('Asal memberi b', 'The origin gives b', 'Karena A·0=0, peta titik asal langsung menghasilkan b=(1,1).', 'Since A·0=0, the image of the origin directly gives b=(1,1).', tex`b=\binom11`),
      s('Selisih memberi kolom', 'Differences give the columns', 'Kurangi b dari peta (1,0) dan (0,1). Matriks adalah−2I; luas dikali4 dan orientasi bidang tetap.', 'Subtract b from the images of (1,0) and (0,1). The matrix is−2I; area is multiplied by4 and planar orientation is preserved.', tex`A=\begin{pmatrix}-2&0\\0&-2\end{pmatrix},\quad\phi(x,y)=(-2x+1,-2y+1),\quad\det A=4`),
    ], check: { question: b('Apakah det A=1 menjamin panjang terjaga?', 'Does det A=1 guarantee lengths are preserved?'), answer: b('Tidak. A=diag(2,1/2) menjaga luas dan orientasi, tetapi mengubah panjang.', 'No. A=diag(2,1/2) preserves area and orientation, but changes lengths.') },
  }),
  geoSimilarity: geometryTopic({
    visual: 'geoSimilarity', title: b('Homoteti, keserupaan dan faktor skala (4.2–4.3)', 'Homothety, similarity and scale factors (4.2–4.3)'),
    question: b('Apa yang tetap ketika semua panjang diperbesar dengan faktor yang sama?', 'What stays the same when all lengths are enlarged by one factor?'),
    meaning: b('Homoteti berpusat c memetakan r ke c+k(r−c), k≠0. Keserupaan menggabungkan isometri dengan skala seragam; sudut tetap, panjang dikali |k|, luas dikali k² dan volume dikali |k|³.', 'A homothety centered at c maps r to c+k(r−c), k≠0. A similarity combines an isometry with uniform scaling; angles stay fixed, lengths gain |k|, areas k² and volumes |k|³.'),
    tex: tex`r'=c+k(r-c),\quad\phi(r)=kQr+b,\quad Q^TQ=I`,
    picture: b('Segitiga dan bayangannya terhadap pusat tetap; slider k melewati faktor positif dan negatif.', 'A triangle and its image about a fixed center; the k slider includes positive and negative factors.'),
    steps: [
      s('Skalakan relatif pusat', 'Scale relative to the center', 'Kurangi pusat sebelum mengalikan k, lalu tambahkan pusat kembali. k<0 juga membalik arah setiap vektor radius.', 'Subtract the center before multiplying by k, then add the center back. A negative k also reverses each radius vector.', tex`\phi(r)=c+k(r-c)=kr+(1-k)c`),
      s('Hitung perubahan panjang', 'Compute the length change', 'Selisih dua peta titik adalah k kali selisih asal. Karena norm menggunakan nilai mutlak, faktor panjangnya |k|.', 'The difference of two image points is k times the original difference. Norms use the absolute value, so the length factor is |k|.', tex`\|\phi(p)-\phi(q)\|=|k|\|p-q\|`),
      s('Sudut dan orientasi bukan hal yang sama', 'Angles and orientation are different', 'Skala seragam mempertahankan sudut. det(kI)=kⁿ: homoteti negatif tetap menjaga orientasi bidang, tetapi membalik orientasi ruang3D.', 'Uniform scaling preserves angles. det(kI)=kⁿ: a negative homothety preserves planar orientation but reverses3D orientation.', tex`\cos\theta'=\frac{k^2u\cdot v}{|k|^2\|u\|\|v\|}=\cos\theta,\quad\det(kI)=k^n`),
      s('Gabungkan dengan isometri', 'Combine with an isometry', 'Q ortogonal menjaga panjang; kQ mengubah semuanya dengan faktor seragam. Homoteti merupakan isometri tepat ketika |k|=1, termasuk k=−1.', 'Orthogonal Q preserves lengths; kQ changes all lengths uniformly. A homothety is an isometry exactly when |k|=1, including k=−1.', tex`(kQ)^T(kQ)=k^2I,\quad H_{c,k}\circ H_{c,l}=H_{c,kl}`),
    ], conditions: [b('k≠0 agar bijektif. Komposisi rasio sederhana kl memerlukan pusat homoteti yang sama. Skala berbeda per arah bukan keserupaan umum.', 'k≠0 is needed for bijectivity. The simple ratio product kl requires a common homothety center. Different scales in different directions do not generally give a similarity.')],
    failure: b('diag(2,1) mengubah sudut antara (1,1) dan (1,−1): semula90°, sesudahnya bukan90°. Sebaliknya, k=−1 tetap isometri meski rasio berbeda dari1.', 'diag(2,1) changes the angle between (1,1) and (1,−1): originally90°, afterwards not90°. Conversely, k=−1 is an isometry despite its ratio differing from1.'),
    examplePrompt: b('Pusat c=(1,1), k=−2: peta P=(2,1), panjang dan luas?', 'With c=(1,1), k=−2, find the image of P=(2,1), and the length and area factors.'),
    exampleSteps: [
      s('Gunakan vektor radius', 'Use the radius vector', 'P−c=(1,0), sehingga peta berada pada sisi berlawanan pusat.', 'P−c=(1,0), so its image lies on the opposite side of the center.', tex`P'=c-2(P-c)=(-1,1)`),
      s('Baca faktor metrik', 'Read the metric factors', 'Panjang dikali2, luas dikali4; det(−2I)=4 positif dalam bidang, jadi orientasi tetap.', 'Lengths are multiplied by2 and areas by4; det(−2I)=4 is positive in the plane, so orientation is preserved.', tex`L'=2L,\quad S'=4S,\quad\det(-2I_2)=4`),
    ], check: { question: b('Apakah k=0 punya invers? Apakah k=−1 menjaga panjang?', 'Does k=0 have an inverse? Does k=−1 preserve lengths?'), answer: b('k=0 meruntuhkan semua titik ke pusat, jadi tidak. k=−1 menjaga panjang karena |k|=1.', 'k=0 collapses every point to the center, so no. k=−1 preserves lengths because |k|=1.') },
  }),
  geoMotions: geometryTopic({
    visual: 'geoMotions', title: b('Rotasi, refleksi, gerak spiral dan orientasi (4.3)', 'Rotations, reflections, screw motions and orientation (4.3)'),
    question: b('Bagaimana mengenali gerakan langsung dan tak langsung dari matriksnya?', 'How can a matrix distinguish direct and indirect motions?'),
    meaning: b('Isometri r↦Qr+b memakai Q ortogonal. det Q=+1 disebut langsung; det Q=−1 tak langsung. Rotasi3D yang menjaga orientasi dan punya titik tetap memiliki sumbu. Rotasi diikuti translasi sejajar sumbu menghasilkan gerak spiral.', 'An isometry r↦Qr+b uses orthogonal Q. det Q=+1 is direct; det Q=−1 is indirect. An orientation-preserving3D rotation with a fixed point has an axis. Rotation followed by a translation parallel to its axis produces a screw motion.'),
    tex: tex`Q^TQ=I,\quad\det Q=\pm1,\quad R_\theta=\begin{pmatrix}\cos\theta&-\sin\theta\\\sin\theta&\cos\theta\end{pmatrix}`,
    picture: b('Rotasi bidang, refleksi garis, lalu jejak spiral di sekitar sumbu z.', 'A planar rotation, a line reflection, then a screw trajectory around the z axis.'),
    steps: [
      s('Rotasi menjaga orientasi', 'Rotation preserves orientation', 'Kolom Rθ adalah basis ortonormal berorientasi sama. Untuk pusat c, putar r−c lalu tambahkan c kembali. Dalam ruang, rotasi sumbu z tidak mengubah z.', 'Columns of Rθ form an orthonormal basis with the same orientation. Around c, rotate r−c then add c back. In space, a z-axis rotation leaves z unchanged.', tex`r'=c+R_\theta(r-c),\quad(x',y',z')=(x\cos\theta-y\sin\theta,x\sin\theta+y\cos\theta,z)`),
      s('Refleksi membalik satu arah normal', 'Reflection reverses one normal direction', 'Untuk bidang n·r=d, gunakan n unit. Refleksi menghapus dua kali jarak bertanda pada normal. Matriks Q=I−2nnᵀ punya satu eigenvalue−1 dan sisanya+1.', 'For a plane n·r=d, use a unit n. Reflection subtracts twice the signed normal distance. Q=I−2nnᵀ has one eigenvalue−1 and the others+1.', tex`r'=r-2(n\cdot r-d)n,\quad Q=I-2nn^T,\quad Q^2=I,\quad\det Q=-1`),
      s('Pusat simetri perlu melihat dimensi', 'Central symmetry depends on dimension', 'Simetri pusat c adalah r′=2c−r dengan Q=−I. Di bidang det Q=+1 (rotasi180°); di ruang3D det Q=−1. Jadi tidak semua jenis simetri selalu tak langsung.', 'Central symmetry at c is r′=2c−r with Q=−I. In2D det Q=+1 (a180° rotation); in3D det Q=−1. Thus not every symmetry type is always indirect.', tex`\det(-I_n)=(-1)^n`),
      s('Tambahkan translasi sepanjang sumbu', 'Add translation along the axis', 'Gerak spiral memakai rotasi XY dan z′=z+h. Jika h≠0, tidak ada titik tetap meski garis sumbunya dipetakan ke dirinya. Komposisi dua refleksi garis berpotongan memberi rotasi dua kali sudut garis.', 'A screw motion uses an XY rotation and z′=z+h. If h≠0, it has no fixed points although the axis maps to itself. Two reflections in intersecting lines compose to a rotation through twice their angle.', tex`(x',y',z')=(R_\theta(x,y),z+h),\quad S_\beta S_\alpha=R_{2(\beta-\alpha)}`),
    ], conditions: [b('Gunakan bingkai ortonormal. Rumus refleksi memerlukan n unit (atau bagi oleh n·n). Sumbu tetap bagi rotasi ruang dengan titik tetap memerlukan det Q=+1. Gerak spiral tetap isometri.', 'Use orthonormal coordinates. The reflection formula requires a unit n (or divide by n·n). A fixed axis for a spatial rotation with a fixed point requires det Q=+1. Screw motions remain isometries.')],
    failure: b('Peta (x,y)↦(−x,−y) bukan refleksi garis: ia rotasi180° dan menjaga orientasi bidang. det Q=+1 juga tidak memastikan titik tetap, misalnya translasi tak nol.', 'The map (x,y)↦(−x,−y) is not a line reflection: it is a180° rotation preserving planar orientation. det Q=+1 does not ensure fixed points either, as a nonzero translation shows.'),
    examplePrompt: b('Putar P=(1,0,2) sebesar90° sekitar sumbu z, lalu geser h=3 sepanjang sumbu.', 'Rotate P=(1,0,2) by90° about z, then translate h=3 along the axis.'),
    exampleSteps: [
      s('Putar komponen XY', 'Rotate the XY components', 'Rotasi90° mengirim (1,0) ke (0,1) tanpa mengubah tinggi2.', 'A90° rotation sends (1,0) to (0,1) without changing height2.', tex`R_{\pi/2}(1,0)=(0,1)`),
      s('Tambahkan perpindahan sumbu', 'Add the axial displacement', 'Tambahkan3 pada z. Semua jarak tetap, tetapi tidak ada titik tetap karena z selalu bertambah3.', 'Add3 to z. All distances are preserved, but no point is fixed since z always increases by3.', tex`P'=(0,1,5),\quad\det Q=1`),
    ], check: { question: b('Apa peta (2,3) oleh refleksi y=1?', 'What is the image of (2,3) under reflection in y=1?'), answer: b('(2,−1), sebab koordinat y dipetakan ke2−y. Refleksi kedua mengembalikan (2,3).', '(2,−1), because y maps to2−y. A second reflection returns (2,3).') },
  }),
  geoInversion: geometryTopic({
    visual: 'geoInversion', title: b('Inversi: jarak radial, garis ke lingkaran dan sudut (4.3)', 'Inversion: radial distances, lines to circles and angles (4.3)'),
    question: b('Mengapa inversi mempertahankan sudut tetapi tidak jarak?', 'Why does inversion preserve angles but not distances?'),
    meaning: b('Inversi berkutub O memetakan r≠0 ke kr/‖r‖², k≠0. Jarak bertanda sepanjang satu garis radial mempunyai hasil kali k. Inversi merupakan invers dirinya, tetapi bukan transformasi afin atau isometri umum.', 'Inversion about O sends r≠0 to kr/‖r‖², k≠0. Signed distances on a radial line have product k. Inversion is its own inverse, but is not generally affine or an isometry.'),
    tex: tex`I_k(r)=\frac{kr}{\|r\|^2},\quad r\ne0,\quad k\ne0`,
    picture: b('Titik pada satu sinar berubah radial; sebuah garis tidak melalui kutub menjadi lingkaran berlubang di kutub.', 'Points change radially; a line avoiding the pole becomes a circle with the pole excluded.'),
    steps: [
      s('Jaga arah radial dan hasil kali', 'Keep radial direction and the product', 'Jika k>0, peta pada sinar sama; jika k<0, pada sinar berlawanan. Panjang radial berubah dari ρ ke |k|/ρ.', 'If k>0, the image lies on the same ray; if k<0, on the opposite ray. Radial distance changes from ρ to |k|/ρ.', tex`\rho'=|k|/\rho,\quad I_k(I_k(r))=r`),
      s('Periksa titik tetap', 'Check fixed points', 'r′=r meminta ‖r‖²=k. Jadi untuk k>0, lingkaran/bola radius√k tetap titik demi titik. Untuk k<0 tidak ada titik tetap; radius√|k| dipetakan ke dirinya sebagai himpunan, dengan titik antipodal.', 'r′=r requires ‖r‖²=k. Thus for k>0, the circle/sphere of radius√k is fixed pointwise. For k<0 there are no fixed points; the radius√|k| sphere is preserved as a set, with antipodal points exchanged.', tex`I_k(r)=r\iff\|r\|^2=k`),
      s('Ubah garis ke lingkaran', 'Change a line into a circle', 'Untuk garis n·r=d dengan d≠0, substitusi r=kr′/‖r′‖². Hasilnya lingkaran berpusat kn/(2d) dengan radius |k|‖n‖/(2|d|). Kutub dikecualikan dari peta.', 'For a line n·r=d with d≠0, substitute r=kr′/‖r′‖². The result is a circle centered at kn/(2d) with radius |k|‖n‖/(2|d|). The pole is excluded from the image.', tex`d\|r'\|^2-kn\cdot r'=0\iff\left\|r'-\frac{k n}{2d}\right\|^2=\frac{k^2\|n\|^2}{4d^2}`),
      s('Mengapa sudut tetap?', 'Why do angles stay the same?', 'Turunan lokal adalah faktor skala k/‖r‖² dikali refleksi I−2uuᵀ, u=r/‖r‖. Refleksi menjaga sudut dan skala seragam juga; faktor berubah menurut posisi, jadi panjang global tidak tetap.', 'The local derivative is the scale factor k/‖r‖² times reflection I−2uuᵀ, with u=r/‖r‖. Reflection and uniform scale preserve angles; the factor varies with position, so global lengths do not stay fixed.', tex`DI_k(r)=\frac{k}{\|r\|^2}(I-2uu^T),\quad u=r/\|r\|`),
    ], conditions: [b('Kutub bukan anggota domain; k≠0. Sudut yang dipertahankan adalah sudut antara kurva/permukaan reguler pada titik kontak yang bukan kutub. Pada pusat lain, kurangi O sebelum inversi dan tambahkan O kembali.', 'The pole is outside the domain; k≠0. Preserved angles are those between regular curves/surfaces at a contact point other than the pole. For another center, subtract O before inversion and add O back.')],
    failure: b('Untuk k=4, titik radialρ=1 danρ=2 berubah menjadiρ′=4 danρ′=2: jarak semula1 menjadi2. Konformal tidak sama dengan isometri.', 'For k=4, radial pointsρ=1 andρ=2 map toρ′=4 andρ′=2: their original distance1 becomes2. Conformal does not mean isometric.'),
    examplePrompt: b('Dengan k=4, cari peta (1,0) dan peta garis x=1.', 'For k=4, find the image of (1,0) and of the line x=1.'),
    exampleSteps: [
      s('Inversi satu titik', 'Invert a point', '‖(1,0)‖²=1, sehingga hasilnya (4,0).', '‖(1,0)‖²=1, so its image is (4,0).', tex`I_4(1,0)=(4,0)`),
      s('Inversi seluruh garis', 'Invert the whole line', 'Gunakan n=(1,0), d=1. Peta adalah lingkaran pusat (2,0), radius2, dengan titik (0,0) dikecualikan; tidak ada prapeta hingga untuk kutub.', 'Use n=(1,0), d=1. The image is the circle centered at (2,0), radius2, with (0,0) excluded; the pole has no finite preimage.', tex`x'^2+y'^2=4x'\iff(x'-2)^2+y'^2=4,\quad(x',y')\ne(0,0)`),
    ], check: { question: b('Untuk k=−4, adakah titik tetap? Bola radius berapa dipertahankan sebagai himpunan?', 'For k=−4, are there fixed points? Which sphere radius is preserved as a set?'), answer: b('Tidak ada titik tetap. Lingkaran/bola radius2 dipertahankan, dengan setiap titik ditukar ke antipodalnya.', 'There are no fixed points. The radius2 circle/sphere is preserved, with each point exchanged for its antipode.') },
  }),
}

export const CLASSIFICATION_SECTIONS: GeometrySection[] = [
  { title: b('Teori umum dan klasifikasi konik/kuadrik (3.3–3.4)', 'General theory and classification of conics/quadrics (3.3–3.4)'), order: ['geoTangent', 'geoCenter', 'geoConjugate', 'eigen', 'reduce', 'geoConicClass', 'geoQuadricClass', 'geoInvariants'] },
  { title: b('Transformasi geometri (Bab4)', 'Geometric transformations (Chapter4)'), order: ['geoComposition', 'affine', 'geoAffineFrame', 'geoSimilarity', 'isometry', 'geoMotions', 'geoInversion'] },
]
export const CLASSIFICATION_DECKS: GeometryDeck[] = [
  { file: '3.3 Teori Umum Konik dan Kuadrik (Bagian 2) - 20240505.pdf', title: b('3.3 Teori umum konik dan kuadrik: bagian2', '3.3 General conic and quadric theory: part2'), topics: ['geoTangent', 'geoCenter', 'geoConjugate', 'eigen'] },
  { file: '3.4 Klasifikasi Konik dan Kuadrik (Bagian 1).pdf', title: b('3.4 Klasifikasi: bagian1', '3.4 Classification: part1'), topics: ['eigen', 'reduce', 'geoConicClass', 'geoQuadricClass', 'geoInvariants'] },
  { file: '3.4 Klasifikasi Konik dan Kuadrik (Bagian 2).pdf', title: b('3.4 Klasifikasi: bagian2', '3.4 Classification: part2'), topics: ['eigen', 'reduce', 'geoConicClass', 'geoQuadricClass', 'geoInvariants'] },
  { file: '4.1 Transformasi Geometri (Bagian 1).pdf', title: b('4.1–4.2 Transformasi dan afin', '4.1–4.2 Transformations and affine maps'), topics: ['geoComposition', 'affine', 'geoAffineFrame', 'geoSimilarity'] },
  { file: '4.3 Transformasi Geometri.pdf', title: b('4.3 Isometri dan inversi', '4.3 Isometries and inversion'), topics: ['isometry', 'geoMotions', 'geoSimilarity', 'geoInversion'] },
]
export const CLASSIFICATION_PRACTICE: Partial<Record<VisualKind, GeometryExercise[]>> = {
  geoTangent: [exercise('Turunkan selubung garis singgung sejajar v memakai diskriminan perpotongan r+tv.', 'Derive the locus of tangent lines parallel to v using the discriminant of r+tv.', 'Substitusi memberi (vᵀAv)t²+2B(r,v)t+f(r)=0, B(r,v)=vᵀ(Ar+a). Akar ganda memberi B²−(vᵀAv)f(r)=0. Butuh vᵀAv≠0 dan titik kontak reguler; arah asimptotik perlu pemeriksaan terpisah.', 'Substitution gives (vᵀAv)t²+2B(r,v)t+f(r)=0, with B(r,v)=vᵀ(Ar+a). A double root gives B²−(vᵀAv)f(r)=0. Require vᵀAv≠0 and regular contact; asymptotic directions need a separate check.', tex`B(r,v)^2-(v^TAv)f(r)=0`)],
  eigen: [exercise('Cari nilai eigen dan arah utama A=[[3,1],[1,3]].', 'Find the eigenvalues and principal directions of A=[[3,1],[1,3]].', 'det(A−λI)=(3−λ)²−1=0 memberi λ=4,2. Eigenvector unit masing-masing (1,1)/√2 dan (1,−1)/√2 saling ortogonal.', 'det(A−λI)=(3−λ)²−1=0 gives λ=4,2. Unit eigenvectors are (1,1)/√2 and (1,−1)/√2, respectively, and are orthogonal.', tex`Q^TAQ=\operatorname{diag}(4,2)`)],
  reduce: [exercise('Reduksi 3x²+2xy+3y²=4 ke bentuk kanonik.', 'Reduce3x²+2xy+3y²=4 to canonical form.', 'Gunakan eigenbasis sebelumnya dengan X=(x+y)/√2, Y=(x−y)/√2. Bentuknya4X²+2Y²=4, jadi elips dengan semisumbu1 dan√2.', 'Use the eigenbasis above with X=(x+y)/√2 and Y=(x−y)/√2. The form is4X²+2Y²=4, an ellipse with semiaxes1 and√2.', tex`X^2+Y^2/2=1`)],
  affine: [exercise('Buktikan peta afin menjaga rasio sederhana dan kesejajaran.', 'Prove that an affine map preserves simple ratios and parallelism.', 'φ(p+t(q−p))=φ(p)+tA(q−p)=φ(p)+t(φ(q)−φ(p)). Parameter t tetap. Dua arah sejajar v dan kv dipetakan ke Av dan kAv. Jika A invertibel, arah tak nol tidak runtuh.', 'φ(p+t(q−p))=φ(p)+tA(q−p)=φ(p)+t(φ(q)−φ(p)). Parameter t stays unchanged. Parallel directions v and kv map to Av and kAv. Invertibility prevents nonzero directions from collapsing.', tex`\phi((1-t)p+tq)=(1-t)\phi(p)+t\phi(q)`)],
  isometry: [exercise('Tunjukkan Q ortogonal menjaga hasil kali skalar, bukan hanya norm.', 'Show that orthogonal Q preserves dot products, not just norms.', '(Qu)·(Qv)=uᵀQᵀQv=u·v. Untuk isometri afin, translasi menghilang dalam selisih dua titik. detQ²=1 memberi orientasi langsung atau tak langsung.', '(Qu)·(Qv)=uᵀQᵀQv=u·v. For an affine isometry, translation cancels in point differences. detQ²=1 gives direct or indirect orientation.', tex`(Qu)^T(Qv)=u^Tv,\quad(\det Q)^2=1`)],
  geoMotions: [
    exercise('Apa komposisi dua refleksi pada garis sejajar x=0 dan x=a, dalam urutan tersebut?', 'What is the composition of reflections in parallel lines x=0 and x=a, in that order?', 'Pertama x↦−x; kedua x↦2a−x. Hasil x↦x+2a, y tetap: translasi 2a. Dua refleksi memberi isometri langsung. Secara umum isometri merupakan komposisi sejumlah hingga refleksi hiperbidang.', 'First x↦−x; then x↦2a−x. The result is x↦x+2a with y unchanged: a translation by 2a. Two reflections give a direct isometry. In general, an isometry is a finite composition of hyperplane reflections.', tex`S_{x=a}\circ S_{x=0}(x,y)=(x+2a,y)`),
    exercise('Apakah simetri terhadap sumbu z di ruang 3D selalu membalik orientasi?', 'Does symmetry about the z axis in 3D reverse orientation?', 'Tidak. Peta (x,y,z)↦(−x,−y,z) mempunyai matriks diag(−1,−1,1) dan determinan +1; ini rotasi 180° sekitar sumbu z. Refleksi terhadap bidang, yang membalik satu arah saja, punya determinan −1.', 'No. The map (x,y,z)↦(−x,−y,z) has matrix diag(−1,−1,1) and determinant +1; it is a 180° rotation about z. A plane reflection, which reverses just one direction, has determinant −1.', tex`\det\operatorname{diag}(-1,-1,1)=1`),
    exercise('Mengapa dua segitiga kongruen tak segaris yang titik sudutnya dipasangkan menentukan satu isometri bidang?', 'Why do two corresponding noncollinear congruent triangles determine a unique planar isometry?', 'Bingkai independen menentukan peta afin unik. Kesamaan ketiga sisi mempertahankan norm kedua vektor basis dan norm selisihnya; identitas polarisasi lalu menjaga hasil kali skalar. Dengan demikian matriks liniernya ortogonal. Di ruang, argumen sama berlaku untuk dua tetrahedron kongruen tak sebidang. Orientasi pasangan menentukan det +1 atau −1.', 'Independent frames determine a unique affine map. Equality of all three sides preserves the norms of both basis vectors and their difference; polarization then preserves their dot product. Thus the linear matrix is orthogonal. The same argument applies to two corresponding noncoplanar congruent tetrahedra in space. Their relative orientation determines determinant +1 or −1.', tex`u\cdot v=\tfrac12(\|u\|^2+\|v\|^2-\|u-v\|^2)`),
  ],
}
